-- AQARI V267 Staging: additive persisted core for collection accounts, reserves and tenant credit/debit ledger.
begin;
create table if not exists private.aqari_tenant_preferences(workspace_id uuid not null,tenant_id uuid not null,preferred_channel text not null check(preferred_channel in('both','email','whatsapp','phone','none','sms','push')),consent_at timestamptz,revision integer not null default 1 check(revision>0),updated_by uuid not null,updated_at timestamptz not null default now(),primary key(workspace_id,tenant_id),foreign key(workspace_id,tenant_id) references public.aqari_tenants(workspace_id,id));
create table if not exists private.aqari_collection_accounts(id uuid primary key,workspace_id uuid not null,property_id uuid not null,kind text not null check(kind in('bank','cashbox')),name text not null,masked_reference text not null,currency text not null default 'KWD' check(currency='KWD'),status text not null default 'active' check(status in('active','inactive')),created_by uuid not null,created_at timestamptz not null default now(),unique(workspace_id,id),foreign key(workspace_id,property_id) references public.aqari_properties(workspace_id,id),check(length(btrim(name)) between 1 and 200),check(length(masked_reference)<=200),check(masked_reference !~ '[0-9]{8,}'));
create table if not exists private.aqari_collection_postings(id uuid primary key,workspace_id uuid not null,payment_id uuid not null references public.aqari_rent_payments(id),account_id uuid not null,amount numeric(15,3) not null check(amount>0),posted_by uuid not null,posted_at timestamptz not null default now(),unique(workspace_id,payment_id),foreign key(workspace_id,account_id) references private.aqari_collection_accounts(workspace_id,id));
create table if not exists private.aqari_reserve_entries(id uuid primary key,workspace_id uuid not null,property_id uuid not null,direction text not null check(direction in('hold','release')),amount numeric(15,3) not null check(amount>0),reason text not null check(length(btrim(reason))>=3),source_id uuid,actor_id uuid not null,created_at timestamptz not null default now(),unique(workspace_id,id),foreign key(workspace_id,property_id) references public.aqari_properties(workspace_id,id));
create table if not exists private.aqari_tenant_ledger_entries(id uuid primary key,workspace_id uuid not null,tenant_id uuid not null,lease_id uuid,direction text not null check(direction in('debit','credit')),kind text not null,amount numeric(15,3) not null check(amount>0),occurred_on date not null,reason text not null check(length(btrim(reason))>=3),source_type text not null,source_id text not null,actor_id uuid not null,created_at timestamptz not null default now(),unique(workspace_id,id),unique(workspace_id,source_type,source_id),foreign key(workspace_id,tenant_id) references public.aqari_tenants(workspace_id,id),foreign key(workspace_id,lease_id) references public.aqari_leases(workspace_id,id));
create table if not exists private.aqari_credit_allocations(id uuid primary key,workspace_id uuid not null,credit_entry_id uuid not null,lease_id uuid not null,period date not null,amount numeric(15,3) not null check(amount>0),actor_id uuid not null,created_at timestamptz not null default now(),unique(workspace_id,id),unique(workspace_id,credit_entry_id,lease_id,period),foreign key(workspace_id,credit_entry_id) references private.aqari_tenant_ledger_entries(workspace_id,id),foreign key(workspace_id,lease_id) references public.aqari_leases(workspace_id,id),check(period=date_trunc('month',period)::date));
do $$declare n text;begin foreach n in array array['aqari_tenant_preferences','aqari_collection_accounts','aqari_collection_postings','aqari_reserve_entries','aqari_tenant_ledger_entries','aqari_credit_allocations'] loop execute format('alter table private.%I enable row level security',n);execute format('revoke all on private.%I from public,anon,authenticated,service_role',n);end loop;end$$;
drop trigger if exists aqari_postings_immutable on private.aqari_collection_postings;create trigger aqari_postings_immutable before update or delete on private.aqari_collection_postings for each row execute function private.aqari_reject_immutable_change();
drop trigger if exists aqari_reserves_immutable on private.aqari_reserve_entries;create trigger aqari_reserves_immutable before update or delete on private.aqari_reserve_entries for each row execute function private.aqari_reject_immutable_change();
drop trigger if exists aqari_tenant_ledger_immutable on private.aqari_tenant_ledger_entries;create trigger aqari_tenant_ledger_immutable before update or delete on private.aqari_tenant_ledger_entries for each row execute function private.aqari_reject_immutable_change();
drop trigger if exists aqari_credit_allocations_immutable on private.aqari_credit_allocations;create trigger aqari_credit_allocations_immutable before update or delete on private.aqari_credit_allocations for each row execute function private.aqari_reject_immutable_change();
commit;
