import {t as translateStatic} from '../components/locale.js';
import {createDialog,node,field} from '../components/dialog.js';
import {mountCommercialSales} from './commercial-sales.js';
const el=(tag,text='')=>node(tag,String(text));const option=(v,t)=>{const o=el('option',t);o.value=v;return o;};const input=(type='text')=>{const x=el('input');x.type=type;return x;};const uuid=()=>crypto.randomUUID();
const money=v=>{v=String(v).trim().replace(/٫/g,'.');if(!/^\d{1,9}(?:\.\d{1,3})?$/.test(v)||Number(v)<=0)throw Error('المبلغ غير صالح.');return Number(v).toFixed(3);};
const req=(v,n,l=2)=>{v=String(v??'').trim();if(v.length<l)throw Error(n+' مطلوب.');return v;};
function select(items,placeholder,label='name'){const s=el('select');s.append(option('',placeholder));for(const x of items)s.append(option(x.id,x[label]||x.title||x.id));s.required=true;return s;}
export function openComplianceCenter(){
 const d=createDialog(translateStatic('العقود التجارية والخدمات وفحص الوحدات'));if(!d)return;let data,pending=false;
 const notice=el('p','كل اعتماد محمي بالتوثيق الثنائي، ويُعاد استرجاع السجل بعد الحفظ. التوقيع هنا مستند محفوظ مرتبط بهوية الحساب وليس رسماً شكلياً.');
 const commercial=el('section'),charges=el('section'),inspections=el('section'),monthlySales=el('section');d.body.append(notice,commercial,monthlySales,charges,inspections);mountCommercialSales(d,monthlySales);
 const rpc=(domain,action,payload={})=>d.session.request(d.session.client.rpc('aqari_compliance_register',{p_workspace_id:d.session.bound.workspace,p_domain:domain,p_action:action,p_data:payload}));
 async function load(proof){data=await rpc('commercial','list');if(!Array.isArray(data.leases)||!Array.isArray(data.commercial)||!Array.isArray(data.allocations)||!Array.isArray(data.inspections))throw Error('تعذر استرجاع سجل المطابقة.');render();if(proof&&!proof(data))throw Error('لم تتطابق إعادة القراءة مع العملية المحفوظة.');}
 async function write(domain,action,payload,proof){if(pending)throw Error('عملية قيد التحقق.');pending=true;try{await rpc(domain,action,payload);await load(proof);d.status.textContent=translateStatic('تم الحفظ والتحقق بإعادة القراءة.');}finally{pending=false;}}
 function run(...args){d.run(()=>write(...args));}
 function renderCommercial(){commercial.replaceChildren(el('h2','خصائص العقود التجارية والنشاط المرخص'));const f=el('form'),lease=select(data.leases,'اختر العقد','contract_no'),grace=input('number'),sales=input('number'),basis=el('select'),cam=input(),activity=input(),license=input(),expiry=input('date'),reference=input();basis.append(option('additional_to_base_rent','النسبة إضافة إلى الإيجار الأساسي'),option('greater_of_base_or_percentage','الأكبر من الإيجار الأساسي أو نسبة المبيعات'));grace.min='0';grace.max='366';sales.min='0';sales.max='100';sales.step='0.0001';for(const x of [grace,sales,basis,cam,activity,license,reference])x.required=true;f.append(field(translateStatic('العقد'),lease),field(translateStatic('أيام السماح'),grace),field(translateStatic('نسبة المبيعات %'),sales),field(translateStatic('أساس احتساب إيجار المبيعات'),basis),field(translateStatic('CAM د.ك'),cam),field(translateStatic('النشاط المسموح'),activity),field(translateStatic('رقم الرخصة'),license),field(translateStatic('انتهاء الرخصة'),expiry),field(translateStatic('مرجع مراجعة الالتزام'),reference),el('button','حفظ واعتماد'));lease.onchange=()=>{const old=data.commercial.find(x=>x.lease_id===lease.value);grace.value=String(old?.grace_days??0);sales.value=String(old?.sales_percentage??0);basis.value=old?.sales_rent_basis||'additional_to_base_rent';cam.value=Number(old?.cam_amount??0).toFixed(3);activity.value=old?.permitted_activity||'';license.value=old?.license_no||'';expiry.value=old?.license_expires_on||'';reference.value=old?.compliance_reference||'';};
 f.onsubmit=e=>{e.preventDefault();const old=data.commercial.find(x=>x.lease_id===lease.value),payload={id:lease.value,revision:old?.revision||0,grace_days:Number(grace.value),sales_percentage:Number(sales.value),sales_rent_basis:basis.value,cam_amount:Number(cam.value||0).toFixed(3),permitted_activity:req(activity.value,'النشاط'),license_no:req(license.value,'الرخصة'),license_expires_on:expiry.value||null,compliance_reference:req(reference.value,'مرجع المراجعة',5)};run('commercial','save',payload,x=>x.commercial.some(row=>row.lease_id===payload.id&&row.revision===payload.revision+1&&Number(row.grace_days)===payload.grace_days&&Number(row.sales_percentage)===payload.sales_percentage&&row.sales_rent_basis===payload.sales_rent_basis&&Number(row.cam_amount)===Number(payload.cam_amount)&&row.permitted_activity===payload.permitted_activity&&row.license_no===payload.license_no&&(row.license_expires_on||null)===payload.license_expires_on&&row.compliance_reference===payload.compliance_reference));};commercial.append(f);for(const x of data.commercial){const basisLabel=x.sales_rent_basis==='greater_of_base_or_percentage'?'الأكبر من الإيجار/النسبة':'النسبة إضافة إلى الإيجار';commercial.append(el('p',`${data.leases.find(l=>l.id===x.lease_id)?.contract_no||x.lease_id} • سماح ${x.grace_days} • مبيعات ${x.sales_percentage}% • ${basisLabel} • CAM ${x.cam_amount} • ${x.permitted_activity}`));}}
 function renderCharges(){charges.replaceChildren(el('h2','توزيع فواتير الخدمات المشتركة'));const f=el('form'),property=select(data.properties,'اختر العقار'),reference=input(),basis=el('select'),total=input(),lines=el('section');basis.append(option('area','حسب المساحة'),option('consumption','حسب الاستهلاك'));for(const x of [reference,total])x.required=true;const amounts=new Map();function rows(){lines.replaceChildren();amounts.clear();for(const l of data.leases.filter(x=>x.property_id===property.value&&x.status==='signed'&&x.start_date<=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuwait'})&&x.end_date>=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuwait'}))){const a=input();a.inputMode='decimal';amounts.set(l.unit_id,a);lines.append(field(`الوحدة ${l.unit_id} — العقد ${l.contract_no}`,a));}}property.onchange=rows;f.append(field(translateStatic('العقار'),property),field(translateStatic('مرجع الفاتورة'),reference),field(translateStatic('أساس التوزيع'),basis),field(translateStatic('الإجمالي'),total),lines,el('button','اعتماد التوزيع'));f.onsubmit=e=>{e.preventDefault();const allocations=[...amounts].filter(([,a])=>a.value.trim()).map(([unit_id,a])=>({unit_id,amount:money(a.value)}));const id=uuid();run('common_charges','allocate',{id,property_id:property.value,invoice_reference:req(reference.value,'المرجع',3),basis:basis.value,total_amount:money(total.value),allocations},x=>x.allocations.some(row=>row.id===id));};charges.append(f);for(const x of data.allocations)charges.append(el('p',`${x.invoice_reference} • ${x.basis} • ${Number(x.total_amount).toFixed(3)} د.ك`));}
 function renderInspections(){inspections.replaceChildren(el('h2','قائمة فحص الوحدة والصور والتوقيع'));const f=el('form'),lease=select(data.leases,'اختر العقد','contract_no'),kind=el('select'),date=input('datetime-local'),checklist=el('textarea'),photos=el('select');for(const [v,l]of [['move_in','دخول'],['periodic','دوري'],['renewal','قبل التجديد'],['move_out','إخلاء']])kind.append(option(v,l));photos.multiple=true;for(const x of data.documents)photos.append(option(x.id,x.title));checklist.placeholder=translateStatic('كل بند في سطر');checklist.required=true;f.append(field(translateStatic('العقد'),lease),field(translateStatic('نوع الفحص'),kind),field(translateStatic('موعد الفحص'),date),field(translateStatic('بنود الفحص'),checklist),field(translateStatic('صور محفوظة (اختيار متعدد)'),photos),el('button','حفظ مسودة الفحص'));f.onsubmit=e=>{e.preventDefault();const id=uuid(),items=checklist.value.split('\n').map(x=>x.trim()).filter(Boolean).map(item=>({item,result:'recorded'}));run('inspections','create',{id,lease_id:lease.value,kind:kind.value,inspected_at:date.value||null,checklist:items,photo_document_ids:[...photos.selectedOptions].map(x=>x.value)},x=>x.inspections.some(row=>row.id===id&&row.status==='draft'));};inspections.append(f);
  for(const x of data.inspections){const card=el('article');card.append(el('p',`${x.kind} • ${x.status} • ${x.inspected_at}`));if(x.status==='draft'){const sf=el('form'),tenant=select(data.documents.filter(d=>d.property_id===data.leases.find(l=>l.id===x.lease_id)?.property_id),'توقيع المستأجر','title'),inspector=select(data.documents.filter(d=>d.property_id===data.leases.find(l=>l.id===x.lease_id)?.property_id),'توقيع الفاحص','title');sf.append(field(translateStatic('مستند توقيع المستأجر'),tenant),field(translateStatic('مستند توقيع الفاحص'),inspector),el('button','اعتماد التوقيعين'));sf.onsubmit=e=>{e.preventDefault();run('inspections','sign',{id:x.id,revision:x.revision,tenant_signature_document_id:tenant.value,inspector_signature_document_id:inspector.value},z=>z.inspections.some(row=>row.id===x.id&&row.status==='signed'&&row.revision===x.revision+1));};card.append(sf);}inspections.append(card);}
 }
 function render(){renderCommercial();renderCharges();renderInspections();}
 d.onDispose(()=>{data=null;commercial.replaceChildren();charges.replaceChildren();inspections.replaceChildren();});d.run(load);
}

