import {createDialog,node,field} from '../components/dialog.js';
import {SECTIONS,LANGUAGES,LABEL_KEYS,label,validateSettings} from '../components/catalog.js';
export async function openControlCenter(){
 const dialog=createDialog('مركز تحكم المدير العام');if(!dialog)return;
 const {session,body,status,run}=dialog;let settings,revision,memberRows=[];
 const reload=node('button','تحديث الإعدادات'),save=node('button','حفظ الإعدادات والتحقق'),reason=node('textarea'),content=node('div'),audit=node('div');reason.maxLength=500;reason.rows=2;
 let auditPage=0;const next=node('button','تعديلات أقدم'),previous=node('button','تعديلات أحدث');
 body.append(node('p','تسري الإعدادات داخل مساحة العمل الحالية. لا يمكن سحب صلاحية المدير العام من هذا المركز. الصلاحيات الإضافية تبقى ضمن حدود دور الحساب.'),reload,content,field('سبب التعديل',reason),save,node('h3','سجل التعديلات'),audit,previous,next);
 async function readAudit(){const rows=await session.request(session.client.from('aqari_control_audit').select('id,actor_id,action,reason,before_value,after_value,created_at').eq('workspace_id',session.bound.workspace).order('created_at',{ascending:false}).order('id',{ascending:false}).range(auditPage*20,auditPage*20+19));audit.replaceChildren();
  for(const row of rows){const details=node('details'),name=memberRows.find(m=>m.user_id===row.actor_id)?.display_name||'مستخدم محفوظ';details.append(node('summary',new Date(row.created_at).toLocaleString('ar-KW')+' • '+name),node('p',row.reason),node('pre',JSON.stringify({قبل:row.before_value,بعد:row.after_value},null,2)));audit.append(details);}if(!rows.length)audit.append(node('p','لا توجد تعديلات في هذه الصفحة.'));previous.hidden=auditPage===0;next.hidden=rows.length<20;}
 function render(){content.replaceChildren();const sections=node('details');sections.open=true;sections.append(node('summary','تشغيل الأقسام وإيقافها'));
  for(const key of SECTIONS){const c=node('input');c.type='checkbox';c.checked=settings.sections[key]!==false;const l=field(label(key),c);l.className='aq267-check';c.onchange=()=>settings.sections[key]=c.checked;sections.append(l);}content.append(sections);
  const permissions=node('details');permissions.append(node('summary','صلاحيات الأدوار والحسابات'));const subjects=node('select');for(const [id,title]of [['role:property_manager','مدير العقار'],['role:accountant','المحاسب'],['role:viewer','عرض فقط'],...memberRows.filter(m=>m.is_active&&m.role!=='general_manager').map(m=>['user:'+m.user_id,m.display_name||'حساب محفوظ'])]){const o=node('option',title);o.value=id;subjects.append(o);}const cells=node('div');permissions.append(field('تحديد الدور أو الحساب',subjects),node('p','«حسب الافتراضي» يرث صلاحيات الدور. صلاحية الحفظ تتطلب العرض أيضاً. حساب العرض لا يتحول إلى محرر، والمحاسب لا يعدّل العقود والحصص.'),cells);
  function renderPermissions(){cells.replaceChildren();for(const key of SECTIONS){const card=node('article');card.append(node('h3',label(key)));for(const [action,title]of [['read','العرض'],['write','الإضافة والتعديل']]){const select=node('select');for(const [value,text]of [['inherit','حسب الافتراضي'],['true','مسموح'],['false','ممنوع']]){const o=node('option',text);o.value=value;select.append(o);}const value=settings.permissions[subjects.value]?.[key]?.[action];select.value=typeof value==='boolean'?String(value):'inherit';select.onchange=()=>{const subject=settings.permissions[subjects.value]??={};const section=subject[key]??={};if(select.value==='inherit')delete section[action];else section[action]=select.value==='true';};card.append(field(title,select));}cells.append(card);}}subjects.onchange=renderPermissions;renderPermissions();content.append(permissions);
  const labels=node('details'),locale=node('select'),names=node('div');labels.append(node('summary','مسميات التنقل والأقسام'));for(const [value,text]of Object.entries(LANGUAGES)){const o=node('option',text);o.value=value;locale.append(o);}labels.append(field('اللغة',locale),node('p','تغيير المسميات لا يغيّر مفاتيح الأقسام أو البيانات. هذه الإعدادات تخص مسميات التنقل؛ نصوص النماذج والعقود تبقى عربية.'),names);
  function renderLabels(){names.replaceChildren();for(const key of LABEL_KEYS){const input=node('input');input.maxLength=80;input.value=settings.labels[locale.value]?.[key]||'';input.placeholder=label(key,locale.value);input.oninput=()=>{const entries=settings.labels[locale.value]??={};if(input.value.trim())entries[key]=input.value.trim();else delete entries[key];};names.append(field(label(key),input));}}locale.onchange=renderLabels;renderLabels();content.append(labels);
 }
 async function load(){const data=await session.request(session.client.rpc('aqari_control_center',{p_workspace_id:session.bound.workspace}));settings=structuredClone(data.control.settings);revision=Number(data.control.revision);memberRows=data.members;render();await readAudit();status.textContent='تمت قراءة الإعدادات وسجل التدقيق من قاعدة البيانات.';}
 reload.onclick=()=>run(load);save.onclick=()=>run(async()=>{if(reason.value.trim().length<3)throw Error('اكتب سبب التعديل أولاً.');validateSettings(settings);const expected=structuredClone(settings),nextRevision=await session.request(session.client.rpc('aqari_save_controls',{p_workspace_id:session.bound.workspace,p_settings:expected,p_expected_revision:revision,p_reason:reason.value.trim()}));const verified=await session.request(session.client.rpc('aqari_control_center',{p_workspace_id:session.bound.workspace}));
  if(Number(verified.control.revision)!==Number(nextRevision)||JSON.stringify(canonical(verified.control.settings))!==JSON.stringify(canonical(expected)))throw Error('لم تتأكد إعادة القراءة. حدّث الإعدادات.');revision=Number(nextRevision);reason.value='';await readAudit();window.dispatchEvent(new CustomEvent('aqari:v267-controls-changed'));status.textContent='تم الحفظ وإعادة القراءة وتسجيل التعديل.';});
 next.onclick=()=>run(async()=>{auditPage++;await readAudit();status.textContent='سجل التعديلات المحفوظ.';});previous.onclick=()=>run(async()=>{if(auditPage>0)auditPage--;await readAudit();status.textContent='سجل التعديلات المحفوظ.';});await run(load);
}
function canonical(x){return x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x;}
