import {t,message} from '../components/locale.js';
import {createDialog,node} from '../components/dialog.js';
import {currentScope} from '../api/session.js';
import {inspectQuality} from '../components/data-quality.mjs';
const labels={rent_payment_without_reference:'تحصيل إيجار بلا رقم وصل — يحتاج مراجعة',rent_payment_without_method:'تحصيل إيجار بلا طريقة دفع — يحتاج مراجعة',rent_payment_without_lease:'تحصيل إيجار بلا ربط بعقد — يحتاج مراجعة',rent_payment_lease_not_in_scan:'تحصيل إيجار بمرجع عقد غير موجود ضمن السجلات المقروءة — يحتاج مراجعة',rent_payment_scope_not_checked:'حركات تحصيل إيجار لم يكتمل نطاق فحص ربطها',rent_payment_duplicate_reference:'حركات تحصيل إيجار تحمل رقم وصل مكرر — تحتاج مراجعة',document_without_record_link:'مستندات بلا مرجع سجل مكتمل — تحتاج مراجعة',document_scope_not_checked:'مستندات خارج نطاق الربط المفحوص — لم يُحسم ربطها',document_record_not_in_scan:'مستندات بمرجع غير موجود ضمن السجلات المقروءة — تحتاج مراجعة',document_ambiguous_record:'مستندات بمرجع يطابق أكثر من سجل — تحتاج مراجعة',lease_without_unit:'عقود بلا ربط بوحدة — تحتاج مراجعة',lease_unit_not_in_scan:'عقود بمرجع وحدة غير موجود ضمن السجلات المقروءة — تحتاج مراجعة',lease_without_tenant:'عقود بلا ربط بمستأجر — تحتاج مراجعة',lease_tenant_not_in_scan:'عقود بمرجع مستأجر غير موجود ضمن السجلات المقروءة — تحتاج مراجعة',duplicate_unit:'رقم وحدة مكرر داخل العقار — يحتاج مراجعة',property_without_units:'عقار تشغيلي بلا وحدات — يحتاج استكمال',possible_duplicate_civil_id:'رقم مدني مشترك بين ملفات — مرشح للمراجعة',shared_phone_review:'هاتف مشترك — لا يثبت تكرار الشخص',missing_name:'اسم مستأجر غير مسجل',draft_leases:'عقود مسودة — ليست عقوداً تشغيلية معتمدة',pending_contract_dates:'تواريخ عقود معلقة — يلزم المرجع المعتمد'};
export function openDataQuality(){
 if(currentScope().role!=='general_manager')throw Error('لا تملك صلاحية هذه العملية.');
 const d=createDialog(t('مركز جودة البيانات'),{localized:true});if(!d)return;
 d.body.append(node('p',t('فحص للقراءة فقط. لا يدمج السجلات ولا يصحح القيم. البريد الإلكتروني اختياري، والهاتف المشترك لا يعني تكرار المستأجر.')));
 d.body.append(node('p',t('يشمل الفحص السجلات المتاحة لصلاحياتك فقط. غياب الملاحظات لا يثبت اكتمال الأرشيف، ولا يشمل هذا الفحص محتوى الملفات أو سلامة نسخها المخزنة.')));
 d.body.append(node('p',t('فحص التحصيل يراجع رقم وصل الإيجار وربطه بالعقد ووجود طريقة الدفع فقط؛ لا يعتمد المبالغ أو التسويات، ولا يراجع مراجع التحويل البنكي أو بقية الدفاتر.')));
 const output=node('div'),refresh=node('button',t('فحص السجلات المحفوظة'));d.body.append(refresh,output);
 async function read(table,columns){const rows=[];for(let offset=0;;offset+=250){const page=await d.session.request(d.session.client.from(table).select(columns).eq('workspace_id',d.session.bound.workspace).order('id').range(offset,offset+249));rows.push(...page);if(page.length<250)return rows;if(rows.length>=10000)throw Error('تجاوز عدد السجلات حد الفحص؛ لم يكتمل التقرير.');}}
 function scan(){return d.run(async()=>{output.replaceChildren();const properties=await read('aqari_properties','id,name,metadata,external_ref');const units=await read('aqari_units','id,property_id,unit_no');const tenants=await read('aqari_tenants','id,full_name,civil_id,phone,external_ref');const leases=await read('aqari_leases','id,status,start_date,end_date,unit_id,tenant_id,external_ref');const documents=await read('aqari_documents','id,document_no,entity_type,entity_ref,status');const rentPayments=await read('aqari_rent_payments','id,lease_id,reference,payment_method,status');const findings=inspectQuality({properties,units,tenants,leases,documents,rentPayments}),paymentReferences=new Map(rentPayments.map(row=>[row.id,row.reference?.trim()?row.reference+' · '+row.id:row.id])),documentNumbers=new Map(documents.map(row=>[row.id,row.document_no||row.id])),propertyNames=new Map(properties.map(row=>[row.id,row.name||row.id]));d.session.check();output.append(node('p',message('تمت قراءة {units} وحدة و{tenants} ملف مستأجر و{leases} عقداً و{documents} مستندًا و{payments} حركة تحصيل إيجار من مساحة العمل الحالية.',{units:units.length,tenants:tenants.length,leases:leases.length,documents:documents.length,payments:rentPayments.length})));for(const f of findings){const detail=node('details'),values=f.kind==='property_without_units'?f.ids.map(id=>propertyNames.get(id)||id):f.kind.startsWith('document_')?f.ids.map(id=>documentNumbers.get(id)||id):f.kind.startsWith('rent_payment_')?f.ids.map(id=>paymentReferences.get(id)||id):f.ids;detail.append(node('summary',t(labels[f.kind])+' ('+f.ids.length+')'),node('p',t(f.kind==='property_without_units'?'العقارات: ':f.kind.startsWith('document_')?'أرقام المستندات: ':f.kind.startsWith('rent_payment_')?'مراجع حركات التحصيل ومعرّفاتها: ':'معرّفات السجلات: ')+values.join(t('، '))));output.append(detail);}if(!findings.length)output.append(node('p',t('لم يرصد هذا الفحص المحدود ملاحظات. لا يمثل ذلك اعتماداً شاملاً للبيانات.')));d.status.textContent=t('اكتمل الفحص للقراءة فقط. التعارضات المصدرية المعروفة تبقى معلقة دون تغيير.');});}
 refresh.onclick=scan;scan();
}
