import {createDialog,node,field} from '../components/dialog.js';
import {createPrivateUrls} from '../components/private-urls.js';
import {createVerifiedUpload} from '../components/verified-upload.js';
import {PROFILE_FIELDS,ADDITIONS,DEDUCTIONS,PERMISSIONS,STATES,METHODS,money,netPay,kuwaitTime,currentMonth,voucherHTML,validateDocument} from '../domain/payroll.js';
const statusLabels={active:'نشط / Active',leave:'في إجازة / On leave',inactive:'غير نشط / Inactive'};
const employeeSearchKey=value=>String(value??'').normalize('NFKC').toLowerCase().replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/\s+/g,' ').trim();
function input(type='text',value=''){const x=node('input');x.type=type;x.value=value??'';return x;}
function select(options,value){const x=node('select');for(const [v,label]of Object.entries(options)){const o=node('option',label);o.value=v;x.append(o);}if(value!==undefined)x.value=value;return x;}
export function openEmployees(){
 const d=createDialog('الموظفون والرواتب / Employees and payroll');if(!d)return;
 const urls=createPrivateUrls(d);let directory={employees:[],properties:[]},directoryView=null;const directoryFilters={query:'',state:'',property:'',page:1};
 const rpc=(action,data={})=>d.session.request(d.session.client.rpc('aqari_hr',{p_workspace_id:d.session.bound.workspace,p_action:action,p_data:data}));
 const button=(label,fn)=>{const b=node('button',label);b.type='button';b.onclick=()=>d.run(fn);return b;};
 function clear(title){directoryView=null;urls.clear();d.body.replaceChildren(node('h3',title));}
 function grid(){const el=node('div');el.className='aq267-grid';return el;}
 function propertyChoices(values=[]){const wrap=node('fieldset'),available=new Set(directory.properties.map(p=>p.id));wrap.append(node('legend','العقارات المصرح بها / Assigned properties'));for(const p of [...directory.properties,...values.filter(id=>!available.has(id)).map(id=>({id,name:'عقار غير متاح حالياً — ألغِ اختياره قبل الحفظ'}))]){const c=input('checkbox');c.value=p.id;c.checked=values.includes(p.id);if(!available.has(p.id))c.onchange=()=>{if(!c.checked)c.disabled=true;};wrap.append(field(p.name,c));}const selected=()=>[...wrap.querySelectorAll('input:checked')].map(x=>x.value);return {el:wrap,values:selected,validate:()=>{if(selected().some(id=>!available.has(id)))throw Error('يوجد عقار مرتبط غير متاح حالياً. ألغِ اختياره صراحة قبل الحفظ أو ارجع بعد استعادة إتاحته.');}};}
 function audit(rows){const box=node('details');box.append(node('summary','سجل التعديلات — آخر 100 / Audit log'));for(const r of rows){const item=node('details');item.append(node('summary',`${r.actor_name} · ${kuwaitTime(r.at)} · ${r.operation} · ${r.entity}`),node('pre',JSON.stringify({before:r.before_value,after:r.after_value},null,2)));box.append(item);}d.body.append(box);}
 async function loadDirectory(){directory=await rpc('list');}
 async function home(){await loadDirectory();clear('دليل الموظفين / Employee directory');d.body.append(node('p','تُجهز مسودات الرواتب تلقائياً يوم 28 الساعة 9 صباحاً بتوقيت الكويت. تتم المراجعة والإصدار والاعتماد والصرف بشكل منفصل.'));
  d.body.append(button('تحديث من قاعدة البيانات / Refresh',home),button('إضافة موظف / Add employee',async()=>editEmployee(null)));
  if(directory.manager)d.body.append(button('صلاحيات حسابات الموظفين / Account permissions',access));
  const view={};directoryView=view;
  const propertyOptions={'':'جميع العقارات / All properties',...Object.fromEntries(directory.properties.map(p=>[p.id,p.name]))};
  if(directoryFilters.property&&!Object.hasOwn(propertyOptions,directoryFilters.property))propertyOptions[directoryFilters.property]='العقار المحدد غير متاح حالياً / Selected property unavailable';
  const search=input('search',directoryFilters.query),stateFilter=select({'':'جميع الحالات / All statuses',...statusLabels},directoryFilters.state),propertyFilter=select(propertyOptions,directoryFilters.property),filters=grid(),summary=node('p'),results=node('p'),list=node('div'),pager=grid(),previous=node('button','السابق / Previous'),next=node('button','التالي / Next'),pageLabel=node('p');
  previous.type=next.type='button';pager.append(previous,next);
  summary.className='aq267-note';summary.textContent=`الملفات المتاحة لك: ${directory.employees.length} · نشط: ${directory.employees.filter(e=>e.status==='active').length} · في إجازة: ${directory.employees.filter(e=>e.status==='leave').length} · غير نشط: ${directory.employees.filter(e=>e.status==='inactive').length}`;
  results.setAttribute('role','status');results.setAttribute('aria-live','polite');
  filters.append(field('البحث بالاسم أو الهاتف / Search',search),field('تصفية حسب الحالة / Filter by status',stateFilter),field('تصفية حسب العقار / Filter by property',propertyFilter));
  const reset=node('button','مسح البحث والفلاتر / Clear filters');reset.type='button';reset.onclick=()=>{if(d.closed||directoryView!==view)return;search.value=stateFilter.value=propertyFilter.value='';updateFilters();};
  d.body.append(summary,filters,reset,results,list,pageLabel,pager);
  function updateFilters(){if(d.closed||directoryView!==view)return;Object.assign(directoryFilters,{query:search.value,state:stateFilter.value,property:propertyFilter.value,page:1});draw();}
  previous.onclick=()=>{if(d.closed||directoryView!==view||previous.disabled)return;directoryFilters.page--;draw();};next.onclick=()=>{if(d.closed||directoryView!==view||next.disabled)return;directoryFilters.page++;draw();};
  function draw(){
   if(d.closed||directoryView!==view)return;list.replaceChildren();const matches=[],q=employeeSearchKey(search.value),phoneQuery=/^[+\d\s().-]+$/.test(q)?q.replace(/\D/g,''):'';
   for(const e of directory.employees){
    if(stateFilter.value&&e.status!==stateFilter.value)continue;
    if(propertyFilter.value&&!(e.property_ids||[]).includes(propertyFilter.value))continue;
    const p=e.profile||{},phone=employeeSearchKey(p.phone);
    if(![p.name_ar,p.name_en,p.phone].some(v=>employeeSearchKey(v).includes(q))&&!(phoneQuery&&phone.replace(/\D/g,'').includes(phoneQuery)))continue;
    matches.push(e);
   }
   const pages=Math.max(1,Math.ceil(matches.length/20));directoryFilters.page=Math.max(1,Math.min(directoryFilters.page,pages));const start=(directoryFilters.page-1)*20;
   for(const e of matches.slice(start,start+20)){const p=e.profile||{};
    const name=[p.name_ar,p.name_en].filter(Boolean).join(' / ')||'ملف موظف / Employee record',card=node('article');
    card.append(node('h4',name),node('p',(p.job_ar||p.job_en||'الوظيفة غير مسجلة / Job not recorded')+' · '+(statusLabels[e.status]||'الحالة غير مسجلة / Status not recorded')),button('فتح ملف '+(p.name_ar||p.name_en||'الموظف'),()=>showEmployee(e.id)));list.append(card);
   }
   results.textContent=`نتائج البحث: ${matches.length} من ${directory.employees.length} ملف متاح لك`;
   pageLabel.textContent=matches.length?`عرض ${start+1}–${Math.min(start+20,matches.length)} · الصفحة ${directoryFilters.page} من ${pages}`:'';pager.hidden=pages<=1;pager.style.display=pages<=1?'none':'';previous.disabled=directoryFilters.page<=1;next.disabled=directoryFilters.page>=pages;
   if(!list.children.length)list.append(node('p','لا توجد ملفات موظفين مطابقة ضمن صلاحيتك.'));
  }search.oninput=stateFilter.onchange=propertyFilter.onchange=updateFilters;draw();d.status.textContent='تمت قراءة دليل الموظفين من قاعدة البيانات.';
 }
 async function editEmployee(record){const e=record?.employee,id=e?.id||crypto.randomUUID();clear(e?'تعديل بيانات الموظف / Edit employee':'موظف جديد / New employee');d.body.append(button('الرجوع للدليل / Back',async()=>{if(draft()!==baseline)throw Error('توجد تعديلات غير محفوظة. احفظها أو اختر تجاهل التعديلات والرجوع للدليل.');await home();}));const form=node('form'),g=grid(),controls={};
  for(const [key,label]of PROFILE_FIELDS){const c=input(key==='phone'?'tel':'text',e?.profile?.[key]);c.required=true;c.maxLength=200;controls[key]=c;g.append(field(label,c));}
  const nationalityEn=input('text',e?.profile?.nationality_en||'');nationalityEn.maxLength=200;g.append(field('الجنسية بالإنجليزي / Nationality in English',nationalityEn));
  const hired=input('date',e?.hired_on),basic=input('text',e?.basic??''),allowances=input('text',e?.allowances??'0'),status=select(statusLabels,e?.status||'active'),props=propertyChoices(e?.property_ids);hired.required=basic.required=allowances.required=true;basic.inputMode=allowances.inputMode='decimal';g.append(field('تاريخ التعيين / Hire date',hired),field('الراتب الأساسي — د.ك / Basic KWD',basic),field('البدلات الشهرية — د.ك / Monthly allowances',allowances),field('حالة الموظف / Status',status));
  const account=select({'':'بدون حساب دخول / No login account',...Object.fromEntries((directory.members||[]).map(m=>[m.user_id,m.name]))},e?.user_id||'');if(directory.manager)g.append(field('ربط حساب الموظف / Linked login account',account));
  const save=node('button','حفظ الموظف والتحقق / Save and verify');save.type='submit';form.append(g,props.el,node('p','الإضافي والخصومات وقسط السلفة تُحدد لكل شهر داخل الراتب. تُسجل السلف والإجازات والمستندات بعد حفظ الملف.'),save);const draft=()=>JSON.stringify({profile:Object.fromEntries(Object.entries(controls).map(([k,c])=>[k,c.value])),nationality_en:nationalityEn.value,hired:hired.value,basic:basic.value,allowances:allowances.value,status:status.value,account:account.value,properties:props.values().sort()}),baseline=draft();
  d.body.append(form,button('التحقق من الحفظ بعد انقطاع الاتصال / Check saved record',async()=>{const result=await rpc('get',{employee_id:id});if(result.employee?.id!==id)throw Error('لم يتأكد العثور على ملف الموظف. بقيت تعديلاتك في النموذج.');d.status.textContent='يوجد ملف محفوظ للموظف. بقيت تعديلات النموذج كما هي؛ وجود الملف لا يؤكد حفظ آخر تعديل. راجع الملف من الدليل قبل إعادة الحفظ.';}),button('تجاهل التعديلات والرجوع للدليل / Discard and return',home));d.status.textContent='أكمل البيانات ثم احفظها. البيانات الإلزامية مبيّنة في النموذج.';
  form.onsubmit=event=>{event.preventDefault();const payload={employee_id:id,revision:e?.revision||0,...(directory.manager?{user_id:account.value||null}:{}),profile:{...Object.fromEntries(Object.entries(controls).map(([k,c])=>[k,c.value.trim()])),nationality_en:nationalityEn.value.trim()},property_ids:props.values(),hired_on:hired.value,status:status.value,basic:basic.value,allowances:allowances.value};d.run(async()=>{payload.basic=money(payload.basic);payload.allowances=money(payload.allowances);props.validate();if(!payload.property_ids.length)throw Error('اختر عقاراً واحداً على الأقل.');await rpc('save_employee',payload);await loadDirectory();await showEmployee(id);d.status.textContent='تم حفظ الموظف وإعادة قراءة ملفه من قاعدة البيانات.';});};
 }
 async function showEmployee(id){const r=await rpc('get',{employee_id:id}),e=r.employee;clear(e.profile.name_ar+' / '+e.profile.name_en);d.body.append(button('الرجوع للدليل / Back',home),button('تحديث الملف / Reload employee',()=>showEmployee(id)));if(r.permissions.edit)d.body.append(button('تعديل بيانات الموظف / Edit employee',()=>editEmployee(r)));
  const profile=node('dl');for(const [key,label]of PROFILE_FIELDS)profile.append(node('dt',label),node('dd',e.profile[key]));profile.append(node('dt','التعيين والحالة / Hire date and status'),node('dd',e.hired_on+' · '+statusLabels[e.status]),node('dt','العقارات / Properties'),node('dd',directory.properties.filter(p=>e.property_ids.includes(p.id)).map(p=>p.name).join('، ')),node('dt','الأساسي والبدلات — د.ك / Basic and allowances'),node('dd',`${e.basic} + ${e.allowances}`),node('dt','رصيد السلف المتبقي — د.ك / Outstanding advances'),node('dd',r.advance_balance));d.body.append(profile);
  const month=input('month',currentMonth());d.body.append(field('شهر الراتب / Payroll month',month));if(r.permissions.add)d.body.append(button('تجهيز راتب الشهر / Prepare monthly salary',async()=>{if(!month.value)throw Error('اختر شهر الراتب.');const fresh=await rpc('prepare',{employee_id:id,month:month.value+'-01'});const p=fresh.payroll.find(p=>p.month.startsWith(month.value));if(!p)throw Error('لم يتأكد تجهيز الراتب.');await showPayroll(id,p.id);d.status.textContent='تم تجهيز مسودة الراتب وحفظها. تكرار الطلب لا ينشئ راتباً ثانياً للشهر نفسه.';}));
  d.body.append(node('h3','الرواتب الشهرية / Monthly payroll'));for(const p of r.payroll)d.body.append(button(`${p.month.slice(0,7)} · ${STATES[p.state]} · ${Number(p.net).toFixed(3)} د.ك`,()=>showPayroll(id,p.id)));if(!r.payroll.length)d.body.append(node('p','لا توجد رواتب محفوظة.'));
  const events=node('section');events.append(node('h3','السلف والإجازات / Advances and leave'));for(const x of r.events){const card=node('article');card.append(node('p',`${x.kind==='advance'?'سلفة / Advance':'إجازة / Leave'} · ${x.on_date}${x.until_date?' — '+x.until_date:''} · ${x.amount??''} · ${x.notes}`));if(r.permissions.edit)card.append(button('تعديل السجل / Edit entry',async()=>{clear('تعديل سلفة أو إجازة');d.body.append(button('العودة للموظف',()=>showEmployee(id)));eventForm(id,x);}));events.append(card);}d.body.append(events);if(r.permissions.add)eventForm(id);
  d.body.append(node('h3','المستندات وعقد العمل / Documents and employment contract'));documents(r.documents.filter(x=>!x.payroll_id),id);if(r.permissions.add)uploadForm(id,null);
  audit(r.audit);d.status.textContent='تم فتح الملف والرواتب والمستندات المحفوظة.';
 }
 function eventForm(id,existing=null){const box=node('details');box.append(node('summary','إضافة سلفة أو إجازة / Add advance or leave'));const f=node('form'),kind=select({advance:'سلفة مدفوعة / Disbursed advance',leave:'إجازة / Leave'}),date=input('date'),until=input('date'),amount=input('text'),notes=node('textarea'),save=node('button','حفظ السجل / Save entry');if(existing){kind.value=existing.kind;date.value=existing.on_date;until.value=existing.until_date||'';amount.value=existing.amount??'';notes.value=existing.notes;box.open=true;}date.required=notes.required=true;notes.maxLength=1000;amount.inputMode='decimal';const amountField=field('مبلغ السلفة المدفوع — د.ك / Advance disbursed',amount),untilField=field('نهاية الإجازة / Leave end',until);function mode(){amount.required=kind.value==='advance';until.required=kind.value==='leave';amountField.hidden=!amount.required;untilField.hidden=!until.required;}kind.onchange=mode;mode();f.append(field('نوع السجل / Type',kind),field('التاريخ / Date',date),untilField,amountField,field('سبب ومرجع السجل / Reason and reference',notes),save);box.append(f);d.body.append(box);if(existing)d.status.textContent='عدّل السجل مع توثيق سبب التصحيح في الملاحظات.';const requestId=existing?.id||crypto.randomUUID();f.onsubmit=event=>{event.preventDefault();const data={employee_id:id,id:requestId,revision:existing?.revision||0,kind:kind.value,on_date:date.value,until_date:until.value||null,amount:amount.value,notes:notes.value.trim()};d.run(async()=>{if(data.kind==='advance')data.amount=money(data.amount);await rpc(existing?'edit_event':'event',data);await showEmployee(id);d.status.textContent='حُفظ السجل مع اسم المستخدم والتوقيت. قسط السلفة يُحدد يدوياً في راتب الشهر.';});};}
 function documents(rows,id){if(!rows.length)d.body.append(node('p','لا توجد مستندات محفوظة.'));for(const doc of rows){const card=node('article');card.append(node('p',`${doc.filename} · ${doc.kind==='signed_salary'?'راتب موقّع / Signed salary':doc.kind==='employment_contract'?'عقد عمل / Employment contract':'مستند / Document'} · ${doc.status==='ready'?'محفوظ / Saved':'رفع غير مؤكد / Unconfirmed'}`));
  card.append(button('فتح المستند '+doc.filename,async()=>{const blob=await d.session.storage('GET',doc.storage_path,undefined,'aqari-hr-private');const url=urls.create(blob),a=node('a','فتح النسخة الأصلية / Open original'),download=node('a','تحميل / Download');a.href=download.href=url;a.target='_blank';a.rel='noopener';download.download=doc.filename;card.append(a,download);d.status.textContent='تم استرجاع الملف من التخزين الخاص.';}));
  if(doc.status==='reserved'){const check=input('checkbox');card.append(node('p','قد يكون الرفع قد اكتمل قبل انقطاع الاتصال. افتح الملف أولاً ثم أكد حفظه. إذا لم يوجد الملف، أعد رفعه من النموذج.'),field(doc.kind==='signed_salary'?'راجعت الملف ويحتوي التوقيع والبصمة والختم الفعلية / Reviewed actual signature, fingerprint and stamp':'راجعت الملف المرفوع / Reviewed uploaded file',check),button('التحقق وإكمال الحفظ / Confirm stored file',async()=>{if(!check.checked)throw Error('راجع المستند وأكد محتواه أولاً.');await rpc('finalize',{employee_id:id,id:doc.id,attestations:doc.kind==='signed_salary'?{signature:true,fingerprint:true,stamp:true}:{}});if(doc.payroll_id)await showPayroll(id,doc.payroll_id);else await showEmployee(id);d.status.textContent='تم التحقق من الملف وإكمال حفظه.';}));}d.body.append(card);
 }}
 function uploadForm(id,payroll){const f=node('form'),kind=select(payroll?{signed_salary:'نسخة راتب موقعة / Signed salary'}:{document:'مستند موظف / Employee document',employment_contract:'عقد عمل / Employment contract'}),file=input('file'),save=node('button','رفع وحفظ المستند / Upload and save');file.accept='application/pdf,image/jpeg,image/png';file.required=true;f.append(field('نوع المستند / Document type',kind),field('المستند — PDF أو PNG/JPEG حتى 10 MB',file));const checks={};if(payroll){for(const [k,label]of Object.entries({signature:'تحتوي النسخة توقيع الموظف الفعلي / Actual employee signature',fingerprint:'تحتوي النسخة بصمة الموظف الفعلية / Actual fingerprint',stamp:'تحتوي النسخة ختم الإدارة الفعلي / Actual administration stamp'})){checks[k]=input('checkbox');checks[k].required=true;f.append(field(label,checks[k]));}f.append(node('p','هذه التأكيدات توثّق مراجعتك للمرفق؛ لا تُنشئ توقيعاً أو بصمة أو اعتماداً إلكترونياً.'));}f.append(save);d.body.append(f);let requestId=crypto.randomUUID(),selected=null,pending=null;
  function resetUpload(){requestId=crypto.randomUUID();pending=null;for(const check of Object.values(checks))check.checked=false;}
  file.onchange=()=>{if(selected!==file.files?.[0]){selected=file.files?.[0];resetUpload();}};kind.onchange=resetUpload;
  f.onsubmit=event=>{event.preventDefault();const chosen=file.files?.[0],docKind=kind.value,attestations=Object.fromEntries(Object.entries(checks).map(([k,c])=>[k,c.checked]));d.run(async()=>{
   await validateDocument(chosen);d.session.check();
   if(payroll&&Object.values(attestations).some(value=>!value))throw Error('أكد وجود التوقيع والبصمة وختم الإدارة في النسخة الفعلية.');
   const doc=await rpc('reserve',{employee_id:id,id:requestId,payroll_id:payroll?.id||null,kind:docKind,filename:chosen.name,mime_type:chosen.type,size_bytes:chosen.size});
   if(doc?.id!==requestId||doc.workspace_id!==d.session.bound.workspace||doc.employee_id!==id||doc.payroll_id!==(payroll?.id||null)||doc.kind!==docKind||doc.created_by!==d.session.bound.user||!doc.storage_path?.startsWith(d.session.bound.workspace+'/'))throw Error('تعارض مرجع الرفع.');
   if(!pending)pending=createVerifiedUpload(d.session,{path:doc.storage_path,blob:chosen,bucket:'aqari-hr-private',readFirst:doc.status==='ready'});
   await pending();
   if(doc.status!=='ready')await rpc('finalize',{employee_id:id,id:doc.id,attestations});
   const result=await rpc('get',{employee_id:id}),verified=result.documents?.find(row=>row.id===doc.id);
   if(!verified||verified.status!=='ready'||verified.storage_path!==doc.storage_path||verified.kind!==docKind||verified.payroll_id!==(payroll?.id||null))throw Error('لم تتأكد إعادة قراءة سجل المستند.');
   if(payroll)await showPayroll(id,payroll.id);else await showEmployee(id);d.status.textContent='تم تأكيد الملف في التخزين الخاص وإعادة قراءة بياناته المحفوظة.';
  });};
 }
 async function showPayroll(id,payrollId){const r=await rpc('get',{employee_id:id}),p=r.payroll.find(x=>x.id===payrollId);if(!p)throw Error('الراتب غير موجود.');clear('راتب '+p.month.slice(0,7)+' / Salary');d.body.append(button('العودة لملف الموظف / Employee file',()=>showEmployee(id)),button('إعادة فتح الراتب من قاعدة البيانات / Reload salary',()=>showPayroll(id,p.id)),node('p',p.snapshot.name_ar+' / '+p.snapshot.name_en),node('p',STATES[p.state]),node('p','رقم السند / Voucher: '+(p.voucher_no||p.id)),node('p','صافي المستحق / Net: '+Number(p.net).toFixed(3)+' د.ك'));
  const f=node('form'),g=grid(),fields={};for(const [key,label]of [...ADDITIONS,...DEDUCTIONS]){const c=input('text',p[key]??0);c.inputMode='decimal';c.required=true;c.disabled=p.state!=='draft'||!r.permissions.edit||['basic','allowances'].includes(key);fields[key]=c;g.append(field(label+' — د.ك / KWD',c));}
  const slip=p.slip_details||{template:'standard'},template=select({standard:'سند عقاري / AQARI voucher','dhahawi-v1':'نموذج برج ضحاوي الكامل / Dhahawi Salary Slip'},slip.template),payerAr=input('text',slip.payer_ar||''),payerEn=input('text',slip.payer_en||'');
  for(const c of [template,payerAr,payerEn])c.disabled=p.state!=='draft'||!r.permissions.edit;payerAr.maxLength=payerEn.maxLength=200;
  const arField=field('اسم مسؤول الصرف بالعربي / Payer Arabic name',payerAr),enField=field('اسم مسؤول الصرف بالإنجليزي / Payer English name',payerEn);function templateMode(){arField.hidden=enField.hidden=template.value!=='dhahawi-v1';}template.onchange=templateMode;templateMode();g.append(field('نموذج سند الراتب / Salary slip template',template),arField,enField);
  const slipData=()=>({template:template.value,payer_ar:payerAr.value.trim(),payer_en:payerEn.value.trim()});
  const method=select(METHODS,p.method),reference=input('text',p.reference),notes=node('textarea');notes.value=p.notes;reference.maxLength=120;notes.maxLength=1000;for(const c of [method,reference,notes])c.disabled=p.state!=='draft'||!r.permissions.edit;g.append(field('طريقة الصرف / Method',method),field('رقم المرجع / Reference',reference),field('ملاحظات / Notes',notes));f.append(g);d.body.append(f,node('p','الأساسي والبدلات وبيانات الموظف محفوظة كما كانت عند تجهيز هذا الراتب. تعديل ملف الموظف لا يغيّر الرواتب السابقة. بند السلفة في المستحقات يخص سلفة جديدة تُصرف مع الراتب؛ قسط السلفة السابقة في الخصومات. لا تكرر السلفة نفسها في سجل السلف. تُثبت في الرصيد عند إثبات الصرف فقط.'));
  if(p.state==='draft'&&r.permissions.edit){const save=node('button','حفظ تعديلات الراتب / Save salary');f.append(save);f.onsubmit=event=>{event.preventDefault();const data={employee_id:id,payroll_id:p.id,revision:p.revision,...Object.fromEntries(Object.entries(fields).map(([k,c])=>[k,c.value])),slip_details:slipData(),method:method.value,reference:reference.value.trim(),notes:notes.value.trim()};d.run(async()=>{for(const key of Object.keys(fields))data[key]=money(data[key]);netPay(data);await rpc('save_payroll',data);await showPayroll(id,p.id);d.status.textContent='تم حفظ الراتب والتحقق من صافي المستحق من قاعدة البيانات.';});};d.body.append(button('إصدار الراتب المحفوظ وتثبيت بياناته / Issue saved salary',async()=>{if(Object.entries(fields).some(([k,c])=>Number(c.value)!==Number(p[k]??0))||template.value!==slip.template||payerAr.value!==(slip.payer_ar||'')||payerEn.value!==(slip.payer_en||'')||method.value!==p.method||reference.value!==p.reference||notes.value!==p.notes)throw Error('احفظ تعديلات الراتب قبل إصداره.');await rpc('issue',{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent='تم إصدار الراتب. بياناته المالية ثابتة، وبانتظار الاعتمادات.';}));}
  for(const [key,label]of [['admin','المدير الإداري / Administrative manager'],['chairman','رئيس مجلس الإدارة / Chairman']]){const approval=p[key+'_approval'];d.body.append(node('p',label+': '+(approval?approval.name+' · '+kuwaitTime(approval.at):'بانتظار الاعتماد / Pending')));if(!approval&&p.state==='issued'&&r.permissions['approve_'+key])d.body.append(button('اعتماد '+label,async()=>{await rpc('approve_'+key,{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent='حُفظ الاعتماد باسم الحساب الحالي وتوقيته.';}));}
  const voucher=node('a','فتح سند راتب عربي/إنجليزي للطباعة أو الحفظ PDF / Print salary voucher');voucher.href=urls.create(new Blob([voucherHTML(p)],{type:'text/html;charset=utf-8'}));voucher.target='_blank';voucher.rel='noopener';d.body.append(voucher);
  d.body.append(node('h3','أرشيف '+p.month.slice(0,4)+' / '+p.month.slice(5,7)+' — النسخ الموقعة'));documents(r.documents.filter(x=>x.payroll_id===p.id),id);if(p.state!=='draft'&&r.permissions.add)uploadForm(id,p);
  if(p.state==='issued'&&r.permissions.edit)d.body.append(button('إثبات صرف الراتب بعد التوقيع والاعتماد / Record paid salary',async()=>{await rpc('paid',{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent='حُفظ الصرف وخصم قسط السلفة مرة واحدة من رصيدها.';}));if(p.paid_at)d.body.append(node('p','تاريخ إثبات الصرف / Paid: '+kuwaitTime(p.paid_at)));d.status.textContent='تمت إعادة قراءة الراتب المحفوظ.';
 }
 async function access(){const data=await rpc('access');clear('صلاحيات حسابات الموظفين / Account permissions');d.body.append(button('الرجوع للدليل / Back',home),node('p','الصلاحيات تخص الحسابات النشطة. تُطبق أيضاً قيود القسم والدور من مركز تحكم المدير. الوصول لملف مرتبط بعدة عقارات يتطلب التصريح بجميع عقاراته. الاعتمادان يحتاجان حسابين مختلفين.'));const f=node('form'),user=select(Object.fromEntries(data.members.map(m=>[m.user_id,m.name+' · '+m.role]))),props=propertyChoices(),checks={};for(const [key,label]of Object.entries(PERMISSIONS)){checks[key]=input('checkbox');f.append(field(label,checks[key]));}const save=node('button','حفظ الصلاحيات / Save permissions');f.prepend(field('الحساب / Account',user),props.el);f.append(save);d.body.append(f);audit(data.audit||[]);let revision=0;function fill(){const grant=data.grants.find(g=>g.user_id===user.value);revision=grant?.revision||0;for(const [key,c]of Object.entries(checks))c.checked=grant?.permissions[key]===true;for(const c of props.el.querySelectorAll('input'))c.checked=grant?.property_ids.includes(c.value)||false;}user.onchange=fill;fill();d.status.textContent='اختر الحساب والعقارات وحدد صلاحياته.';f.onsubmit=event=>{event.preventDefault();const payload={user_id:user.value,property_ids:props.values(),permissions:Object.fromEntries(Object.entries(checks).map(([k,c])=>[k,c.checked])),revision};d.run(async()=>{await rpc('grant',payload);await access();d.status.textContent='حُفظت الصلاحيات مع سجل التعديل. إلغاء العرض يمنع الوصول فوراً.';});};}
 d.onDispose(()=>{directoryView=null;Object.assign(directoryFilters,{query:'',state:'',property:'',page:1});directory={employees:[],properties:[]};d.body.replaceChildren();});d.run(home);
}
