import {message as visibleMessage} from '../components/locale.js';
import {t as translateStatic} from '../components/locale.js';
import {createDialog,node,field} from '../components/dialog.js';
import {createPrivateUrls} from '../components/private-urls.js';
import {createVerifiedUpload} from '../components/verified-upload.js';
import {PROFILE_FIELDS,ADDITIONS,DEDUCTIONS,PERMISSIONS,STATES,METHODS,money,netPay,kuwaitTime,currentMonth,voucherHTML,validateDocument} from '../domain/payroll.js';
const statusLabels={active:'نشط / Active',leave:'في إجازة / On leave',inactive:'غير نشط / Inactive'};
const employeeSearchKey=value=>String(value??'').normalize('NFKC').toLowerCase().replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/\s+/g,' ').trim();
function input(type='text',value=''){const x=node('input');x.type=type;x.value=value??'';return x;}
function select(options,value){const x=node('select');for(const [v,label]of Object.entries(options)){const o=node('option',label);o.value=v;x.append(o);}if(value!==undefined)x.value=value;return x;}
export function openEmployees(){
 const d=createDialog(translateStatic('الموظفون والرواتب / Employees and payroll'));if(!d)return;
 const urls=createPrivateUrls(d);let directory={employees:[],properties:[]};
 const rpc=(action,data={})=>d.session.request(d.session.client.rpc('aqari_hr',{p_workspace_id:d.session.bound.workspace,p_action:action,p_data:data}));
 const button=(label,fn)=>{const b=node('button',label);b.type='button';b.onclick=()=>d.run(fn);return b;};
 function clear(title){d.setBeforeClose?.(null);urls.clear();d.body.replaceChildren(node('h3',title));}
 function grid(){const el=node('div');el.className='aq267-grid';return el;}
 function propertyChoices(values=[]){const wrap=node('fieldset'),available=new Set(directory.properties.map(p=>p.id));wrap.append(node('legend',translateStatic('العقارات المصرح بها / Assigned properties')));for(const p of [...directory.properties,...values.filter(id=>!available.has(id)).map(id=>({id,name:translateStatic('عقار غير متاح حالياً — ألغِ اختياره قبل الحفظ')}))]){const c=input('checkbox');c.value=p.id;c.checked=values.includes(p.id);if(!available.has(p.id))c.onchange=()=>{if(!c.checked)c.disabled=true;};wrap.append(field(p.name,c));}const selected=()=>[...wrap.querySelectorAll('input:checked')].map(x=>x.value);return {el:wrap,values:selected,validate:()=>{if(selected().some(id=>!available.has(id)))throw Error('يوجد عقار مرتبط غير متاح حالياً. ألغِ اختياره صراحة قبل الحفظ أو ارجع بعد استعادة إتاحته.');}};}
 function audit(rows){const box=node('details');box.append(node('summary',translateStatic('سجل التعديلات — آخر 100 / Audit log')));for(const r of rows){const item=node('details');item.append(node('summary',`${r.actor_name} · ${kuwaitTime(r.at)} · ${r.operation} · ${r.entity}`),node('pre',JSON.stringify({before:r.before_value,after:r.after_value},null,2)));box.append(item);}d.body.append(box);}
 async function loadDirectory(){directory=await rpc('list');}
 async function home(){await loadDirectory();clear(translateStatic('دليل الموظفين / Employee directory'));d.body.append(node('p',translateStatic('تُجهز مسودات الرواتب تلقائياً يوم 28 الساعة 9 صباحاً بتوقيت الكويت. تتم المراجعة والإصدار والاعتماد والصرف بشكل منفصل.')));
  d.body.append(button(translateStatic('تحديث من قاعدة البيانات / Refresh'),home),button(translateStatic('إضافة موظف / Add employee'),async()=>editEmployee(null)));
  d.body.append(button(translateStatic('دورة الموظفين والرواتب الكاملة / Complete HR lifecycle'),async()=>{d.close();const module=await import('./hr-lifecycle.js');module.openHrLifecycle();}));
  if(directory.manager)d.body.append(button(translateStatic('صلاحيات حسابات الموظفين / Account permissions'),access));
  const shortcuts=grid();shortcuts.setAttribute?.('aria-label',translateStatic('مستندات الموظفين والرواتب'));
  for(const [icon,title,section] of [['📄','عقد عمل / Employment contract','contract'],['💼','عقد راتب / Salary contract','salary_contract'],['🧾','سند راتب / Salary voucher','salary'],['📁','مستندات الموظف / Employee documents','documents'],['📅','السلف والإجازات / Advances and leave','events']]){
   const shortcut=button(icon+' '+translateStatic(title),()=>chooseEmployee(title,section));shortcut.style.minHeight='64px';shortcuts.append(shortcut);
  }d.body.append(shortcuts);
  const search=input('search'),list=node('div');d.body.append(field(translateStatic('البحث بالاسم أو الهاتف / Search'),search),list);
  function draw(){
   if(d.closed)return;list.replaceChildren();const q=employeeSearchKey(search.value),phoneQuery=/^[+\d\s().-]+$/.test(q)?q.replace(/\D/g,''):'';
   for(const e of directory.employees){
    const p=e.profile||{},phone=employeeSearchKey(p.phone);
    if(![p.name_ar,p.name_en,p.phone].some(v=>employeeSearchKey(v).includes(q))&&!(phoneQuery&&phone.replace(/\D/g,'').includes(phoneQuery)))continue;
    const name=[p.name_ar,p.name_en].filter(Boolean).join(' / ')||translateStatic('ملف موظف / Employee record'),card=node('article');
    card.append(node('h4',name),node('p',(p.job_ar||p.job_en||translateStatic('الوظيفة غير مسجلة / Job not recorded'))+' · '+(translateStatic(statusLabels[e.status])||translateStatic('الحالة غير مسجلة / Status not recorded'))),button(translateStatic('فتح ملف ')+(p.name_ar||p.name_en||translateStatic('الموظف')),()=>showEmployee(e.id)));list.append(card);
   }
   if(!list.children.length)list.append(node('p',translateStatic('لا توجد ملفات موظفين مطابقة ضمن صلاحيتك.')));
  }search.oninput=draw;draw();d.status.textContent=translateStatic('تمت قراءة دليل الموظفين من قاعدة البيانات.');
 }
 async function chooseEmployee(title,section){
  clear(translateStatic(title));d.body.append(button(translateStatic('الرجوع للدليل / Back'),home),node('p',translateStatic('اختر الموظف لفتح مستنداته المحفوظة.')));
  if(!directory.employees.length){d.body.append(node('p',translateStatic('لا توجد ملفات موظفين مطابقة ضمن صلاحيتك.')),button(translateStatic('إضافة موظف / Add employee'),()=>editEmployee(null)));return;}
  const choices=select(Object.fromEntries(directory.employees.map(e=>[e.id,[e.profile?.name_ar,e.profile?.name_en].filter(Boolean).join(' / ')||translateStatic('ملف موظف / Employee record')])));
  d.body.append(field(translateStatic('الموظف'),choices),button(translateStatic('فتح ملف الموظف'),()=>showEmployee(choices.value,section)));d.status.textContent=translateStatic('اختر الموظف أولاً.');
 }
 async function editEmployee(record){const e=record?.employee,id=e?.id||crypto.randomUUID();clear(e?translateStatic('تعديل بيانات الموظف / Edit employee'):translateStatic('موظف جديد / New employee'));d.body.append(button(translateStatic('الرجوع للدليل / Back'),async()=>{if(draft()!==baseline)throw Error('توجد تعديلات غير محفوظة. احفظها أو اختر تجاهل التعديلات والرجوع للدليل.');await home();}));const form=node('form'),g=grid(),controls={};
  for(const [key,label]of PROFILE_FIELDS){const c=input(key==='phone'?'tel':'text',e?.profile?.[key]);c.required=true;c.maxLength=200;controls[key]=c;g.append(field(translateStatic(label),c));}
  const nationalityEn=input('text',e?.profile?.nationality_en||'');nationalityEn.maxLength=200;g.append(field(translateStatic('الجنسية بالإنجليزي / Nationality in English'),nationalityEn));
  const hired=input('date',e?.hired_on),basic=input('text',e?.basic??''),allowances=input('text',e?.allowances??'0'),status=select(Object.fromEntries(Object.entries(statusLabels).map(([key,label])=>[key,translateStatic(label)])),e?.status||'active'),props=propertyChoices(e?.property_ids);hired.required=basic.required=allowances.required=true;basic.inputMode=allowances.inputMode='decimal';g.append(field(translateStatic('تاريخ التعيين / Hire date'),hired),field(translateStatic('الراتب الأساسي — د.ك / Basic KWD'),basic),field(translateStatic('البدلات الشهرية — د.ك / Monthly allowances'),allowances),field(translateStatic('حالة الموظف / Status'),status));
  const linkedAccount=e?.user_id||'',availableAccounts=directory.members||[],missingAccount=directory.manager&&linkedAccount&&!availableAccounts.some(member=>member.user_id===linkedAccount);
  const account=select({'':translateStatic('بدون حساب دخول / No login account'),...Object.fromEntries(availableAccounts.map(m=>[m.user_id,m.name])),...(missingAccount?{[linkedAccount]:translateStatic('حساب مرتبط غير متاح حالياً — اختر حساباً نشطاً أو ألغِ الربط صراحةً')}: {})},linkedAccount);if(directory.manager)g.append(field(translateStatic('ربط حساب الموظف / Linked login account'),account));
  const save=node('button',translateStatic('حفظ الموظف والتحقق / Save and verify'));save.type='submit';form.append(g,props.el,node('p',translateStatic('الإضافي والخصومات وقسط السلفة تُحدد لكل شهر داخل الراتب. تُسجل السلف والإجازات والمستندات بعد حفظ الملف.')),save);const draft=()=>JSON.stringify({profile:Object.fromEntries(Object.entries(controls).map(([k,c])=>[k,c.value])),nationality_en:nationalityEn.value,hired:hired.value,basic:basic.value,allowances:allowances.value,status:status.value,account:account.value,properties:props.values().sort()}),baseline=draft();
  d.setBeforeClose?.(()=>draft()===baseline||window.confirm(translateStatic('توجد تعديلات بيانات موظف غير محفوظة. هل تريد إغلاق النافذة وترك هذه التعديلات؟')));
  d.body.append(form,button(translateStatic('التحقق من الحفظ بعد انقطاع الاتصال / Check saved record'),async()=>{const result=await rpc('get',{employee_id:id});if(result.employee?.id!==id)throw Error('لم يتأكد العثور على ملف الموظف. بقيت تعديلاتك في النموذج.');d.status.textContent=translateStatic('يوجد ملف محفوظ للموظف. بقيت تعديلات النموذج كما هي؛ وجود الملف لا يؤكد حفظ آخر تعديل. راجع الملف من الدليل قبل إعادة الحفظ.');}),button(translateStatic('تجاهل التعديلات والرجوع للدليل / Discard and return'),home));d.status.textContent=translateStatic('أكمل البيانات ثم احفظها. البيانات الإلزامية مبيّنة في النموذج.');
  form.onsubmit=event=>{event.preventDefault();const payload={employee_id:id,revision:e?.revision||0,...(directory.manager?{user_id:account.value||null}:{}),profile:{...Object.fromEntries(Object.entries(controls).map(([k,c])=>[k,c.value.trim()])),nationality_en:nationalityEn.value.trim()},property_ids:props.values(),hired_on:hired.value,status:status.value,basic:basic.value,allowances:allowances.value};d.run(async()=>{payload.basic=money(payload.basic);payload.allowances=money(payload.allowances);if(directory.manager&&payload.user_id&&!availableAccounts.some(member=>member.user_id===payload.user_id))throw Error('حساب الدخول المرتبط غير متاح حالياً. اختر حساباً نشطاً أو اختر بدون حساب دخول لإلغاء الربط صراحةً.');props.validate();if(!payload.property_ids.length)throw Error('اختر عقاراً واحداً على الأقل.');await rpc('save_employee',payload);await loadDirectory();await showEmployee(id);d.status.textContent=translateStatic('تم حفظ الموظف وإعادة قراءة ملفه من قاعدة البيانات.');});};
 }
 async function showEmployee(id,section=null){const r=await rpc('get',{employee_id:id}),e=r.employee;clear(e.profile.name_ar+' / '+e.profile.name_en);d.body.append(button(translateStatic('الرجوع للدليل / Back'),home),button(translateStatic('تحديث الملف / Reload employee'),()=>showEmployee(id)));if(r.permissions.edit)d.body.append(button(translateStatic('تعديل بيانات الموظف / Edit employee'),()=>editEmployee(r)));
  if(section==='contract'||section==='salary_contract'||section==='documents'){
   d.body.append(node('h3',translateStatic(section==='contract'?'عقد عمل / Employment contract':section==='salary_contract'?'عقد راتب / Salary contract':'مستندات الموظف / Employee documents')));
   documents(r.documents.filter(x=>!x.payroll_id&&(section==='contract'?x.kind==='employment_contract':section==='salary_contract'?x.kind==='salary_contract':true)),id);
   if(r.permissions.add)uploadForm(id,null,section==='contract'?'employment_contract':section==='salary_contract'?'salary_contract':null);
   d.status.textContent=translateStatic('تم فتح المستندات المحفوظة.');return;
  }
  if(section==='events'){
   d.body.append(node('h3',translateStatic('السلف والإجازات / Advances and leave')));
   for(const x of r.events)d.body.append(node('p',`${x.kind==='advance'?translateStatic('سلفة / Advance'):translateStatic('إجازة / Leave')} · ${x.on_date} · ${x.amount??''} · ${x.notes||''}`));
   if(!r.events.length)d.body.append(node('p',translateStatic('لا توجد سجلات محفوظة.')));
   if(r.permissions.add)eventForm(id);d.status.textContent=translateStatic('تم فتح السجلات المحفوظة.');return;
  }
  if(section!=='salary'){
  const profile=node('dl');for(const [key,label]of PROFILE_FIELDS)profile.append(node('dt',translateStatic(label)),node('dd',e.profile[key]));profile.append(node('dt',translateStatic('التعيين والحالة / Hire date and status')),node('dd',e.hired_on+' · '+translateStatic(statusLabels[e.status])),node('dt',translateStatic('العقارات / Properties')),node('dd',directory.properties.filter(p=>e.property_ids.includes(p.id)).map(p=>p.name).join('، ')),node('dt',translateStatic('الأساسي والبدلات — د.ك / Basic and allowances')),node('dd',`${e.basic} + ${e.allowances}`),node('dt',translateStatic('رصيد السلف المتبقي — د.ك / Outstanding advances')),node('dd',r.advance_balance));d.body.append(profile);
  }
  const month=input('month',currentMonth());d.body.append(field(translateStatic('شهر الراتب / Payroll month'),month));if(r.permissions.add)d.body.append(button(translateStatic('تجهيز راتب الشهر / Prepare monthly salary'),async()=>{if(!month.value)throw Error('اختر شهر الراتب.');const fresh=await rpc('prepare',{employee_id:id,month:month.value+'-01'});const p=fresh.payroll.find(p=>p.month.startsWith(month.value));if(!p)throw Error('لم يتأكد تجهيز الراتب.');await showPayroll(id,p.id);d.status.textContent=translateStatic('تم تجهيز مسودة الراتب وحفظها. تكرار الطلب لا ينشئ راتباً ثانياً للشهر نفسه.');}));
  d.body.append(node('h3',translateStatic('الرواتب الشهرية / Monthly payroll')));for(const p of r.payroll)d.body.append(button(visibleMessage("{p0} · {p1} · {p2} د.ك",{p0:(p.month.slice(0,7)),p1:(translateStatic(STATES[p.state])),p2:(Number(p.net).toFixed(3))}),()=>showPayroll(id,p.id)));if(!r.payroll.length)d.body.append(node('p',translateStatic('لا توجد رواتب محفوظة.')));
  if(section==='salary'){d.status.textContent=translateStatic('تم فتح الرواتب المحفوظة. اختر راتب الشهر لعرض السند وطباعته.');return;}
  const events=node('section');events.append(node('h3',translateStatic('السلف والإجازات / Advances and leave')));for(const x of r.events){const card=node('article');card.append(node('p',`${x.kind==='advance'?translateStatic('سلفة / Advance'):translateStatic('إجازة / Leave')} · ${x.on_date}${x.until_date?' — '+x.until_date:''} · ${x.amount??''} · ${x.notes}`));if(r.permissions.edit)card.append(button(translateStatic('تعديل السجل / Edit entry'),async()=>{clear(translateStatic('تعديل سلفة أو إجازة'));d.body.append(button(translateStatic('العودة للموظف'),()=>showEmployee(id)));eventForm(id,x);}));events.append(card);}d.body.append(events);if(r.permissions.add)eventForm(id);
  d.body.append(node('h3',translateStatic('المستندات وعقد العمل / Documents and employment contract')));documents(r.documents.filter(x=>!x.payroll_id),id);if(r.permissions.add)uploadForm(id,null);
  audit(r.audit);d.status.textContent=translateStatic('تم فتح الملف والرواتب والمستندات المحفوظة.');
 }
 function eventForm(id,existing=null){const box=node('details');box.append(node('summary',translateStatic('إضافة سلفة أو إجازة / Add advance or leave')));const f=node('form'),kind=select({advance:translateStatic('سلفة مدفوعة / Disbursed advance'),leave:translateStatic('إجازة / Leave')}),date=input('date'),until=input('date'),amount=input('text'),notes=node('textarea'),save=node('button',translateStatic('حفظ السجل / Save entry'));if(existing){kind.value=existing.kind;date.value=existing.on_date;until.value=existing.until_date||'';amount.value=existing.amount??'';notes.value=existing.notes;box.open=true;}date.required=notes.required=true;notes.maxLength=1000;amount.inputMode='decimal';const amountField=field(translateStatic('مبلغ السلفة المدفوع — د.ك / Advance disbursed'),amount),untilField=field(translateStatic('نهاية الإجازة / Leave end'),until);function mode(){amount.required=kind.value==='advance';until.required=kind.value==='leave';amountField.hidden=!amount.required;untilField.hidden=!until.required;}kind.onchange=mode;mode();f.append(field(translateStatic('نوع السجل / Type'),kind),field(translateStatic('التاريخ / Date'),date),untilField,amountField,field(translateStatic('سبب ومرجع السجل / Reason and reference'),notes),save);box.append(f);d.body.append(box);if(existing)d.status.textContent=translateStatic('عدّل السجل مع توثيق سبب التصحيح في الملاحظات.');const requestId=existing?.id||crypto.randomUUID();f.onsubmit=event=>{event.preventDefault();const data={employee_id:id,id:requestId,revision:existing?.revision||0,kind:kind.value,on_date:date.value,until_date:until.value||null,amount:amount.value,notes:notes.value.trim()};d.run(async()=>{if(data.kind==='advance')data.amount=money(data.amount);await rpc(existing?'edit_event':'event',data);await showEmployee(id);d.status.textContent=translateStatic('حُفظ السجل مع اسم المستخدم والتوقيت. قسط السلفة يُحدد يدوياً في راتب الشهر.');});};}
 function documents(rows,id){if(!rows.length)d.body.append(node('p',translateStatic('لا توجد مستندات محفوظة.')));for(const doc of rows){const card=node('article');card.append(node('p',`${doc.filename} · ${doc.kind==='signed_salary'?translateStatic('راتب موقّع / Signed salary'):doc.kind==='employment_contract'?translateStatic('عقد عمل / Employment contract'):doc.kind==='salary_contract'?translateStatic('عقد راتب / Salary contract'):translateStatic('مستند / Document')} · ${doc.status==='ready'?translateStatic('محفوظ / Saved'):translateStatic('رفع غير مؤكد / Unconfirmed')}`));
  card.append(button(translateStatic('فتح المستند ')+doc.filename,async()=>{const blob=await d.session.storage('GET',doc.storage_path,undefined,'aqari-hr-private');const url=urls.create(blob),a=node('a',translateStatic('فتح النسخة الأصلية / Open original')),download=node('a',translateStatic('تحميل / Download'));a.href=download.href=url;a.target='_blank';a.rel='noopener';download.download=doc.filename;card.append(a,download);d.status.textContent=translateStatic('تم استرجاع الملف من التخزين الخاص.');}));
  if(doc.status==='reserved'){const check=input('checkbox');card.append(node('p',translateStatic('قد يكون الرفع قد اكتمل قبل انقطاع الاتصال. افتح الملف أولاً ثم أكد حفظه. إذا لم يوجد الملف، أعد رفعه من النموذج.')),field(doc.kind==='signed_salary'?translateStatic('راجعت الملف ويحتوي التوقيع والبصمة والختم الفعلية / Reviewed actual signature, fingerprint and stamp'):translateStatic('راجعت الملف المرفوع / Reviewed uploaded file'),check),button(translateStatic('التحقق وإكمال الحفظ / Confirm stored file'),async()=>{if(!check.checked)throw Error('راجع المستند وأكد محتواه أولاً.');await rpc('finalize',{employee_id:id,id:doc.id,attestations:doc.kind==='signed_salary'?{signature:true,fingerprint:true,stamp:true}:{}});if(doc.payroll_id)await showPayroll(id,doc.payroll_id);else await showEmployee(id);d.status.textContent=translateStatic('تم التحقق من الملف وإكمال حفظه.');}));}d.body.append(card);
 }}
 function uploadForm(id,payroll,defaultKind=null){const f=node('form'),kind=select(payroll?{signed_salary:translateStatic('نسخة راتب موقعة / Signed salary')}:{document:translateStatic('مستند موظف / Employee document'),employment_contract:translateStatic('عقد عمل / Employment contract'),salary_contract:translateStatic('عقد راتب / Salary contract')}),file=input('file'),save=node('button',translateStatic('رفع وحفظ المستند / Upload and save'));if(defaultKind)kind.value=defaultKind;file.accept='application/pdf,image/jpeg,image/png';file.required=true;f.append(field(translateStatic('نوع المستند / Document type'),kind),field(translateStatic('المستند — PDF أو PNG/JPEG حتى 10 MB'),file));const checks={};if(payroll){for(const [k,label]of Object.entries({signature:translateStatic('تحتوي النسخة توقيع الموظف الفعلي / Actual employee signature'),fingerprint:translateStatic('تحتوي النسخة بصمة الموظف الفعلية / Actual fingerprint'),stamp:translateStatic('تحتوي النسخة ختم الإدارة الفعلي / Actual administration stamp')})){checks[k]=input('checkbox');checks[k].required=true;f.append(field(label,checks[k]));}f.append(node('p',translateStatic('هذه التأكيدات توثّق مراجعتك للمرفق؛ لا تُنشئ توقيعاً أو بصمة أو اعتماداً إلكترونياً.')));}f.append(save);d.body.append(f);let requestId=crypto.randomUUID(),selected=null,pending=null;
  function resetUpload(){requestId=crypto.randomUUID();pending=null;for(const check of Object.values(checks))check.checked=false;}
  file.onchange=()=>{if(selected!==file.files?.[0]){selected=file.files?.[0];resetUpload();}};kind.onchange=resetUpload;
  f.onsubmit=event=>{event.preventDefault();const chosen=file.files?.[0],docKind=kind.value,attestations=Object.fromEntries(Object.entries(checks).map(([k,c])=>[k,c.checked]));d.run(async()=>{
   await validateDocument(chosen);d.session.check();
   if(payroll&&Object.values(attestations).some(value=>!value))throw Error('أكد وجود التوقيع والبصمة وختم الإدارة في النسخة الفعلية.');
   const doc=await rpc('reserve',{employee_id:id,id:requestId,payroll_id:payroll?.id||null,kind:docKind,filename:chosen.name,mime_type:chosen.type,size_bytes:chosen.size});
   if(doc?.id!==requestId||doc.workspace_id!==d.session.bound.workspace||doc.employee_id!==id||doc.payroll_id!==(payroll?.id||null)||doc.kind!==docKind||doc.created_by!==d.session.bound.user||!doc.storage_path?.startsWith(d.session.bound.workspace+'/'))throw Error('تعارض مرجع الرفع.');
   if(!pending)pending=createVerifiedUpload(d.session,{path:doc.storage_path,blob:chosen,bucket:'aqari-hr-private',readFirst:doc.status==='ready'});
   await pending();
   if(doc.status!=='ready')await rpc('finalize',{employee_id:id,id:doc.id,attestations});
   const result=await rpc('get',{employee_id:id}),verified=result.documents?.find(row=>row.id===doc.id);
   if(!verified||verified.status!=='ready'||verified.storage_path!==doc.storage_path||verified.kind!==docKind||verified.payroll_id!==(payroll?.id||null))throw Error('لم تتأكد إعادة قراءة سجل المستند.');
   if(payroll)await showPayroll(id,payroll.id);else await showEmployee(id);d.status.textContent=translateStatic('تم تأكيد الملف في التخزين الخاص وإعادة قراءة بياناته المحفوظة.');
  });};
 }
 async function showPayroll(id,payrollId){const r=await rpc('get',{employee_id:id}),p=r.payroll.find(x=>x.id===payrollId);if(!p)throw Error('الراتب غير موجود.');clear(translateStatic('راتب ')+p.month.slice(0,7));d.body.append(button(translateStatic('العودة لملف الموظف / Employee file'),()=>showEmployee(id)),button(translateStatic('إعادة فتح الراتب من قاعدة البيانات / Reload salary'),()=>showPayroll(id,p.id)),node('p',p.snapshot.name_ar+' / '+p.snapshot.name_en),node('p',translateStatic(STATES[p.state])),node('p',translateStatic('رقم السند / Voucher: ')+(p.voucher_no||p.id)),node('p',translateStatic('صافي المستحق / Net: ')+Number(p.net).toFixed(3)+translateStatic(' د.ك')));
  const f=node('form'),g=grid(),fields={};for(const [key,label]of [...ADDITIONS,...DEDUCTIONS]){const c=input('text',p[key]??0);c.inputMode='decimal';c.required=true;c.disabled=p.state!=='draft'||!r.permissions.edit||['basic','allowances'].includes(key);fields[key]=c;g.append(field(translateStatic(label)+translateStatic(' — د.ك / KWD'),c));}
  const slip=p.slip_details||{template:'standard'},template=select({standard:translateStatic('سند عقاري / AQARI voucher'),'dhahawi-v1':translateStatic('نموذج برج ضحاوي الكامل / Dhahawi Salary Slip')},slip.template),payerAr=input('text',slip.payer_ar||''),payerEn=input('text',slip.payer_en||'');
  for(const c of [template,payerAr,payerEn])c.disabled=p.state!=='draft'||!r.permissions.edit;payerAr.maxLength=payerEn.maxLength=200;
  const arField=field(translateStatic('اسم مسؤول الصرف بالعربي / Payer Arabic name'),payerAr),enField=field(translateStatic('اسم مسؤول الصرف بالإنجليزي / Payer English name'),payerEn);function templateMode(){arField.hidden=enField.hidden=template.value!=='dhahawi-v1';}template.onchange=templateMode;templateMode();g.append(field(translateStatic('نموذج سند الراتب / Salary slip template'),template),arField,enField);
  const slipData=()=>({template:template.value,payer_ar:payerAr.value.trim(),payer_en:payerEn.value.trim()});
  const method=select(Object.fromEntries(Object.entries(METHODS).map(([key,label])=>[key,translateStatic(label)])),p.method),reference=input('text',p.reference),notes=node('textarea');notes.value=p.notes;reference.maxLength=120;notes.maxLength=1000;for(const c of [method,reference,notes])c.disabled=p.state!=='draft'||!r.permissions.edit;g.append(field(translateStatic('طريقة الصرف / Method'),method),field(translateStatic('رقم المرجع / Reference'),reference),field(translateStatic('ملاحظات / Notes'),notes));f.append(g);d.body.append(f,node('p',translateStatic('الأساسي والبدلات وبيانات الموظف محفوظة كما كانت عند تجهيز هذا الراتب. تعديل ملف الموظف لا يغيّر الرواتب السابقة. بند السلفة في المستحقات يخص سلفة جديدة تُصرف مع الراتب؛ قسط السلفة السابقة في الخصومات. لا تكرر السلفة نفسها في سجل السلف. تُثبت في الرصيد عند إثبات الصرف فقط.')));
  if(p.state==='draft'&&r.permissions.edit){const save=node('button',translateStatic('حفظ تعديلات الراتب / Save salary'));f.append(save);f.onsubmit=event=>{event.preventDefault();const data={employee_id:id,payroll_id:p.id,revision:p.revision,...Object.fromEntries(Object.entries(fields).map(([k,c])=>[k,c.value])),slip_details:slipData(),method:method.value,reference:reference.value.trim(),notes:notes.value.trim()};d.run(async()=>{for(const key of Object.keys(fields))data[key]=money(data[key]);netPay(data);await rpc('save_payroll',data);await showPayroll(id,p.id);d.status.textContent=translateStatic('تم حفظ الراتب والتحقق من صافي المستحق من قاعدة البيانات.');});};d.body.append(button(translateStatic('إصدار الراتب المحفوظ وتثبيت بياناته / Issue saved salary'),async()=>{if(Object.entries(fields).some(([k,c])=>Number(c.value)!==Number(p[k]??0))||template.value!==slip.template||payerAr.value!==(slip.payer_ar||'')||payerEn.value!==(slip.payer_en||'')||method.value!==p.method||reference.value!==p.reference||notes.value!==p.notes)throw Error('احفظ تعديلات الراتب قبل إصداره.');await rpc('issue',{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent=translateStatic('تم إصدار الراتب. بياناته المالية ثابتة، وبانتظار الاعتمادات.');}));}
  for(const [key,label]of [['admin',translateStatic('المدير الإداري / Administrative manager')],['chairman',translateStatic('رئيس مجلس الإدارة / Chairman')]]){const approval=p[key+'_approval'];d.body.append(node('p',label+': '+(approval?approval.name+' · '+kuwaitTime(approval.at):translateStatic('بانتظار الاعتماد / Pending'))));if(!approval&&p.state==='issued'&&r.permissions['approve_'+key])d.body.append(button(translateStatic('اعتماد ')+label,async()=>{await rpc('approve_'+key,{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent=translateStatic('حُفظ الاعتماد باسم الحساب الحالي وتوقيته.');}));}
  const voucher=node('a',translateStatic('فتح سند راتب عربي/إنجليزي للطباعة أو الحفظ PDF / Print salary voucher'));voucher.href=urls.create(new Blob([voucherHTML(p)],{type:'text/html;charset=utf-8'}));voucher.target='_blank';voucher.rel='noopener';d.body.append(voucher);
  d.body.append(node('h3',translateStatic('أرشيف ')+p.month.slice(0,4)+' / '+p.month.slice(5,7)+translateStatic(' — النسخ الموقعة')));documents(r.documents.filter(x=>x.payroll_id===p.id),id);if(p.state!=='draft'&&r.permissions.add)uploadForm(id,p);
  if(p.state==='issued'&&r.permissions.edit)d.body.append(button(translateStatic('إثبات صرف الراتب بعد التوقيع والاعتماد / Record paid salary'),async()=>{await rpc('paid',{employee_id:id,payroll_id:p.id,revision:p.revision});await showPayroll(id,p.id);d.status.textContent=translateStatic('حُفظ الصرف وخصم قسط السلفة مرة واحدة من رصيدها.');}));if(p.paid_at)d.body.append(node('p',translateStatic('تاريخ إثبات الصرف / Paid: ')+kuwaitTime(p.paid_at)));d.status.textContent=translateStatic('تمت إعادة قراءة الراتب المحفوظ.');
 }
 async function access(prefetched=null,selected=''){
  const data=prefetched||await rpc('access');if(!data||!['members','grants','audit'].every(key=>Array.isArray(data[key])))throw Error('تعذر التحقق من بيانات صلاحيات الموظفين. بقيت الشاشة السابقة دون تغيير.');
  clear(translateStatic('صلاحيات حسابات الموظفين / Account permissions'));
  const f=node('form'),user=select(Object.fromEntries(data.members.map(m=>[m.user_id,m.name+' · '+m.role]))),propertySlot=node('div'),checks={},save=node('button',translateStatic('حفظ الصلاحيات / Save permissions')),recover=button(translateStatic('التحقق من حفظ الصلاحيات السابق'),verify);
  let props,revision=0,selectedUser='',baseline='',pendingGrant=null;
  const values=()=>({user_id:selectedUser,property_ids:props.values().sort(),permissions:Object.fromEntries(Object.entries(checks).map(([key,c])=>[key,c.checked])),revision});
  const dirty=()=>JSON.stringify(values())!==baseline;
  const canLeave=()=>pendingGrant?window.confirm(translateStatic('لم يتأكد حفظ الصلاحيات بعد. هل تريد المغادرة؟ تحقّق من السجل عند العودة قبل إعادة الحفظ.')):!dirty()||window.confirm(translateStatic('توجد تعديلات صلاحيات غير محفوظة. هل تريد تركها؟'));
  d.body.append(button(translateStatic('الرجوع للدليل / Back'),async()=>{if(canLeave())await home();}),node('p',translateStatic('الصلاحيات تخص الحسابات النشطة. تُطبق أيضاً قيود القسم والدور من مركز تحكم المدير. الوصول لملف مرتبط بعدة عقارات يتطلب التصريح بجميع عقاراته. الاعتمادان يحتاجان حسابين مختلفين.')));
  for(const [key,label]of Object.entries(PERMISSIONS)){checks[key]=input('checkbox');f.append(field(translateStatic(label),checks[key]));}
  save.type='submit';f.prepend(field(translateStatic('الحساب / Account'),user),propertySlot);f.append(save);d.body.append(f,recover);audit(data.audit);
  function lock(){f.inert=!!pendingGrant;recover.hidden=!pendingGrant;}
  function fill(){selectedUser=user.value;const grant=data.grants.find(g=>g.user_id===selectedUser);revision=grant?.revision||0;props=propertyChoices(grant?.property_ids||[]);propertySlot.replaceChildren(props.el);for(const [key,c]of Object.entries(checks))c.checked=grant?.permissions[key]===true;baseline=JSON.stringify(values());lock();}
  if(data.members.some(member=>member.user_id===selected))user.value=selected;
  user.onchange=()=>{if(pendingGrant||dirty()&&!window.confirm(translateStatic('توجد تعديلات صلاحيات غير محفوظة. هل تريد تركها؟'))){user.value=selectedUser;return;}fill();};fill();d.setBeforeClose?.(canLeave);d.status.textContent=translateStatic('اختر الحساب والعقارات وحدد صلاحياته.');
  function matches(record,payload){return record?.user_id===payload.user_id&&record.revision===payload.revision+1&&Array.isArray(record.property_ids)&&JSON.stringify([...record.property_ids].sort())===JSON.stringify([...payload.property_ids].sort())&&Object.keys(PERMISSIONS).every(key=>record.permissions?.[key]===payload.permissions[key]);}
  async function verify(){if(!pendingGrant)return;const verified=await rpc('access');if(!Array.isArray(verified?.grants)||!matches(verified.grants.find(g=>g.user_id===pendingGrant.user_id),pendingGrant))throw Error('لم تتأكد مطابقة الصلاحيات المحفوظة. احتُفظ بالطلب؛ تحقّق من السجل قبل إعادة الحفظ.');const account=pendingGrant.user_id;await access(verified,account);d.status.textContent=translateStatic('حُفظت الصلاحيات وتأكدت مطابقة العقارات والخيارات ورقم المراجعة بإعادة القراءة.');}
  f.onsubmit=event=>{event.preventDefault();d.run(async()=>{if(pendingGrant)throw Error('تحقّق من حفظ الصلاحيات السابق أولًا.');props.validate();const payload=values();if(!payload.property_ids.length)throw Error('اختر عقارًا محفوظًا واحدًا على الأقل.');if(!data.members.some(member=>member.user_id===payload.user_id))throw Error('اختر حسابًا نشطًا من القائمة.');pendingGrant=payload;lock();try{await rpc('grant',payload);}catch(error){if([400,404,409,422].includes(Number(error?.status))||['P0001','22023','40001'].includes(error?.code)){pendingGrant=null;lock();}throw error;}await verify();});};
 }

 d.onDispose(()=>{directory={employees:[],properties:[]};d.body.replaceChildren();});d.run(home);
}

