import {createDialog,node,field} from '../components/dialog.js';
const kinds={elevator:'مصعد',air_conditioning:'تكييف',fire_system:'أنظمة إطفاء',water_tank:'خزان مياه',generator:'مولد',plumbing:'تمديدات صحية',electrical:'كهرباء',other:'أخرى'};
const text=(tag,value)=>node(tag,String(value??''));const opt=(value,label)=>{const o=node('option',label);o.value=value;return o;};
function select(items,placeholder){const s=node('select');s.append(opt('',placeholder));for(const item of items)s.append(opt(item.id,item.name||item.title));s.required=true;return s;}
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;}
export function openMaintenancePlans(){
 const d=createDialog('الصيانة الدورية والتنبيهات');if(!d)return;
 let data=null,pending=false;const toolbar=node('div'),reload=node('button','تحديث السجل'),prepare=node('button','تجهيز تنبيهات اليوم'),summary=node('section'),editor=node('section'),plans=node('section'),tasks=node('section'),alerts=node('section');
 reload.type=prepare.type='button';toolbar.append(reload,prepare);d.body.append(text('p','تُجهز التنبيهات في سجل داخلي فقط. لا تُعرض كرسائل مُرسلة حتى يؤكد المزود التسليم.'),toolbar,summary,editor,plans,tasks,alerts);
 const rpc=(action,payload={})=>d.session.request(d.session.client.rpc('aqari_maintenance_plans',{p_workspace_id:d.session.bound.workspace,p_action:action,p_data:payload}));
 async function load(proof){const fresh=await rpc('list');if(!Array.isArray(fresh?.plans)||!Array.isArray(fresh.tasks)||!Array.isArray(fresh.alerts)||!Array.isArray(fresh.properties)||!Array.isArray(fresh.documents))throw Error('تعذر استرجاع سجل الصيانة الدورية.');data=fresh;render();if(proof&&!proof(fresh))throw Error('تعذر مطابقة العملية بعد إعادة القراءة؛ لا تكررها قبل المراجعة.');}
 async function write(action,payload,proof){if(pending)throw Error('عملية سابقة قيد التحقق.');pending=true;render();try{await rpc(action,payload);await load(proof);d.status.textContent='تم الحفظ والتحقق بإعادة القراءة.';}finally{pending=false;render();}}
 function render(){
  if(!data)return;reload.disabled=prepare.disabled=pending;summary.replaceChildren(text('h2','ملخص'),text('p',`الخطط: ${data.plans.length} • المهام: ${data.tasks.length} • التنبيهات المسجلة: ${data.alerts.length}`));
  editor.replaceChildren(text('h2','خطة صيانة جديدة'));const f=node('form'),property=select(data.properties,'اختر العقار'),kind=node('select'),title=node('input'),frequency=node('input'),next=node('input');
  for(const [value,label]of Object.entries(kinds))kind.append(opt(value,label));frequency.type='number';frequency.min='1';frequency.max='730';next.type='date';title.required=frequency.required=next.required=true;
  f.append(field('العقار',property),field('نوع الأصل',kind),field('عنوان الخطة',title),field('التكرار بالأيام',frequency),field('موعد الصيانة القادمة',next),Object.assign(node('button','حفظ الخطة'),{type:'submit'}));
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{if(!validDate(next.value))throw Error('موعد الصيانة غير صالح.');const id=crypto.randomUUID();await write('save',{id,revision:0,property_id:property.value,asset_kind:kind.value,title:title.value.trim(),frequency_days:Number(frequency.value),next_due_on:next.value,warning_days:[90,60,30],is_active:true},x=>x.plans.some(p=>p.id===id&&p.revision===1));});};editor.append(f);
  plans.replaceChildren(text('h2','الخطط المحفوظة'));for(const plan of data.plans){const card=node('article'),create=node('button','إنشاء مهمة من الموعد');create.type='button';card.append(text('h3',plan.title),text('p',`${kinds[plan.asset_kind]||plan.asset_kind} • الموعد ${plan.next_due_on} • كل ${plan.frequency_days} يوماً`),create);create.onclick=()=>d.run(()=>{const taskId=crypto.randomUUID(),taskNo='MT-'+plan.next_due_on.replaceAll('-','')+'-'+taskId.slice(0,8).toUpperCase();return write('generate_task',{id:plan.id,task_id:taskId,task_no:taskNo,description:plan.title},x=>x.tasks.some(t=>t.id===taskId&&t.plan_id===plan.id));});plans.append(card);}
  tasks.replaceChildren(text('h2','مهام الصيانة'));for(const task of data.tasks){const card=node('article');card.append(text('h3',task.task_no),text('p',`${task.status} • الاستحقاق ${task.due_on} • التكلفة ${Number(task.cost).toFixed(3)} د.ك`));if(task.status!=='completed'&&task.status!=='cancelled'){const f=node('form'),doc=select(data.documents.filter(x=>x.property_id===task.property_id).map(x=>({...x,name:(x.document_no?x.document_no+' — ':'')+x.title})),'اختر مستند وصور الإنجاز'),cost=node('input'),reason=node('input');cost.inputMode='decimal';cost.required=reason.required=true;f.append(field('مستند الإنجاز المحفوظ',doc),field('التكلفة د.ك',cost),field('بيان الإنجاز',reason),Object.assign(node('button','اعتماد إكمال المهمة'),{type:'submit'}));f.onsubmit=e=>{e.preventDefault();d.run(()=>write('complete_task',{id:task.id,revision:task.revision,completion_document_id:doc.value,photo_document_ids:[doc.value],cost:cost.value,reason:reason.value.trim()},x=>x.tasks.some(t=>t.id===task.id&&t.status==='completed'&&t.revision===task.revision+1)));};card.append(f);}tasks.append(card);}
  alerts.replaceChildren(text('h2','سجل التنبيهات'));if(!data.alerts.length)alerts.append(text('p','لا توجد تنبيهات مجهزة.'));for(const alert of data.alerts)alerts.append(text('p',`${alert.kind} • ${alert.scheduled_for} • ${alert.status}`));
 }
 reload.onclick=()=>d.run(async()=>{await load();d.status.textContent='تم استرجاع الخطط والمهام والتنبيهات.';});
 prepare.onclick=()=>d.run(()=>write('prepare_alerts',{},x=>Array.isArray(x.runs)&&x.runs.length>0));
 d.onDispose(()=>{data=null;pending=false;for(const x of [summary,editor,plans,tasks,alerts])x.replaceChildren();});
 d.run(load);
}
