import {createDialog,node,field} from '../components/dialog.js';

const input=(type='text',value='')=>{const x=node('input');x.type=type;x.value=value??'';return x;};
const text=v=>String(v??'').trim();
const money=v=>v==null?'غير متاح':Number(v).toFixed(3)+' د.ك';
const pct=v=>`${Number(v||0).toFixed(0)}%`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuwait',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function button(label,fn){const b=node('button',label);b.type='button';b.onclick=fn;return b;}
function section(title){const s=node('section');s.className='aq267-property-master-section';s.append(node('h3',title));return s;}
function metric(label,value){const a=node('article');a.className='aq267-property-master-metric';a.append(node('span',label),node('strong',value));return a;}
function select(rows,value=''){const x=node('select');let found=false;for(const [v,label]of rows){const o=node('option',label);o.value=v;x.append(o);if(String(v)===String(value))found=true;}if(value&&!found){const o=node('option',String(value));o.value=value;x.append(o);}x.value=value??'';return x;}
function check(label,value=false){const c=input('checkbox');c.checked=Boolean(value);return {c,el:field(label,c)};}
function list(target,rows,empty,render){if(!Array.isArray(rows)||!rows.length){target.append(node('p',empty));return;}for(const row of rows.slice(0,150))target.append(render(row));}
function urlLink(label,url){const a=node('a',label);a.href=url;a.target='_blank';a.rel='noopener';return a;}
const channelLabels={website:'Website',instagram:'Instagram',tiktok:'TikTok',snapchat:'Snapchat',x:'X',facebook:'Facebook',youtube:'YouTube',whatsapp:'WhatsApp',email:'Email',phone:'هاتف',other:'قناة أخرى'};
const unitStates=[['available','شاغرة'],['ready','جاهزة للتأجير'],['rented','مؤجرة'],['reserved','محجوزة'],['cleaning','تحتاج تنظيف'],['maintenance','تحتاج صيانة'],['renovation','تحتاج تجديد']];

export function openPropertyHub(propertyId){
 const d=createDialog('الملف الكامل للعقار');if(!d)return false;
 const rpc=(name,args)=>d.session.request(d.session.client.rpc(name,args));
 let file,header,access,channels;
 async function read(){
  const asOf=today();
  [file,header,access,channels]=await Promise.all([
   rpc('aqari_property_full_file',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_as_of:asOf}),
   rpc('aqari_property_dashboard_header',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_as_of:asOf}),
   rpc('aqari_workspace_access',{p_workspace_id:d.session.bound.workspace}),
   rpc('aqari_property_channel_settings',{p_workspace_id:d.session.bound.workspace,p_action:'context',p_data:{propertyId}})
  ]);d.session.check();
  if(file?.property?.id!==propertyId||header?.property_id!==propertyId||channels?.propertyId!==propertyId||access?.workspace_id!==d.session.bound.workspace||access?.user_id!==d.session.bound.user)throw Error('تعذر تأكيد نطاق ملف العقار.');return file;
 }
 const canWrite=()=>access?.permissions?.properties?.write===true;
 const isManager=()=>access?.role==='general_manager';
 function masterPayload(p,patch={}){return {...{name:p.name,address:p.address||'',description:p.description||'',locationUrl:p.locationUrl||'',propertyAutomaticRef:p.propertyAutomaticRef||'',type:p.type||'',status:p.status||'active',statedIncome:p.statedIncome??null,owners:Array.isArray(p.owners)?p.owners:[],email:p.email||'',phone:p.phone||'',whatsapp:p.whatsapp||'',assets:p.assets||{},tenantVisibility:p.tenantVisibility||{},tenantInfo:p.tenantInfo||{}},...patch};}
 async function editProperty(){
  if(!canWrite())throw Error('تعديل العقار غير متاح لصلاحية حسابك.');await read();const p=file.property;d.body.replaceChildren(node('h3','تعديل بيانات العقار والظهور للمستأجر'),button('رجوع',()=>d.run(render)));
  const f=node('form'),name=input('text',p.name),address=node('textarea'),description=node('textarea'),locationUrl=input('url',p.locationUrl),auto=input('text',p.propertyAutomaticRef),type=input('text',p.type),status=input('text',p.status),income=input('text',p.statedIncome??''),email=input('email',p.email),phone=input('tel',p.phone),wa=input('tel',p.whatsapp),reason=node('textarea');address.value=p.address||'';description.value=p.description||'';reason.value='تحديث ملف العقار';reason.required=true;reason.minLength=3;income.inputMode='decimal';
  for(const [label,c]of [['اسم العقار',name],['العنوان',address],['الوصف المختصر',description],['رابط الموقع',locationUrl],['الرقم الآلي للعقار',auto],['نوع العقار',type],['الحالة',status],['الدخل المعلن الاختياري',income],['البريد',email],['الهاتف',phone],['واتساب',wa]])f.append(field(label,c));
  const vis=section('ما يظهر للمستأجر'),visibility={};for(const [key,label,def]of [['name','اسم العقار',true],['logo','الشعار',false],['phone','الهاتف',false],['whatsapp','واتساب',false],['email','البريد',false],['location','الموقع',false],['instructions','التعليمات',false],['officeHours','أوقات الإدارة',false],['emergency','الطوارئ',false],['services','الخدمات',false]]){const c=check(label,p.tenantVisibility?.[key]??def);visibility[key]=c.c;vis.append(c.el);}const info=p.tenantInfo||{},instructions=node('textarea'),office=input('text',info.officeHours||''),emergency=input('text',info.emergency||''),services=node('textarea');instructions.value=info.instructions||'';services.value=typeof info.services==='string'?info.services:JSON.stringify(info.services||'');vis.append(field('تعليمات المستأجر',instructions),field('أوقات الإدارة',office),field('الطوارئ',emergency),field('الخدمات',services));f.append(vis,field('سبب التعديل',reason));const save=node('button','حفظ وإعادة القراءة');save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{const data=masterPayload(p,{name:text(name.value),address:text(address.value),description:text(description.value),locationUrl:text(locationUrl.value),propertyAutomaticRef:text(auto.value),type:text(type.value),status:text(status.value),statedIncome:text(income.value)||null,email:text(email.value).toLowerCase(),phone:text(phone.value),whatsapp:text(wa.value),tenantVisibility:Object.fromEntries(Object.entries(visibility).map(([k,c])=>[k,c.checked])),tenantInfo:{instructions:text(instructions.value),officeHours:text(office.value),emergency:text(emergency.value),services:text(services.value)}});const saved=await rpc('aqari_property_master_save',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_expected_revision:Number(p.revision||0),p_data:data,p_reason:text(reason.value)});if(saved?.property?.id!==propertyId)throw Error('لم تتأكد إعادة قراءة العقار.');await render();d.status.textContent='تم حفظ ملف العقار وإعادة قراءته.';});};
 }
 async function editUnit(unit){
  if(!canWrite())throw Error('تعديل الوحدة غير متاح لصلاحية حسابك.');await read();unit=file.units.find(x=>x.id===unit.id)||unit;d.body.replaceChildren(node('h3','تعديل الوحدة '+unit.unitNo),button('رجوع',()=>d.run(render)));
  const f=node('form'),unitNo=input('text',unit.unitNo),floor=input('text',unit.floor),type=input('text',unit.type),status=select(unitStates,unit.status||'available'),area=input('text',unit.areaSqm??''),rent=input('text',unit.statedRent??''),auto=input('text',unit.leasedAssetAutomaticRef||unit.automaticRef||''),serial=input('text',unit.internalSerial||''),parking=input('text',unit.parking||''),storage=input('text',unit.storage||''),services=input('text',Object.keys(unit.services||{}).filter(k=>unit.services[k]).join(', ')),reason=node('textarea');reason.value='تحديث بيانات الوحدة';reason.required=true;reason.minLength=3;area.inputMode=rent.inputMode='decimal';
  for(const [label,c]of [['رقم الوحدة',unitNo],['الدور',floor],['نوع الوحدة',type],['الحالة',status],['المساحة م²',area],['الإيجار المعلن',rent],['الرقم الآلي للعين المؤجرة',auto],['الرقم التسلسلي الداخلي',serial],['الموقف',parking],['المخزن',storage],['الخدمات — مفصولة بفاصلة',services]])f.append(field(label,c));f.append(field('سبب التعديل',reason));const save=node('button','حفظ الوحدة وإعادة القراءة');save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{const serviceKeys=text(services.value).split(/[,،]/).map(x=>x.trim().toLowerCase()).filter(Boolean);if(serviceKeys.some(k=>!/^[a-z][a-z0-9_.-]{0,49}$/.test(k)))throw Error('مفاتيح الخدمات تستخدم أحرفًا إنجليزية مثل elevator, water, internet.');const response=await rpc('aqari_unit_master_save',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_unit_id:unit.id,p_expected_revision:Number(unit.revision||0),p_data:{unitNo:text(unitNo.value),floor:text(floor.value),type:text(type.value),status:status.value,areaSqm:text(area.value)||null,statedRent:text(rent.value)||null,leasedAssetAutomaticRef:text(auto.value),internalSerial:text(serial.value),parking:text(parking.value),storage:text(storage.value),services:Object.fromEntries(serviceKeys.map(k=>[k,true]))},p_reason:text(reason.value)});if(response?.unit?.id!==unit.id)throw Error('لم تتأكد إعادة قراءة الوحدة.');await render();d.status.textContent='تم حفظ بيانات الوحدة وإعادة قراءتها.';});};
 }
 async function contract(unit){
  const ctx=await rpc('aqari_property_contract_context',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_unit_id:unit.id});d.session.check();if(ctx?.property?.id!==propertyId||ctx?.unit?.id!==unit.id)throw Error('تعذر تأكيد ربط العقار والوحدة.');d.close();const m=await import('./contract-foundation.js');return m.openContractFoundation({propertyId,unitId:unit.id,property:ctx.property.name,unit:ctx.unit.unitNo,floor:ctx.unit.floor,address:ctx.property.address,propertyRevision:ctx.binding?.propertyRevision,unitRevision:ctx.binding?.unitRevision});
 }
 async function manageChannels(existing=null){
  if(!isManager())throw Error('إدارة قنوات العقار متاحة للمدير العام فقط.');await read();d.body.replaceChildren(node('h3',existing?'تعديل قناة التواصل':'إضافة قناة تواصل'),button('رجوع',()=>d.run(render)));
  const f=node('form'),kind=select(Object.entries(channelLabels),existing?.kind||'whatsapp'),label=input('text',existing?.label||''),url=input('text',existing?.url||''),visible=check('يظهر للمستأجر',existing?.tenantVisible===true),status=select([['active','مفعل'],['hidden','مخفي'],['archived','مؤرشف']],existing?.status||'active'),sort=input('number',existing?.sortOrder??100),reference=input('text',existing?.managementReference||''),reason=node('textarea');reason.value=existing?'تحديث قناة العقار':'إضافة قناة عقار';reason.required=true;reason.minLength=3;sort.min='0';sort.max='10000';url.placeholder='https://... أو mailto:... أو tel:+...';f.append(field('نوع القناة',kind),field('المسمى',label),field('الرابط/الاتصال',url),visible.el,field('الحالة',status),field('الترتيب',sort),field('مرجع إداري داخلي',reference),field('سبب التعديل',reason));const save=node('button','حفظ القناة وإعادة القراءة');save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{let target=text(url.value);if(kind.value==='email'&&!target.startsWith('mailto:'))target='mailto:'+target;if(kind.value==='phone'&&!target.startsWith('tel:'))target='tel:'+target.replace(/[ ()-]/g,'');const response=await rpc('aqari_property_channel_settings',{p_workspace_id:d.session.bound.workspace,p_action:'save',p_data:{id:existing?.id||null,propertyId,revision:Number(existing?.revision||0),kind:kind.value,label:text(label.value),url:target,tenantVisible:visible.c.checked,status:status.value,sortOrder:Number(sort.value||100),managementReference:text(reference.value),reason:text(reason.value)}});if(!response?.record)throw Error('لم تتأكد إعادة قراءة قناة العقار.');await render();d.status.textContent='تم حفظ قناة العقار وإعادة قراءتها.';});};
 }
 async function createUnit(){d.close();const m=await import('./property-unit-create.js');return m.openPropertyUnitCreate(propertyId);}
 async function propertyControls(){d.close();const m=await import('./property-controls.js');return m.openPropertyControls(propertyId);}
 async function render(){
  await read();const p=file.property,h=header,f=h.financial?.available?h.financial:null,score=h.completeness?.score??0;d.body.replaceChildren();
  const head=section(p.name||'العقار'),grid=node('div');grid.className='aq267-property-master-metrics';for(const [label,value]of [['اكتمال الملف',pct(score)],['الوحدات',h.units?.total??0],['المؤجر',h.units?.occupied??0],['الشاغر',h.units?.vacant??0],['تحصيل الشهر',money(h.monthCollection)],['المتأخرات',money(h.arrears)],['صافي الشهر',money(f?.month?.net)],['صافي السنة',money(f?.year?.net)]])grid.append(metric(label,value));head.append(grid);if((h.completeness?.missing||[]).length)head.append(node('p','الناقص: '+h.completeness.missing.join('، ')));if(canWrite())head.append(button('تعديل بيانات العقار والظهور للمستأجر',editProperty),button('+ إضافة وحدة',createUnit));if(isManager())head.append(button('بنود المالك وخصائص العقار والفنيون والقوالب',propertyControls));d.body.append(head);
  const info=section('بيانات العقار');info.append(node('p','العنوان: '+(p.address||'—')),node('p','النوع: '+(p.type||'—')+' · الحالة: '+(p.status||'—')),node('p','الوصف: '+(p.description||'—')),node('p','الرقم الآلي للعقار: '+(p.propertyAutomaticRef||'—')));if(p.locationUrl)info.append(urlLink('فتح الموقع',p.locationUrl));d.body.append(info);
  const owner=section('الملاك');list(owner,p.owners,'لا توجد حصص ملاك محفوظة.',o=>node('p',`${o.role||'مالك'} · ${o.name||'—'} · ${(Number(o.bps||0)/100).toFixed(2)}% · ${o.phone||o.whatsapp||o.email||'—'}`));d.body.append(owner);
  const channelsBox=section('التواصل والسوشال ميديا');if(isManager())channelsBox.append(button('+ إضافة قناة',()=>d.run(()=>manageChannels(null))));list(channelsBox,channels.items,'لا توجد قنوات مضافة.',c=>{const a=node('article');a.append(urlLink(`${c.label||channelLabels[c.kind]||c.kind}${c.tenantVisible?' · يظهر للمستأجر':''}`,c.url));if(isManager())a.append(button('تعديل',()=>d.run(()=>manageChannels(c))));return a;});d.body.append(channelsBox);
  const units=section('الوحدات والأدوار');list(units,file.units,'لا توجد وحدات.',u=>{const a=node('article');a.className='aq267-property-unit-card';a.append(node('strong','الوحدة '+u.unitNo),node('p',`الدور ${u.floor||'—'} · ${u.type||'—'} · ${u.status||'—'} · المساحة ${u.areaSqm??'—'} م²`),node('p',`الإيجار ${money(u.statedRent)} · آلي العين ${u.leasedAssetAutomaticRef||'—'} · داخلي ${u.internalSerial||'—'}`),node('p',`الموقف ${u.parking||'—'} · المخزن ${u.storage||'—'} · الخدمات ${Object.keys(u.services||{}).filter(k=>u.services[k]).join('، ')||'—'}`));if(canWrite())a.append(button('تعديل الوحدة',()=>d.run(()=>editUnit(u))));if(access?.permissions?.contracts?.write===true)a.append(button('إبرام عقد من هذه الوحدة',()=>d.run(()=>contract(u))));return a;});d.body.append(units);
  const contracts=section('العقود');if(file.permissions?.contracts===false)contracts.append(node('p','ليس لديك صلاحية.'));else list(contracts,file.contracts,'لا توجد عقود مرتبطة.',x=>node('p',`${x.contractNo} · ${x.status} · ${money(x.monthlyRent)}`));d.body.append(contracts);
  const collections=section('التحصيل والمتأخرات');if(file.permissions?.collections===false)collections.append(node('p','ليس لديك صلاحية.'));else list(collections,file.collections,'لا توجد تحصيلات.',x=>node('p',`${x.paidAt} · ${x.reference} · ${money(x.amount)} · ${x.status}`));d.body.append(collections);
  const expenses=section('المصروفات');if(file.permissions?.finance===false)expenses.append(node('p','ليس لديك صلاحية.'));else list(expenses,file.expenses,'لا توجد مصروفات.',x=>node('p',`${x.date} · ${x.category} · ${x.payee} · ${money(x.amount)} · ${x.state}`));d.body.append(expenses);
  const docs=section('المستندات والصور والمخططات');if(file.permissions?.documents===false)docs.append(node('p','ليس لديك صلاحية.'));else list(docs,file.documents,'لا توجد مستندات مرتبطة.',x=>node('p',`${x.no} · ${x.type} · ${x.title} · ${x.status}`));d.body.append(docs);
  const ops=section('الصيانة والموظفون والتنبيهات');ops.append(node('p',`الصيانة المفتوحة/المحفوظة: ${file.summary?.maintenance??'غير متاح'} · الموظفون المرتبطون: ${file.summary?.employees??'غير متاح'}`));if(file.permissions?.notifications===false)ops.append(node('p','التنبيهات: ليس لديك صلاحية.'));else list(ops,file.notices,'لا توجد إعلانات/تنبيهات.',x=>node('p',`${x.kind} · ${x.title} · ${x.status}`));d.body.append(ops);
  const audit=section('سجل التعديلات');list(audit,file.audit,'لا توجد تعديلات مسجلة.',x=>node('p',`${x.at} · ${x.actor} · ${x.action} · ${x.reason}`));d.body.append(audit);
  d.status.textContent='الملف الكامل يقرأ البيانات الخادمة الفعلية. القيم المحجوبة بالصلاحية لا تظهر كأنها صفر.';
 }
 d.run(render);return true;
}
