import {openPropertyContract,openPropertySavedStatements} from '../components/property-record-navigation.js';
import {t as translateStatic,message as translateMessage} from '../components/locale.js';
import {createDialog,node,field} from '../components/dialog.js';

const input=(type='text',value='')=>{const x=node('input');x.type=type;x.value=value??'';return x;};
const text=v=>String(v??'').trim();
const money=v=>v==null?translateStatic('غير متاح'):Number(v).toFixed(3)+translateStatic(' د.ك');
const pct=v=>`${Number(v||0).toFixed(0)}%`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuwait',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function button(label,fn){const b=node('button',label);b.type='button';b.onclick=fn;return b;}
function section(title){const s=node('section');s.className='aq267-property-master-section';s.append(node('h3',title));return s;}
function metric(label,value){const a=node('article');a.className='aq267-property-master-metric';a.append(node('span',label),node('strong',value));return a;}
function select(rows,value=''){const x=node('select');let found=false;for(const [v,label]of rows){const o=node('option',label);o.value=v;x.append(o);if(String(v)===String(value))found=true;}if(value&&!found){const o=node('option',String(value));o.value=value;x.append(o);}x.value=value??'';return x;}
function check(label,value=false){const c=input('checkbox');c.checked=Boolean(value);return {c,el:field(label,c)};}
function list(target,rows,empty,render){if(!Array.isArray(rows)||!rows.length){target.append(node('p',empty));return;}for(const row of rows.slice(0,150))target.append(render(row));}
function urlLink(label,url){const a=node('a',label);a.href=url;a.target='_blank';a.rel='noopener';return a;}
const channelLabels={website:'Website',instagram:'Instagram',tiktok:'TikTok',snapchat:'Snapchat',x:'X',facebook:'Facebook',youtube:'YouTube',whatsapp:'WhatsApp',email:'Email',phone:translateStatic('هاتف'),other:translateStatic('قناة أخرى')};
const unitStates=[['available',translateStatic('شاغرة')],['ready',translateStatic('جاهزة للتأجير')],['rented',translateStatic('مؤجرة')],['reserved',translateStatic('محجوزة')],['cleaning',translateStatic('تحتاج تنظيف')],['maintenance',translateStatic('تحتاج صيانة')],['renovation',translateStatic('تحتاج تجديد')]];

export function openPropertyHub(propertyId){
 const d=createDialog(translateStatic('الملف الكامل للعقار'));if(!d)return false;
 const rpc=(name,args)=>d.session.request(d.session.client.rpc(name,args));
 let file,header,access,channels,presentationState;
 async function read(){
  const asOf=today();
  [file,header,access,channels,presentationState]=await Promise.all([
   rpc('aqari_property_full_file',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_as_of:asOf}),
   rpc('aqari_property_dashboard_header',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_as_of:asOf}),
   rpc('aqari_workspace_access',{p_workspace_id:d.session.bound.workspace}),
   rpc('aqari_property_channel_settings',{p_workspace_id:d.session.bound.workspace,p_action:'context',p_data:{propertyId}}),
   rpc('aqari_ui_presentation_settings',{p_workspace_id:d.session.bound.workspace,p_action:'context',p_data:{surface:'property_hub'}})
  ]);d.session.check();
  if(file?.property?.id!==propertyId||header?.property_id!==propertyId||channels?.propertyId!==propertyId||access?.workspace_id!==d.session.bound.workspace||access?.user_id!==d.session.bound.user||presentationState?.workspace_id!==d.session.bound.workspace||presentationState?.user_id!==d.session.bound.user)throw Error('تعذر تأكيد نطاق ملف العقار.');return file;
 }
 const canWrite=()=>access?.permissions?.properties?.write===true;
 const isManager=()=>access?.role==='general_manager';
 const presentation=key=>(presentationState?.items||[]).find(x=>x.key===key)||{key,labelAr:'',icon:'',sortOrder:100,visible:true};
 function mount(key,box,summaryName=''){const p=presentation(key),h=box.querySelector('h3');if(h){const label=p.labelAr||h.textContent;h.textContent=[p.icon,label,summaryName?`— ${summaryName}`:''].filter(Boolean).join(' ');}box.hidden=p.visible===false;box.style.order=String(Number(p.sortOrder||100));box.dataset.presentationKey=key;d.body.append(box);}
 function resetBody(){d.body.style.display='';d.body.style.flexDirection='';d.body.replaceChildren();}
 function masterPayload(p,patch={}){return {...{name:p.name,address:p.address||'',description:p.description||'',locationUrl:p.locationUrl||'',propertyAutomaticRef:p.propertyAutomaticRef||'',type:p.type||'',status:p.status||'active',statedIncome:p.statedIncome??null,owners:Array.isArray(p.owners)?p.owners:[],email:p.email||'',phone:p.phone||'',whatsapp:p.whatsapp||'',assets:p.assets||{},tenantVisibility:p.tenantVisibility||{},tenantInfo:p.tenantInfo||{}},...patch};}
 async function editProperty(){
  if(!canWrite())throw Error('تعديل العقار غير متاح لصلاحية حسابك.');await read();const p=file.property;resetBody();d.body.replaceChildren(node('h3',translateStatic('تعديل بيانات العقار والظهور للمستأجر')),button(translateStatic('رجوع'),()=>d.run(render)));
  const f=node('form'),name=input('text',p.name),address=node('textarea'),description=node('textarea'),locationUrl=input('url',p.locationUrl),auto=input('text',p.propertyAutomaticRef),type=input('text',p.type),status=input('text',p.status),income=input('text',p.statedIncome??''),email=input('email',p.email),phone=input('tel',p.phone),wa=input('tel',p.whatsapp),reason=node('textarea');address.value=p.address||'';description.value=p.description||'';reason.value='تحديث ملف العقار';reason.required=true;reason.minLength=3;income.inputMode='decimal';
  for(const [label,c]of [[translateStatic('اسم العقار'),name],[translateStatic('العنوان'),address],[translateStatic('الوصف المختصر'),description],[translateStatic('رابط الموقع'),locationUrl],[translateStatic('الرقم الآلي للعقار'),auto],[translateStatic('نوع العقار'),type],[translateStatic('الحالة'),status],[translateStatic('الدخل المعلن الاختياري'),income],[translateStatic('البريد'),email],[translateStatic('الهاتف'),phone],[translateStatic('واتساب'),wa]])f.append(field(label,c));
  const vis=section(translateStatic('ما يظهر للمستأجر')),visibility={};for(const [key,label,def]of [['name',translateStatic('اسم العقار'),true],['logo',translateStatic('الشعار'),false],['phone',translateStatic('الهاتف'),false],['whatsapp',translateStatic('واتساب'),false],['email',translateStatic('البريد'),false],['location',translateStatic('الموقع'),false],['instructions',translateStatic('التعليمات'),false],['officeHours',translateStatic('أوقات الإدارة'),false],['emergency',translateStatic('الطوارئ'),false],['services',translateStatic('الخدمات'),false]]){const c=check(label,p.tenantVisibility?.[key]??def);visibility[key]=c.c;vis.append(c.el);}const info=p.tenantInfo||{},instructions=node('textarea'),office=input('text',info.officeHours||''),emergency=input('text',info.emergency||''),services=node('textarea');instructions.value=info.instructions||'';services.value=typeof info.services==='string'?info.services:JSON.stringify(info.services||'');vis.append(field(translateStatic('تعليمات المستأجر'),instructions),field(translateStatic('أوقات الإدارة'),office),field(translateStatic('الطوارئ'),emergency),field(translateStatic('الخدمات'),services));f.append(vis,field(translateStatic('سبب التعديل'),reason));const save=node('button',translateStatic('حفظ وإعادة القراءة'));save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{const data=masterPayload(p,{name:text(name.value),address:text(address.value),description:text(description.value),locationUrl:text(locationUrl.value),propertyAutomaticRef:text(auto.value),type:text(type.value),status:text(status.value),statedIncome:text(income.value)||null,email:text(email.value).toLowerCase(),phone:text(phone.value),whatsapp:text(wa.value),tenantVisibility:Object.fromEntries(Object.entries(visibility).map(([k,c])=>[k,c.checked])),tenantInfo:{instructions:text(instructions.value),officeHours:text(office.value),emergency:text(emergency.value),services:text(services.value)}});const saved=await rpc('aqari_property_master_save',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_expected_revision:Number(p.revision||0),p_data:data,p_reason:text(reason.value)});if(saved?.property?.id!==propertyId)throw Error('لم تتأكد إعادة قراءة العقار.');await render();d.status.textContent=translateStatic('تم حفظ ملف العقار وإعادة قراءته.');});};
 }
 async function editUnit(unit){
  if(!canWrite())throw Error('تعديل الوحدة غير متاح لصلاحية حسابك.');await read();unit=file.units.find(x=>x.id===unit.id)||unit;resetBody();d.body.replaceChildren(node('h3',translateStatic('تعديل الوحدة ')+unit.unitNo),button(translateStatic('رجوع'),()=>d.run(render)));
  const f=node('form'),unitNo=input('text',unit.unitNo),floor=input('text',unit.floor),type=input('text',unit.type),status=select(unitStates,unit.status||'available'),area=input('text',unit.areaSqm??''),rent=input('text',unit.statedRent??''),auto=input('text',unit.leasedAssetAutomaticRef||unit.automaticRef||''),serial=input('text',unit.internalSerial||''),parking=input('text',unit.parking||''),storage=input('text',unit.storage||''),services=input('text',Object.keys(unit.services||{}).filter(k=>unit.services[k]).join(', ')),reason=node('textarea');reason.value='تحديث بيانات الوحدة';reason.required=true;reason.minLength=3;area.inputMode=rent.inputMode='decimal';
  for(const [label,c]of [[translateStatic('رقم الوحدة'),unitNo],[translateStatic('الدور'),floor],[translateStatic('نوع الوحدة'),type],[translateStatic('الحالة'),status],[translateStatic('المساحة م²'),area],[translateStatic('الإيجار المعلن'),rent],[translateStatic('الرقم الآلي للعين المؤجرة'),auto],[translateStatic('الرقم التسلسلي الداخلي'),serial],[translateStatic('الموقف'),parking],[translateStatic('المخزن'),storage],[translateStatic('الخدمات — مفصولة بفاصلة'),services]])f.append(field(label,c));f.append(field(translateStatic('سبب التعديل'),reason));const save=node('button',translateStatic('حفظ الوحدة وإعادة القراءة'));save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{const serviceKeys=text(services.value).split(/[,،]/).map(x=>x.trim().toLowerCase()).filter(Boolean);if(serviceKeys.some(k=>!/^[a-z][a-z0-9_.-]{0,49}$/.test(k)))throw Error('مفاتيح الخدمات تستخدم أحرفًا إنجليزية مثل elevator, water, internet.');const response=await rpc('aqari_unit_master_save',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_unit_id:unit.id,p_expected_revision:Number(unit.revision||0),p_data:{unitNo:text(unitNo.value),floor:text(floor.value),type:text(type.value),status:status.value,areaSqm:text(area.value)||null,statedRent:text(rent.value)||null,leasedAssetAutomaticRef:text(auto.value),internalSerial:text(serial.value),parking:text(parking.value),storage:text(storage.value),services:Object.fromEntries(serviceKeys.map(k=>[k,true]))},p_reason:text(reason.value)});if(response?.unit?.id!==unit.id)throw Error('لم تتأكد إعادة قراءة الوحدة.');await render();d.status.textContent=translateStatic('تم حفظ بيانات الوحدة وإعادة قراءتها.');});};
 }
 async function contract(unit){const ctx=await rpc('aqari_property_contract_context',{p_workspace_id:d.session.bound.workspace,p_property_id:propertyId,p_unit_id:unit.id});d.session.check();if(ctx?.property?.id!==propertyId||ctx?.unit?.id!==unit.id)throw Error('تعذر تأكيد ربط العقار والوحدة.');d.close();const m=await import('./contract-foundation.js');return m.openContractFoundation({propertyId,unitId:unit.id,property:ctx.property.name,unit:ctx.unit.unitNo,floor:ctx.unit.floor,address:ctx.property.address,propertyRevision:ctx.binding?.propertyRevision,unitRevision:ctx.binding?.unitRevision});}
 async function manageChannels(existing=null){
  if(!isManager())throw Error('إدارة قنوات العقار متاحة للمدير العام فقط.');await read();resetBody();d.body.replaceChildren(node('h3',existing?translateStatic('تعديل قناة التواصل'):translateStatic('إضافة قناة تواصل')),button(translateStatic('رجوع'),()=>d.run(render)));
  const f=node('form'),kind=select(Object.entries(channelLabels),existing?.kind||'whatsapp'),label=input('text',existing?.label||''),url=input('text',existing?.url||''),visible=check(translateStatic('يظهر للمستأجر'),existing?.tenantVisible===true),status=select([['active',translateStatic('مفعل')],['hidden',translateStatic('مخفي')],['archived',translateStatic('مؤرشف')]],existing?.status||'active'),sort=input('number',existing?.sortOrder??100),reference=input('text',existing?.managementReference||''),reason=node('textarea');reason.value=existing?'تحديث قناة العقار':'إضافة قناة عقار';reason.required=true;reason.minLength=3;sort.min='0';sort.max='10000';url.placeholder=translateStatic('https://... أو mailto:... أو tel:+...');f.append(field(translateStatic('نوع القناة'),kind),field(translateStatic('المسمى'),label),field(translateStatic('الرابط/الاتصال'),url),visible.el,field(translateStatic('الحالة'),status),field(translateStatic('الترتيب'),sort),field(translateStatic('مرجع إداري داخلي'),reference),field(translateStatic('سبب التعديل'),reason));const save=node('button',translateStatic('حفظ القناة وإعادة القراءة'));save.type='submit';f.append(save);d.body.append(f);
  f.onsubmit=e=>{e.preventDefault();d.run(async()=>{let target=text(url.value);if(kind.value==='email'&&!target.startsWith('mailto:'))target='mailto:'+target;if(kind.value==='phone'&&!target.startsWith('tel:'))target='tel:'+target.replace(/[ ()-]/g,'');const response=await rpc('aqari_property_channel_settings',{p_workspace_id:d.session.bound.workspace,p_action:'save',p_data:{id:existing?.id||null,propertyId,revision:Number(existing?.revision||0),kind:kind.value,label:text(label.value),url:target,tenantVisible:visible.c.checked,status:status.value,sortOrder:Number(sort.value||100),managementReference:text(reference.value),reason:text(reason.value)}});if(!response?.record)throw Error('لم تتأكد إعادة قراءة قناة العقار.');await render();d.status.textContent=translateStatic('تم حفظ قناة العقار وإعادة قراءتها.');});};
 }
 async function createUnit(){d.close();const m=await import('./property-unit-create.js');return m.openPropertyUnitCreate(propertyId);}
 async function propertyControls(){d.close();const m=await import('./property-controls.js');return m.openPropertyControls(propertyId);}
 async function adminSettings(){d.close();const m=await import('./property-admin-settings.js');return m.openPropertyAdminSettings(propertyId);}
 async function financeCenter(){d.close();const m=await import('./property-cost-allocation.js');return m.openPropertyCostAllocation({propertyId});}
 async function ownerStatement(){d.close();const m=await import('./property-owner-statement.js');return m.openPropertyOwnerStatement(propertyId);}
 async function render(){
  await read();const p=file.property,h=header,f=h.financial?.available?h.financial:null,score=h.completeness?.score??0;resetBody();d.body.style.display='flex';d.body.style.flexDirection='column';
  const head=section(translateStatic('ملخص العقار')),grid=node('div');grid.className='aq267-property-master-metrics';for(const [label,value]of [[translateStatic('اكتمال الملف'),pct(score)],[translateStatic('الوحدات'),h.units?.total??0],[translateStatic('المؤجر'),h.units?.occupied??0],[translateStatic('الشاغر'),h.units?.vacant??0],[translateStatic('تحصيل الشهر'),money(h.monthCollection)],[translateStatic('المتأخرات'),money(h.arrears)],[translateStatic('صافي الشهر'),money(f?.month?.net)],[translateStatic('صافي السنة'),money(f?.year?.net)]])grid.append(metric(label,value));head.append(grid);if((h.completeness?.missing||[]).length)head.append(node('p',translateStatic('الناقص: ')+h.completeness.missing.join('، ')));if(canWrite())head.append(button(translateStatic('تعديل بيانات العقار والظهور للمستأجر'),editProperty),button(translateStatic('+ إضافة وحدة'),createUnit));if(isManager())head.append(button(translateStatic('بنود المالك وخصائص العقار والفنيون والقوالب'),propertyControls),button(translateStatic('تخصيص المسميات والأيقونات والحقول'),adminSettings));if(file.permissions?.finance!==false)head.append(button(translateStatic('مركز تكلفة العقار والتوزيع'),financeCenter),button(translateStatic('كشف الملاك المحسوب'),ownerStatement));mount('summary',head,p.name);
  const info=section(translateStatic('بيانات العقار'));info.append(node('p',translateStatic('العنوان: ')+(p.address||'—')),node('p',translateStatic('النوع: ')+(p.type||'—')+translateStatic(' · الحالة: ')+(p.status||'—')),node('p',translateStatic('الوصف: ')+(p.description||'—')),node('p',translateStatic('الرقم الآلي للعقار: ')+(p.propertyAutomaticRef||'—')));if(p.locationUrl)info.append(urlLink(translateStatic('فتح الموقع'),p.locationUrl));mount('property',info);
  const owner=section(translateStatic('الملاك'));list(owner,p.owners,translateStatic('لا توجد حصص ملاك محفوظة.'),o=>node('p',`${o.role||translateStatic('مالك')} · ${o.name||'—'} · ${(Number(o.bps||0)/100).toFixed(2)}% · ${o.phone||o.whatsapp||o.email||'—'}`));mount('owners',owner);
  const channelsBox=section(translateStatic('التواصل والسوشال ميديا'));if(isManager())channelsBox.append(button(translateStatic('+ إضافة قناة'),()=>d.run(()=>manageChannels(null))));list(channelsBox,channels.items,translateStatic('لا توجد قنوات مضافة.'),c=>{const a=node('article');a.append(urlLink(`${c.label||channelLabels[c.kind]||c.kind}${c.tenantVisible?translateStatic(' · يظهر للمستأجر'):''}`,c.url));if(isManager())a.append(button(translateStatic('تعديل'),()=>d.run(()=>manageChannels(c))));return a;});mount('channels',channelsBox);
  const units=section(translateStatic('الوحدات والأدوار'));list(units,file.units,translateStatic('لا توجد وحدات.'),u=>{const a=node('article');a.className='aq267-property-unit-card';a.append(node('strong',translateStatic('الوحدة ')+u.unitNo),node('p',translateMessage("الدور {v0} · {v1} · {v2} · المساحة {v3} م²",{v0:(u.floor||'—'),v1:(u.type||'—'),v2:(u.status||'—'),v3:(u.areaSqm??'—')})),node('p',translateMessage("الإيجار {v0} · آلي العين {v1} · داخلي {v2}",{v0:(money(u.statedRent)),v1:(u.leasedAssetAutomaticRef||'—'),v2:(u.internalSerial||'—')})),node('p',translateMessage("الموقف {v0} · المخزن {v1} · الخدمات {v2}",{v0:(u.parking||'—'),v1:(u.storage||'—'),v2:(Object.keys(u.services||{}).filter(k=>u.services[k]).join('، ')||'—')})));if(canWrite())a.append(button(translateStatic('تعديل الوحدة'),()=>d.run(()=>editUnit(u))));if(access?.permissions?.contracts?.write===true)a.append(button(translateStatic('إبرام عقد من هذه الوحدة'),()=>d.run(()=>contract(u))));return a;});mount('units',units);
  const contracts=section(translateStatic('العقود'));if(file.permissions?.contracts===false)contracts.append(node('p',translateStatic('ليس لديك صلاحية.')));else list(contracts,file.contracts,translateStatic('لا توجد عقود مرتبطة.'),x=>{const row=node('article');row.append(node('p',`${x.contractNo} · ${x.status} · ${money(x.monthlyRent)}`),button(translateStatic('عرض العقد'),()=>d.run(()=>openPropertyContract(d,propertyId,x))));return row;});mount('contracts',contracts);
  const collections=section(translateStatic('التحصيل والمتأخرات'));if(file.permissions?.collections===false)collections.append(node('p',translateStatic('ليس لديك صلاحية.')));else list(collections,file.collections,translateStatic('لا توجد تحصيلات.'),x=>node('p',`${x.paidAt} · ${x.reference} · ${money(x.amount)} · ${x.status}`));if(f)collections.prepend(node('p',translateMessage("متوقع الشهر {v0} · فعلي {v1} · الفرق {v2} · المتأخر {v3}",{v0:(money(f.month?.expectedIncome)),v1:(money(f.month?.income)),v2:(money(f.month?.collectionVariance)),v3:(money(f.arrears))})));if(file.permissions?.collections!==false)collections.append(button(translateStatic('عرض آخر كشف محفوظ'),()=>d.run(()=>openPropertySavedStatements(d,p.name))));mount('collections',collections);
  const expenses=section(translateStatic('المصروفات'));if(file.permissions?.finance===false)expenses.append(node('p',translateStatic('ليس لديك صلاحية.')));else list(expenses,file.expenses,translateStatic('لا توجد مصروفات.'),x=>node('p',`${x.date} · ${x.category} · ${x.payee} · ${money(x.amount)} · ${x.state}`));if(f)expenses.prepend(node('p',translateMessage("مصروف الشهر الفعلي {v0} · الأثر التحليلي الشهري {v1} · صافي تحليلي {v2}",{v0:(money(f.month?.expenses)),v1:(money(f.month?.analyticalExpenses)),v2:(money(f.month?.analyticalNet))})));mount('expenses',expenses);
  const docs=section(translateStatic('المستندات والصور والمخططات'));if(file.permissions?.documents===false)docs.append(node('p',translateStatic('ليس لديك صلاحية.')));else list(docs,file.documents,translateStatic('لا توجد مستندات مرتبطة.'),x=>node('p',`${x.no} · ${x.type} · ${x.title} · ${x.status}`));mount('documents',docs);
  const ops=section(translateStatic('الصيانة والموظفون والتنبيهات'));ops.append(node('p',translateMessage("الصيانة المفتوحة/المحفوظة: {v0} · الموظفون المرتبطون: {v1}",{v0:(file.summary?.maintenance??translateStatic('غير متاح')),v1:(file.summary?.employees??translateStatic('غير متاح'))})));if(file.permissions?.notifications===false)ops.append(node('p',translateStatic('التنبيهات: ليس لديك صلاحية.')));else list(ops,file.notices,translateStatic('لا توجد إعلانات/تنبيهات.'),x=>node('p',`${x.kind} · ${x.title} · ${x.status}`));mount('operations',ops);
  const audit=section(translateStatic('سجل التعديلات'));list(audit,file.audit,translateStatic('لا توجد تعديلات مسجلة.'),x=>node('p',`${x.at} · ${x.actor} · ${x.action} · ${x.reason}`));mount('audit',audit);
  d.status.textContent=translateStatic('الملف الكامل يقرأ البيانات الخادمة الفعلية. تخصيص المسميات والأيقونات والترتيب هو عرض فقط ولا يغير المفاتيح التقنية.');
 }
 d.run(render);return true;
}

