export const PROFILE_FIELDS=[['name_ar','الاسم بالعربي / Arabic name'],['name_en','الاسم بالإنجليزي / English name'],['civil_id','الرقم المدني / Civil ID'],['passport','رقم الجواز / Passport'],['nationality','الجنسية / Nationality'],['phone','الهاتف / Phone'],['job_ar','المسمى الوظيفي بالعربي / Arabic job title'],['job_en','المسمى الوظيفي بالإنجليزي / English job title'],['work_location','موقع العمل / Work location']];
export const PERMISSIONS={read:'عرض / View',add:'إضافة / Add',edit:'تعديل وإصدار وصرف / Edit, issue and record payment',approve_admin:'اعتماد المدير الإداري / Administrative manager',approve_chairman:'اعتماد رئيس مجلس الإدارة / Chairman'};
export const STATES={draft:'مسودة / Draft',issued:'صادر / Issued',paid:'مصروف / Paid'};
export const METHODS={cash:'نقدي / Cash',cheque:'شيك / Cheque',transfer:'تحويل / Transfer'};
export function money(value){const text=String(value??'').trim().replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace('٫','.');if(!/^\d{1,9}(\.\d{1,3})?$/.test(text))throw Error('أدخل مبلغاً صحيحاً بثلاث منازل عشرية كحد أقصى.');return text;}
export function fils(value){const [a,b='']=money(value).split('.');return Number(a)*1000+Number(b.padEnd(3,'0'));}
export function netPay(p){const n=fils(p.basic)+fils(p.allowances)+fils(p.overtime)-fils(p.deductions)-fils(p.advance_repayment);if(n<0)throw Error('الخصومات وقسط السلفة يتجاوزان إجمالي المستحق.');return (n/1000).toFixed(3);}
export function kuwaitTime(value){return value?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuwait',dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';}
export function currentMonth(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuwait',year:'numeric',month:'2-digit'}).formatToParts(new Date());return p.find(x=>x.type==='year').value+'-'+p.find(x=>x.type==='month').value;}
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function voucherHTML(p){
 const person=p.snapshot||{},rows=[...PROFILE_FIELDS.map(([key,label])=>[label,person[key]]),['تاريخ التعيين / Hire date',person.hired_on],['العقارات / Properties',(person.properties||[]).join('، ')],['الشهر / Month',p.month.slice(0,7)],['رقم السند / Voucher number',p.id],['الحالة / Status',STATES[p.state]],['الراتب الأساسي / Basic',p.basic],['البدلات / Allowances',p.allowances],['الإضافي / Overtime',p.overtime],['الخصومات / Deductions',p.deductions],['قسط السلفة / Advance repayment',p.advance_repayment],['صافي المستحق — د.ك / Net payable — KWD',netPay(p)],['طريقة الصرف / Method',METHODS[p.method]],['المرجع / Reference',p.reference||'—'],['تاريخ إثبات الصرف / Payment recorded',kuwaitTime(p.paid_at)],['ملاحظات / Notes',p.notes||'—']];
 const approval=(title,a)=>`<section><h3>${esc(title)}</h3><p>${a?esc(a.name)+' · '+esc(kuwaitTime(a.at)):'بانتظار الاعتماد / Pending approval'}</p><p>التوقيع / Signature: ____________________</p></section>`;
 return `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>سند راتب / Salary voucher ${esc(p.month.slice(0,7))}</title><style>@page{size:A4;margin:14mm}body{font:14px/1.65 system-ui,sans-serif;color:#172b37;max-width:800px;margin:24px auto;padding:12px}h1{font-size:24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbc8cd;padding:5px;text-align:start;overflow-wrap:anywhere}th{width:50%;background:#f1f5f6}td{unicode-bidi:plaintext}section{break-inside:avoid;border:1px solid #bbc8cd;padding:12px;margin-top:12px}h3{margin:0}small{display:block} @media print{body{margin:0;padding:0}a{display:none}}</style><h1>AQARI · سند راتب / Salary voucher</h1><p>نسخة ${p.state==='draft'?'مسودة للمراجعة / Draft for review':'صادرة / Issued'} — ${esc(p.month.slice(0,7))}</p><table>${rows.map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</table><section><h3>استلام الموظف / Employee acknowledgement</h3><p>أقر باستلام صافي المستحق الموضح أعلاه. / I acknowledge receiving the net amount stated above.</p><p>التاريخ / Date: ____________________</p><p>توقيع الموظف / Employee signature: ____________________</p><p>بصمة الموظف / Employee fingerprint:</p><div style="height:75px;border:1px dashed #888;width:150px"></div></section>${approval('اعتماد المدير الإداري / Administrative manager',p.admin_approval)}${approval('اعتماد رئيس مجلس الإدارة / Chairman',p.chairman_approval)}<section><h3>ختم الإدارة / Administration stamp</h3><div style="height:70px"></div></section><small>تُحفظ النسخة الموقعة في ملف الموظف حسب السنة والشهر. / Archive the signed copy in the employee file by year and month.</small></html>`;
}
export async function validateDocument(file){
 if(!file||file.size<1||file.size>10485760||!['application/pdf','image/jpeg','image/png'].includes(file.type))throw Error('اختر PDF أو صورة PNG/JPEG بحد أقصى 10 ميجابايت.');
 const b=new Uint8Array(await file.slice(0,8).arrayBuffer());const valid=file.type==='application/pdf'?String.fromCharCode(...b.slice(0,5))==='%PDF-':file.type==='image/png'?b.join(',')==='137,80,78,71,13,10,26,10':b[0]===255&&b[1]===216&&b[2]===255;
 if(!valid)throw Error('محتوى الملف لا يطابق نوعه.');return file;
}
