const test=require('node:test'),assert=require('node:assert/strict');
const api=import('../lib/v267/migration-preflight.js');
const config=import('../scripts/configure-v267-staging.mjs');
test('staging generator also rejects the database currently shared with the live domain',async()=>{
 const {stageConfiguration}=await config;
 for(const slash of ['','/'])assert.throws(()=>stageConfiguration({url:'https://djkpkkgoibruaezdrchb.supabase.co'+slash,publishableKey:'sb_publishable_TEST'},"export const PRODUCT_VERSION = 'V267';"),/ISOLATED/);
});
function fixture(){return {properties:[['عقار اختبار']],tenantProfilesV267:[{id:'t1',nameAr:'شخص اختبار',civilId:'123456789012',phone:'55550000'}],contractsV202:[{id:'c1',contract_no:'L1',property:'عقار اختبار',unit:'1',tenant:'شخص اختبار',tenantId:'t1',rent:100,start_date:'2026-01-01',end_date:'2026-12-31',status:'signed',source:'v267-cloud'}],tenantDirectoryV202:[{contractNo:'L1',property:'عقار اختبار',unit:'1',tenant:'شخص اختبار',civilId:'123456789012',phone:'55550000',verified:true}],rentLedgerV202:[],collections:[]}}
test('preflight is read-only, deterministic and excludes personal fields from report',async()=>{const {migrationPreflight}=await api;const f=fixture(),before=JSON.stringify(f),r=migrationPreflight(f);assert.equal(JSON.stringify(f),before);assert.equal(r.canMigrate,true);assert.deepEqual(r,migrationPreflight(f));assert.ok(!JSON.stringify(r).includes('123456789012'));});
test('protected signed import cannot silently become an operational lease',async()=>{const {migrationPreflight}=await api;const f=fixture();f.contractsV202[0].source='protected-rent-import-v202';f.tenantDirectoryV202[0].verified=false;const r=migrationPreflight(f);assert.equal(r.canMigrate,false);assert.equal(r.issueCounts.IMPORTED_REQUIRES_REVIEW,1);assert.equal(r.issueCounts.IDENTITY_REQUIRES_REVIEW,1);});
test('missing date and profile each block migration',async()=>{const {migrationPreflight}=await api;const f=fixture();delete f.contractsV202[0].end_date;f.tenantProfilesV267=[];const r=migrationPreflight(f);assert.equal(r.issueCounts.INVALID_DATES,1);assert.equal(r.issueCounts.VERIFIED_PROFILE_REQUIRED,1);});
test('Arabic apartment digits collide and overlapping dates block both leases',async()=>{const {migrationPreflight}=await api;const f=fixture();f.contractsV202.push({...f.contractsV202[0],id:'c2',contract_no:'L2',unit:'١'});assert.equal(migrationPreflight(f).issueCounts.UNIT_DATE_OVERLAP,2);});
test('same-unit non-overlapping lease is not an overlap',async()=>{const {migrationPreflight}=await api;const f=fixture();f.contractsV202.push({...f.contractsV202[0],id:'c2',contract_no:'L2',start_date:'2027-01-01',end_date:'2027-12-31'});assert.equal(migrationPreflight(f).issueCounts.UNIT_DATE_OVERLAP,undefined);});
test('historical payment with missing actual date cannot be reported as a fresh payment',async()=>{const {migrationPreflight}=await api;const f=fixture();f.rentLedgerV202.push({paid:100,due:100,period:'2026-09',contractId:'c1',contractNo:'L1',property:'عقار اختبار',unit:'1',tenant:'شخص اختبار',receiptNo:'R1',status:'paid',source:'import'});const r=migrationPreflight(f);assert.equal(r.issueCounts.MISSING_PAYMENT_DATE,1);assert.equal(r.issueCounts.HISTORICAL_RECONCILIATION_REQUIRED,1);});
test('unmatched collection cannot disappear in migration',async()=>{const {migrationPreflight}=await api;const f=fixture();f.collections=[['R1','شخص اختبار',100]];assert.equal(migrationPreflight(f).issueCounts.UNRECONCILED_COLLECTION,1);});
test('cloud envelope has the same counts',async()=>{const {migrationPreflight}=await api;const f=fixture();assert.deepEqual(migrationPreflight({format:'aqari-cloud-state-v1',snapshot:{values:{aqari_v30:f}}}).counts,migrationPreflight(f).counts);});
test('staging generator rejects production project and secret keys',async()=>{const {stageConfiguration}=await config;assert.throws(()=>stageConfiguration({url:'https://qtavnufzbkdfeauyukot.supabase.co',publishableKey:'sb_publishable_TEST'},"export const PRODUCT_VERSION = 'V267';"),/ISOLATED/);assert.throws(()=>stageConfiguration({url:'https://aaaaaaaaaaaaaaaaaaaa.supabase.co',publishableKey:'sb_secret_TEST'},"export const PRODUCT_VERSION = 'V267';"),/PUBLISHABLE/);});
test('browser and server point to identical isolated project and own session storage',async()=>{const {stageConfiguration}=await config;const r=stageConfiguration({url:'https://aaaaaaaaaaaaaaaaaaaa.supabase.co',publishableKey:'sb_publishable_TEST'},"export const PRODUCT_VERSION = 'V267';\nexport const RELEASE_STAGE = 'production';\nexport const C={url: 'OLD',publishableKey: 'OLD'};");assert.match(r.server,/RELEASE_STAGE = 'preview'/);assert.match(r.server,/aaaaaaaaaaaaaaaaaaaa/);assert.match(r.browser,/sb-aaaaaaaaaaaaaaaaaaaa-auth-token/);assert.doesNotMatch(r.server,/qtavnuf/);});

test('shared phones warn without blocking distinct identities or exposing personal values',async()=>{
 const {migrationPreflight}=await api,f=fixture();f.tenantProfilesV267.push({id:'t2',nameAr:'شخص آخر',civilId:'223456789012',phone:'٥٥٥٥-٠٠٠٠'});
 const before=JSON.stringify(f),r=migrationPreflight(f);assert.equal(r.canMigrate,true);assert.equal(r.warningCounts.SHARED_PHONE,2);assert.equal(r.issueCounts.DUPLICATE_IDENTITY,undefined);assert.equal(JSON.stringify(f),before);assert.doesNotMatch(JSON.stringify(r),/55550000|223456789012|شخص آخر/);
 f.tenantProfilesV267[1].civilId=f.tenantProfilesV267[0].civilId;const blocked=migrationPreflight(f);assert.equal(blocked.canMigrate,false);assert.equal(blocked.issueCounts.DUPLICATE_IDENTITY,2);
 f.tenantProfilesV267.forEach(p=>p.phone='');assert.deepEqual(migrationPreflight(f).warnings,[]);
});
