import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const base=readFileSync(new URL('../staging-database/sql/property-owner-controls.sql',import.meta.url),'utf8');
const settingsFix=readFileSync(new URL('../staging-database/sql/property-owner-controls-feature-settings-fix.sql',import.meta.url),'utf8');
const typeFix=readFileSync(new URL('../staging-database/sql/property-owner-controls-property-type-fix.sql',import.meta.url),'utf8');
assert.match(base,/set settings=settings,revision=next_rev/,'base anchor changed; reconcile the follow-up fix');
assert.match(settingsFix,/feature_settings jsonb/);
assert.match(settingsFix,/set settings=feature_settings,revision=next_rev/);
assert.match(settingsFix,/select s\.settings into feature_settings/);
assert.match(settingsFix,/PROPERTY_CONTROL_FEATURE_SETTINGS_PATCH_INCOMPLETE/);
assert.ok(settingsFix.indexOf('pg_get_functiondef')<settingsFix.indexOf('execute s'));
assert.match(base,/m\.type/,'base type anchor changed; reconcile the follow-up fix');
assert.match(typeFix,/m\.property_type/);
assert.match(typeFix,/PROPERTY_TYPE_FIX_INCOMPLETE/);
assert.match(typeFix,/pg_get_functiondef\('public\.aqari_property_controls/);
assert.match(typeFix,/pg_get_functiondef\('private\.aqari_property_template_scope_guard/);
console.log('V267 property controls SQL fixes: PASS');
