import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const sql=readFileSync(new URL('../staging-database/sql/property-batch-a2-core.sql',import.meta.url),'utf8');
const ownerFix=readFileSync(new URL('../staging-database/sql/property-batch-a2-owner-normalization.sql',import.meta.url),'utf8');
const hub=readFileSync(new URL('../src/v267/pages/property-hub.js',import.meta.url),'utf8');
const onboarding=readFileSync(new URL('../src/v267/pages/property-onboarding.js',import.meta.url),'utf8');
const upload=readFileSync(new URL('../src/v267/components/original-document-upload.js',import.meta.url),'utf8');
const experience=readFileSync(new URL('../src/v267/components/property-experience.js',import.meta.url),'utf8');

assert.match(sql,/add column if not exists description text/);
assert.match(sql,/add column if not exists property_automatic_ref text/);
assert.match(sql,/add column if not exists area_sqm numeric/);
assert.match(sql,/add column if not exists internal_serial text/);
assert.match(sql,/leasedAssetAutomaticRef/);
assert.match(sql,/aqari_property_channel_settings/);
assert.match(sql,/tiktok/);assert.match(sql,/snapchat/);assert.match(sql,/mailto:/);assert.match(sql,/tel:/);
assert.match(sql,/PROPERTY_CHANNEL_DELETE_FORBIDDEN/);
assert.match(sql,/aqari_property_completeness/);
assert.match(sql,/aqari_property_dashboard_header/);
assert.match(sql,/aqari_property_tenant_profile/);
assert.match(sql,/PROPERTY_AUTOMATIC_REF_ALREADY_EXISTS/);
assert.match(sql,/LEASED_ASSET_AUTOMATIC_REF_ALREADY_EXISTS/);
assert.match(sql,/UNIT_INTERNAL_SERIAL_ALREADY_EXISTS/);
assert.match(sql,/property_main_photo/);assert.match(sql,/property_license/);assert.match(sql,/property_certificate/);assert.match(sql,/property_insurance/);
assert.match(ownerFix,/jsonb_agg\(x\.value-''share''\)/);
assert.match(onboarding,/الصورة الرئيسية/);assert.match(onboarding,/الرخص/);assert.match(onboarding,/التأمينات/);assert.match(onboarding,/tenantVisibility/);assert.match(onboarding,/propertyAutomaticRef/);
assert.match(upload,/property_main_photo/);assert.match(upload,/property_license/);assert.match(upload,/property_certificate/);assert.match(upload,/property_insurance/);
assert.match(hub,/اكتمال الملف/);assert.match(hub,/المؤجر/);assert.match(hub,/الشاغر/);assert.match(hub,/إبرام عقد من هذه الوحدة/);assert.match(hub,/leasedAssetAutomaticRef/);assert.match(hub,/التواصل والسوشال ميديا/);
assert.match(experience,/import\('\.\.\/pages\/property-hub\.js'\)/);
console.log('V267 property Batch A2 contract: PASS');
