import test from 'node:test';import assert from 'node:assert/strict';
import {openFinancialArchive,archiveCsvCell} from '../src/v267/pages/financial-archive.js';
async function fixture({wrongMonth=false}={}){
 const original={window:globalThis.window,document:globalThis.document};const downloads=[],calls=[];
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.attributes={};this.value='';this.disabled=false;}get isConnected(){return this.parent?this.parent.isConnected:this.connected===true;}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}replaceChildren(...nodes){this.children=[];this.append(...nodes);}querySelectorAll(){return this.children.flatMap(n=>[n,...n.querySelectorAll()]);}setAttribute(k,v){this.attributes[k]=v;}addEventListener(){}showModal(){}close(){}remove(){this.parent.children=this.parent.children.filter(x=>x!==this);}click(){downloads.push(this.download);}}
 const body=new Element('body');body.connected=true;
 const client={rpc(name,args){assert.equal(name,'aqari_financial_archive');calls.push(args);return {abortSignal:async()=>({data:{month:wrongMonth?'1900-01':args.p_month,properties:[{id:'p1',name:'عقار الاختبار'}],period:{closed_at:'2026-02-01',snapshot:{rent_payments:100}},summary:{rent_payments:999},history:[],entries:[{id:'r1',stream:'rent',on_date:'2026-01-01',property_id:'p1',amount:'100.000',direction:'received',status:'cancelled',reference:'R-1',description:'إلغاء موثق'},{id:'b1',stream:'opening',on_date:'2026-01-01',property_id:'p1',amount:'20.000',direction:'credit',status:'recorded',reference:'B-1',description:'افتتاحي'}]}})};}};
 globalThis.document={body,activeElement:null,createElement:t=>new Element(t),documentElement:{classList:{contains:()=>true}}};
 globalThis.window={AQARI_PUBLIC_CONFIG:{supabaseUrl:'https://ofgmcsmxmdswlovsckqs.supabase.co'},AQARI_DATA_GATE:{scope:{userId:'u',workspaceId:'w'}},AQARI_SUPABASE:{getClient:async()=>client,context:{user:{id:'u'},workspace:{id:'w'},membership:{user_id:'u',workspace_id:'w',is_active:true,role:'general_manager'}}},addEventListener(){},removeEventListener(){}};
 openFinancialArchive();await new Promise(setImmediate);const dialog=body.children[0],elements=()=>dialog.querySelectorAll();
 return {downloads,calls,elements,button:label=>elements().find(x=>x.tagName==='button'&&x.textContent===label),status:()=>elements().find(x=>x.attributes.role==='status').textContent,cleanup(){dialog.children[0].onclick();Object.assign(globalThis,original);}};
}
test('archive displays saved close totals, cancelled receipts and separate opening entries',async()=>{const f=await fixture();try{const texts=f.elements().map(x=>x.textContent);assert.ok(texts.includes('التحصيل في لقطة الإقفال: 100'));assert.ok(texts.includes('ملغى'));assert.ok(texts.includes('رصيد افتتاحي'));assert.equal(f.elements().filter(x=>x.tagName==='tbody')[0].children.length,2);assert.ok(!texts.includes('التحصيل في لقطة الإقفال: 999'));}finally{f.cleanup();}});
test('changing month input cannot relabel already-loaded archive exports',async()=>{const f=await fixture();try{const loaded=f.calls[0].p_month;f.elements().find(x=>x.tagName==='input').value='1900-01';f.button('تصدير السجل للتدقيق').onclick();f.button('تنزيل جدول CSV').onclick();assert.deepEqual(f.downloads,[`AQARI-finance-${loaded}.json`,`AQARI-finance-${loaded}.csv`]);}finally{f.cleanup();}});
test('wrong-month RPC response cannot populate archive or offer download',async()=>{const f=await fixture({wrongMonth:true});try{assert.equal(f.button('تنزيل جدول CSV'),undefined);assert.match(f.status(),/تعذر تأكيد شهر الأرشيف/);}finally{f.cleanup();}});
test('CSV escaping protects financial references from spreadsheet formula execution',()=>{for(const value of ['=SUM(A1)','+cmd','-1+2','@SUM(A1)','\t=1','\r\n=1'])assert.match(archiveCsvCell(value),/^"'/);assert.equal(archiveCsvCell('مرجع "١"'),'"مرجع ""١"""');assert.equal(archiveCsvCell('100.125'),'"100.125"');});
