-- Generated by scripts/build-hosted-archive-tests.mjs from the matching local suite.
-- Independently verified test branch only. No owner workspace or password credentials.
-- Positive synthetic MFA fixture: include a current supported second-factor event.
-- Negative AAL1/expired-MFA cases and all production guards remain unchanged.
-- Synthetic records only; all writes roll back. Must run after source/access/template upgrades.
begin;
set local statement_timeout='30s';
set local lock_timeout='3s';
insert into public.aqari_workspaces(id,slug,name) values('7f6b0000-0000-4000-8000-000000000098','aqari-v267-archive-acceptance-20260912','اختبار أرشفة مؤقت — يتراجع بالكامل');
insert into public.aqari_app_state(workspace_id,payload) values('7f6b0000-0000-4000-8000-000000000098','{}');
insert into private.aqari_allowed_users(email,display_name,role,workspace_slug) values
 ('official-source-manager@example.invalid','مدير نماذج اختبار','general_manager','aqari-v267-archive-acceptance-20260912'),
 ('official-source-accountant@example.invalid','محاسب نماذج اختبار','accountant','aqari-v267-archive-acceptance-20260912');
insert into auth.users(id,email,email_confirmed_at) values
 ('7f680000-0000-4000-8000-000000000001','official-source-manager@example.invalid',now()),
 ('7f680000-0000-4000-8000-000000000002','official-source-accountant@example.invalid',now());
select set_config('aqari.test.official_source.workspace',(select workspace_id::text from public.aqari_memberships where user_id='7f680000-0000-4000-8000-000000000001' and is_active),true);
select set_config('request.jwt.claim.sub','7f680000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from statement_timestamp()))::bigint)))::text,true);
insert into public.aqari_workspaces(id,slug,name) values('7f680000-0000-4000-8000-000000000099','official-source-foreign-fixture','Foreign isolated fixture');
insert into public.aqari_app_state(workspace_id,payload) values('7f680000-0000-4000-8000-000000000099','{}');
do $$declare n integer;w uuid;p uuid;t uuid;u uuid;l uuid;begin
 for n in 1..3 loop
  w:=case n when 3 then '7f680000-0000-4000-8000-000000000099'::uuid else current_setting('aqari.test.official_source.workspace')::uuid end;
  p:=('7f680000-0000-4000-8000-00000000010'||n)::uuid;t:=('7f680000-0000-4000-8000-00000000020'||n)::uuid;
  u:=('7f680000-0000-4000-8000-00000000030'||n)::uuid;l:=('7f680000-0000-4000-8000-00000000040'||n)::uuid;
  insert into public.aqari_properties(id,workspace_id,external_ref,name,metadata) values(p,w,'DOC-P-'||n,'عقار اختبار '||n,'{}');
  insert into public.aqari_units(id,workspace_id,property_id,unit_no) values(u,w,p,'10'||n);
  insert into public.aqari_tenants(id,workspace_id,external_ref,full_name,civil_id,phone,profile) values(t,w,'DOC-T-'||n,'مستأجر اختبار '||n,'76800000000'||n,'7680000'||n,'{}');
  
  insert into private.aqari_unit_readiness(id,workspace_id,unit_id,revision,state,inspected_on,source_ref,reason,recorded_by)
  select gen_random_uuid(),u.workspace_id,u.id,1,'ready',current_date,'Synthetic acceptance fixture','Synthetic inspection for archive test',auth.uid()
  from public.aqari_units u where left(u.id::text,8)='7f680000'
   and not exists(select 1 from private.aqari_unit_readiness r where r.workspace_id=u.workspace_id and r.unit_id=u.id);
insert into public.aqari_leases(id,workspace_id,external_ref,tenant_id,unit_id,contract_no,start_date,end_date,monthly_rent,deposit,status,snapshot)
   values(l,w,'DOC-L-'||n,t,u,'DOC-L-'||n,'2026-01-01','2026-12-31',100,50,'signed','{}');
  insert into public.aqari_rent_payments(id,workspace_id,lease_id,reference,amount,period,paid_at,status,payment_method,record,receipt)
   values(('7f680000-0000-4000-8000-00000000050'||n)::uuid,w,l,'DOC-PAY-'||n,12.345,'2026-09-01','2026-09-05','paid','cash','{}','{"collectorName":"محصل الاختبار"}');
 end loop;
 insert into private.aqari_staff_assignments(workspace_id,user_id,operational_role,property_ids,is_active,updated_by)values
 (current_setting('aqari.test.official_source.workspace')::uuid,'7f680000-0000-4000-8000-000000000002','accountant',array['7f680000-0000-4000-8000-000000000101']::uuid[],true,'7f680000-0000-4000-8000-000000000001');
end $$;
create function pg_temp.document_request(w uuid,l uuid,p uuid,n integer) returns jsonb language plpgsql as $$
declare v jsonb;body text;snapshot jsonb;no text;begin
 no:=public.aqari_official_document_number(w,('7f680000-0000-4000-8000-'||lpad((600+n)::text,12,'0'))::uuid,'rent_receipt',l)->>'document_no';
 v:=private.aqari_official_source(w,'rent_receipt','lease',l,p)||jsonb_build_object('documentNo',no,'issuedAt','2026-09-12');
 body:='نشهد باستلام مبلغ '||(v->>'amount')||' د.ك من السيد/السيدة '||(v->>'tenantName')||' عن إيجار الوحدة '||(v->>'unitNo')||' في '||(v->>'propertyName')||' عن الفترة '||(v->>'period')||'، بموجب العقد رقم '||(v->>'contractNo')||' وطريقة السداد '||(v->>'paymentMethod')||' والمرجع '||(v->>'paymentReference')||'.';
 snapshot:=jsonb_build_object('kind','rent_receipt','title','وصل إيجار','documentNo',no,'version',1,'issuedAt','2026-09-12','body',body,'payload',v);
 return jsonb_build_object('id',('7f680000-0000-4000-8000-'||lpad((600+n)::text,12,'0'))::uuid,'version_id',('7f680000-0000-4000-8000-'||lpad((700+n)::text,12,'0'))::uuid,
  'event_id',gen_random_uuid(),'kind','rent_receipt','document_no',no,'entity_type','lease','entity_id',l,'title','وصل إيجار','body',body,'payload',v,'template_version',1,
  'content_sha256',encode(sha256(convert_to(private.aqari_official_canonical(snapshot),'UTF8')),'hex'),'reason','إصدار اختبار من مصدر محفوظ');
end$$;
select set_config('aqari.test.official_source.req1',pg_temp.document_request(current_setting('aqari.test.official_source.workspace')::uuid,'7f680000-0000-4000-8000-000000000401','7f680000-0000-4000-8000-000000000501',1)::text,true);
select set_config('aqari.test.official_source.req2',pg_temp.document_request(current_setting('aqari.test.official_source.workspace')::uuid,'7f680000-0000-4000-8000-000000000402','7f680000-0000-4000-8000-000000000502',2)::text,true);
set local role authenticated;
select public.aqari_official_document_register(current_setting('aqari.test.official_source.workspace')::uuid,'issue',current_setting('aqari.test.official_source.req1')::jsonb);
select public.aqari_official_document_register(current_setting('aqari.test.official_source.workspace')::uuid,'issue',current_setting('aqari.test.official_source.req2')::jsonb);
reset role;
create function pg_temp.pdf_commit(doc uuid default '7f680000-0000-4000-8000-000000000601', actor uuid default '7f680000-0000-4000-8000-000000000001', bytes text default '%PDF-1.7 archive-test', v integer default 1) returns jsonb language plpgsql as $$
declare w uuid:=current_setting('aqari.test.official_source.workspace')::uuid; h text;begin
 h:=(case when doc='7f680000-0000-4000-8000-000000000601' then current_setting('aqari.test.official_source.req1') else current_setting('aqari.test.official_source.req2') end)::jsonb->>'content_sha256';
 return public.aqari_official_pdf_commit(w,doc,v,actor,h,encode(convert_to(bytes,'UTF8'),'base64'),encode(sha256(convert_to(bytes,'UTF8')),'hex'),'test-renderer');
end $$;
set local role authenticated;
do $$declare w uuid:=current_setting('aqari.test.official_source.workspace')::uuid;begin
 if public.aqari_official_pdf_get(w,'7f680000-0000-4000-8000-000000000601',1)<>'{}'::jsonb then raise exception 'PHANTOM_ARCHIVE';end if;
 begin perform pg_temp.pdf_commit();raise exception 'BROWSER_CAN_FORGE_PDF';exception when insufficient_privilege then null;end;
 begin perform 1 from private.aqari_official_pdf_artifacts;raise exception 'DIRECT_PDF_ACCESS';exception when insufficient_privilege then null;end;
end $$;
reset role;
set local role anon;
do $$begin
 begin perform public.aqari_official_pdf_get(current_setting('aqari.test.official_source.workspace')::uuid,'7f680000-0000-4000-8000-000000000601',1);raise exception 'ANONYMOUS_PDF_ACCESS';exception when insufficient_privilege then null;end;
end $$;
reset role;
set local role service_role;
do $$declare w uuid:=current_setting('aqari.test.official_source.workspace')::uuid;r jsonb;before_claims text:=current_setting('request.jwt.claims');begin
 r:=pg_temp.pdf_commit();if r->>'archived'<>'true' or r->>'replayed'<>'false' then raise exception 'FIRST_COMMIT_FAILED';end if;
 if current_setting('request.jwt.claims') is distinct from before_claims then raise exception 'ACTOR_CONTEXT_LEAK';end if;
 r:=pg_temp.pdf_commit();if r->>'replayed'<>'true' then raise exception 'RETRY_NOT_IDEMPOTENT';end if;
 begin perform pg_temp.pdf_commit(bytes=>'%PDF-1.7 different');raise exception 'ORIGINAL_BYTES_REPLACED';exception when unique_violation then null;end;
 begin perform pg_temp.pdf_commit('7f680000-0000-4000-8000-000000000602','7f680000-0000-4000-8000-000000000002');raise exception 'RENDERER_IGNORES_ACTOR_PROPERTY_SCOPE';exception when insufficient_privilege then null;end;
 begin perform pg_temp.pdf_commit(actor=>'7f680000-0000-4000-8000-000000000099');raise exception 'RENDERER_IGNORES_MEMBERSHIP';exception when insufficient_privilege then null;end;
 begin perform public.aqari_official_pdf_commit(w,'7f680000-0000-4000-8000-000000000601',1,'7f680000-0000-4000-8000-000000000001',repeat('a',64),'JVBERi0xLjc=',repeat('b',64),'test');raise exception 'BAD_SNAPSHOT_ALLOWED';exception when check_violation then null;end;
 begin perform pg_temp.pdf_commit(bytes=>'not a PDF');raise exception 'BAD_MAGIC_ALLOWED';exception when check_violation then null;end;
end $$;
reset role;
do $$declare w uuid:=current_setting('aqari.test.official_source.workspace')::uuid;begin
 if (select count(*) from private.aqari_official_document_events where workspace_id=w and action='pdf_export')<>1 then raise exception 'RETRY_DUPLICATED_AUDIT';end if;
 begin update private.aqari_official_pdf_artifacts set renderer_version='changed' where workspace_id=w;raise exception 'ORIGINAL_MUTABLE';exception when check_violation then null;end;
 begin delete from private.aqari_official_pdf_artifacts where workspace_id=w;raise exception 'ORIGINAL_DELETABLE';exception when check_violation then null;end;
end $$;
-- A correction has its own PDF; the first version is never replaced.
set local role authenticated;
select public.aqari_official_document_register(current_setting('aqari.test.official_source.workspace')::uuid,'supersede',
 current_setting('aqari.test.official_source.req1')::jsonb||jsonb_build_object('expected_version',1,'version_id',gen_random_uuid(),'event_id',gen_random_uuid()));
reset role;
set local role service_role;
select pg_temp.pdf_commit(bytes=>'%PDF-1.7 corrected-v2',v=>2);
reset role;
set local role authenticated;
do $$declare w uuid:=current_setting('aqari.test.official_source.workspace')::uuid;r jsonb;begin
 r:=public.aqari_official_pdf_get(w,'7f680000-0000-4000-8000-000000000601',1);
 if convert_from(decode(r->>'pdf_base64','base64'),'UTF8')<>'%PDF-1.7 archive-test' or r->>'document_status'<>'issued' then raise exception 'BYTES_READBACK_FAILED';end if;
 r:=public.aqari_official_pdf_get(w,'7f680000-0000-4000-8000-000000000601',2);
 if convert_from(decode(r->>'pdf_base64','base64'),'UTF8')<>'%PDF-1.7 corrected-v2' then raise exception 'CORRECTION_REUSED_WRONG_PDF';end if;
 begin perform public.aqari_official_pdf_get(w,'7f680000-0000-4000-8000-000000000601',3);raise exception 'WRONG_VERSION_ALLOWED';exception when no_data_found then null;end;
 perform public.aqari_official_document_register(w,'void',jsonb_build_object('id','7f680000-0000-4000-8000-000000000601','event_id',gen_random_uuid(),'reason','إلغاء اختبار'));
 perform public.aqari_official_document_register(w,'void',jsonb_build_object('id','7f680000-0000-4000-8000-000000000602','event_id',gen_random_uuid(),'reason','إلغاء قبل تصدير'));
 r:=public.aqari_official_pdf_get(w,'7f680000-0000-4000-8000-000000000601',1);
 if convert_from(decode(r->>'pdf_base64','base64'),'UTF8')<>'%PDF-1.7 archive-test' or r->>'document_status'<>'void' then raise exception 'VOID_REWROTE_ORIGINAL';end if;
end $$;
reset role;
set local role service_role;
do $$begin
 begin perform pg_temp.pdf_commit('7f680000-0000-4000-8000-000000000602');raise exception 'VOID_DOCUMENT_ORIGINAL_FABRICATED';exception when check_violation then null;end;
end $$;
reset role;
update public.aqari_memberships set is_active=false where user_id='7f680000-0000-4000-8000-000000000001';
set local role authenticated;
do $$begin
 begin perform public.aqari_official_pdf_get(current_setting('aqari.test.official_source.workspace')::uuid,'7f680000-0000-4000-8000-000000000601',1);raise exception 'REVOKED_USER_DOWNLOAD';exception when insufficient_privilege then null;end;
end $$;
reset role;rollback;
select 'PASS: immutable PDF bytes, service-only writes, scoped readback, retry, cancellation and revoked access';
