-- Generated by scripts/build-hosted-readiness-test.mjs.
-- Verified isolated target only, BEFORE activation; schema and fixtures all roll back.
begin;
set local statement_timeout='45s';
set local lock_timeout='3s';
insert into public.aqari_workspaces(id,slug,name) values('7f6c0000-0000-4000-8000-000000000098','aqari-v267-readiness-acceptance-20260912','اختبار جاهزية مؤقت — يتراجع بالكامل');
insert into public.aqari_app_state(workspace_id,payload) values('7f6c0000-0000-4000-8000-000000000098','{}');
-- Positive local fixture carries current MFA evidence; production guards remain enabled.
-- Local isolated runner only. Existing signed lease predates the new readiness guard.
insert into private.aqari_allowed_users(email,display_name,role,workspace_slug) values
 ('readiness-manager@example.invalid','مدير اختبار الجاهزية','general_manager','aqari-v267-readiness-acceptance-20260912'),
 ('readiness-maintenance@example.invalid','صيانة اختبار الجاهزية','property_manager','aqari-v267-readiness-acceptance-20260912'),
 ('readiness-viewer@example.invalid','عرض اختبار الجاهزية','viewer','aqari-v267-readiness-acceptance-20260912');
insert into auth.users(id,email,email_confirmed_at) values
 ('76620000-0000-4000-8000-000000000001','readiness-manager@example.invalid',now()),
 ('76620000-0000-4000-8000-000000000002','readiness-maintenance@example.invalid',now()),
 ('76620000-0000-4000-8000-000000000003','readiness-viewer@example.invalid',now());
select set_config('aqari.test.readiness.workspace',(select workspace_id::text from public.aqari_memberships where user_id='76620000-0000-4000-8000-000000000001' and is_active),true);
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from statement_timestamp()))::bigint)))::text,true);
insert into public.aqari_properties(id,workspace_id,external_ref,name,metadata)
 select ('76620000-0000-4000-8000-00000000010'||n)::uuid,current_setting('aqari.test.readiness.workspace')::uuid,'readiness-property-'||n,'عقار اختبار الجاهزية '||n,'{}' from generate_series(1,2)n;
insert into public.aqari_units(id,workspace_id,property_id,unit_no)
 values('76620000-0000-4000-8000-000000000201',current_setting('aqari.test.readiness.workspace')::uuid,'76620000-0000-4000-8000-000000000101','101');
insert into public.aqari_tenants(id,workspace_id,external_ref,full_name,civil_id,phone,profile)
 values('76620000-0000-4000-8000-000000000301',current_setting('aqari.test.readiness.workspace')::uuid,'readiness-tenant','مستأجر اختبار الجاهزية','766200000001','76620001','{}');
insert into public.aqari_leases(id,workspace_id,external_ref,tenant_id,unit_id,contract_no,start_date,end_date,monthly_rent,deposit,status,snapshot)
 values('76620000-0000-4000-8000-000000000401',current_setting('aqari.test.readiness.workspace')::uuid,'readiness-existing','76620000-0000-4000-8000-000000000301','76620000-0000-4000-8000-000000000201','READINESS-EXISTING','2025-01-01','2025-12-31',100,50,'signed','{"source":"preserved"}');
insert into private.aqari_staff_assignments(workspace_id,user_id,operational_role,property_ids,is_active,updated_by) values
 (current_setting('aqari.test.readiness.workspace')::uuid,'76620000-0000-4000-8000-000000000002','maintenance',array['76620000-0000-4000-8000-000000000101']::uuid[],true,'76620000-0000-4000-8000-000000000001'),
 (current_setting('aqari.test.readiness.workspace')::uuid,'76620000-0000-4000-8000-000000000003','viewer',array['76620000-0000-4000-8000-000000000101']::uuid[],true,'76620000-0000-4000-8000-000000000001');

-- A second workspace exercises the actual state RPC and receipt projection.
insert into public.aqari_workspaces(id,slug,name) values('76620000-0000-4000-8000-000000000900','readiness-legacy-save','Local readiness projection fixture');
insert into public.aqari_app_state(workspace_id,payload) values('76620000-0000-4000-8000-000000000900','{}');
insert into private.aqari_allowed_users(email,display_name,role,workspace_slug) values('readiness-projection@example.invalid','مدير حفظ اصطناعي','general_manager','readiness-legacy-save');
insert into auth.users(id,email,email_confirmed_at) values('76620000-0000-4000-8000-000000000004','readiness-projection@example.invalid',now());
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000004',true);
set local role authenticated;
do $$declare t jsonb;c jsonb;d jsonb;begin
 t:='{"id":"readiness-projection-t","nameAr":"مستأجر حفظ اصطناعي","nameEn":"Readiness Projection Tenant","civilId":"766200000004","passportNo":"READINESS-4","phone":"76620004","nationality":"اختبار","email":"readiness-tenant@example.invalid","attachments":[]}';
 c:=jsonb_build_object('id','readiness-projection-c','source','v267-cloud','detailsVersion',2,'tenantId',t->>'id','tenant',t->>'nameAr','tenantProfile',t,'property','عقار حفظ اصطناعي','unit','1','floor','الأول','contract_no','READINESS-PROJECTION','start_date',to_char(current_date-interval '1 month','YYYY-MM-DD'),'end_date',to_char(current_date+interval '1 year','YYYY-MM-DD'),'writtenOn',to_char(now() at time zone 'Asia/Kuwait','YYYY-MM-DD'),'receivedAt',to_char((now()-interval '1 hour') at time zone 'Asia/Kuwait','YYYY-MM-DD"T"HH24:MI:SS')||'+03:00','contractReceived','مستلم','evictionNotice','لم يُبلّغ','accountant','محاسب اختبار','contractRent',100,'discount',0,'rent',100,'deposit',0,'advance',0,'cleaningFee',0,'status','signed');
 d:=jsonb_build_object('properties',jsonb_build_array(jsonb_build_array(c->>'property')),'tenants',jsonb_build_array(jsonb_build_array(t->>'nameAr',c->>'property',t->>'phone','اختبار',t->>'id')),'tenantProfilesV267',jsonb_build_array(t),'contractsV202',jsonb_build_array(c),'leases',jsonb_build_array(jsonb_build_array(c->>'tenant',c->>'unit',100,c->>'end_date',c->>'id')),'tenantDirectoryV202',jsonb_build_array(jsonb_build_object('property',c->>'property','unit',c->>'unit','tenant',c->>'tenant','contractNo',c->>'contract_no','phone',t->>'phone','civilId',t->>'civilId','tenantProfileId',t->>'id')));
 perform public.aqari_save_state_v267('76620000-0000-4000-8000-000000000900',d,1);
end$$;
reset role;
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000001',true);

-- AQARI V267: explicit, audited unit readiness before a new tenancy.
-- Apply on the independently verified test branch only after its backup is verified.
-- Requires staff-property-scope.sql and mfa-enforcement.sql. Existing data is not rewritten.

create table private.aqari_unit_readiness(
 id uuid primary key,workspace_id uuid not null,unit_id uuid not null,
 revision bigint not null check(revision>0),
 state text not null check(state in ('ready','not_ready','review_required')),
 inspected_on date not null,source_ref text not null check(length(btrim(source_ref)) between 3 and 500),
 reason text not null check(length(btrim(reason)) between 3 and 500),
 recorded_by uuid not null references auth.users(id),recorded_at timestamptz not null default now(),
 foreign key(workspace_id,unit_id) references public.aqari_units(workspace_id,id),
 unique(workspace_id,unit_id,revision)
);
alter table private.aqari_unit_readiness enable row level security;
revoke all on private.aqari_unit_readiness from public,anon,authenticated;
create function private.aqari_readiness_immutable() returns trigger
language plpgsql set search_path='' as $$begin raise check_violation using message='READINESS_HISTORY_IMMUTABLE';end$$;
revoke all on function private.aqari_readiness_immutable() from public,anon,authenticated;
create trigger aqari_unit_readiness_immutable before update or delete on private.aqari_unit_readiness
 for each row execute function private.aqari_readiness_immutable();

create function public.aqari_unit_readiness_register(p_workspace_id uuid,p_action text,p_data jsonb default '{}') returns jsonb
language plpgsql volatile security definer set search_path='' as $$
declare w uuid:=p_workspace_id;d jsonb:=p_data;p uuid;u public.aqari_units;
 saved private.aqari_unit_readiness;ident uuid;expected bigint;version bigint;number text;observed date;
begin
 if auth.uid() is null or not private.aqari_can(w,'properties','read') then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 if p_action is null or p_action not in ('list','record') or d is null or jsonb_typeof(d)<>'object' or octet_length(d::text)>8192 then raise invalid_parameter_value using message='INVALID_READINESS_REQUEST';end if;
 if p_action='list' then
  return jsonb_build_object(
   'properties',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'name',x.name,'can_create',private.aqari_can_property(w,x.id,'properties','write'),'can_write',private.aqari_can_property(w,x.id,'properties','write') or private.aqari_can_property(w,x.id,'maintenance','write')) order by x.name,x.id) from public.aqari_properties x where x.workspace_id=w and private.aqari_can_property(w,x.id,'properties','read')),'[]'),
   'units',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'property_id',x.property_id,'unit_no',x.unit_no,'revision',coalesce(r.revision,0),'state',coalesce(r.state,'review_required'),'inspected_on',r.inspected_on,'source_ref',r.source_ref,'reason',r.reason) order by x.unit_no,x.id)
    from public.aqari_units x left join lateral(select y.* from private.aqari_unit_readiness y where y.workspace_id=w and y.unit_id=x.id order by y.revision desc limit 1)r on true where x.workspace_id=w and private.aqari_can_property(w,x.property_id,'properties','read')),'[]'),
   'history',coalesce((select jsonb_agg(to_jsonb(r) order by r.recorded_at desc,r.revision desc) from private.aqari_unit_readiness r join public.aqari_units x on x.workspace_id=r.workspace_id and x.id=r.unit_id where r.workspace_id=w and private.aqari_can_property(w,x.property_id,'properties','read')),'[]'));
 end if;
 ident:=(d->>'id')::uuid;p:=(d->>'property_id')::uuid;
 if ident is null or p is null or not (private.aqari_can_property(w,p,'properties','write') or private.aqari_can_property(w,p,'maintenance','write')) then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 perform private.aqari_require_sensitive_aal2(w);
 number:=translate(btrim(coalesce(d->>'unit_no','')),'٠١٢٣٤٥٦٧٨٩','0123456789');
 if length(number) not between 1 and 80 or number~'[[:cntrl:]<>]' or coalesce(d->>'state','') not in ('ready','not_ready','review_required') or coalesce(d->>'expected_revision','')!~'^[0-9]{1,15}$' or coalesce(d->>'inspected_on','')!~'^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or length(btrim(coalesce(d->>'source_ref',''))) not between 3 and 500 or length(btrim(coalesce(d->>'reason',''))) not between 3 and 500 then raise check_violation using message='INVALID_READINESS_RECORD';end if;
 expected:=(d->>'expected_revision')::bigint;observed:=(d->>'inspected_on')::date;
 if observed>(now() at time zone 'Asia/Kuwait')::date then raise check_violation using message='INVALID_READINESS_DATE';end if;
 select * into u from public.aqari_units where workspace_id=w and property_id=p and unit_no=number for update;
 if u.id is null then
  if not private.aqari_can_property(w,p,'properties','write') then raise insufficient_privilege using message='ACCESS_DENIED';end if;
  insert into public.aqari_units(id,workspace_id,property_id,unit_no) values(md5(p::text||':unit:'||number)::uuid,w,p,number) on conflict(workspace_id,property_id,unit_no) do nothing;
  select * into u from public.aqari_units where workspace_id=w and property_id=p and unit_no=number for update;
 end if;
 select * into saved from private.aqari_unit_readiness where id=ident;
 if found then
  if saved.workspace_id<>w or saved.unit_id<>u.id or saved.revision<>expected+1 or saved.state<>d->>'state' or saved.inspected_on<>observed or saved.source_ref<>btrim(d->>'source_ref') or saved.reason<>btrim(d->>'reason') then raise unique_violation using message='READINESS_IDEMPOTENCY_CONFLICT';end if;
  return to_jsonb(saved);
 end if;
 select coalesce(max(revision),0) into version from private.aqari_unit_readiness where workspace_id=w and unit_id=u.id;
 if version<>expected then raise serialization_failure using message='REVISION_CONFLICT';end if;
 insert into private.aqari_unit_readiness(id,workspace_id,unit_id,revision,state,inspected_on,source_ref,reason,recorded_by)
 values(ident,w,u.id,version+1,d->>'state',observed,btrim(d->>'source_ref'),btrim(d->>'reason'),auth.uid()) returning * into saved;
 return to_jsonb(saved);
end$$;
revoke all on function public.aqari_unit_readiness_register(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.aqari_unit_readiness_register(uuid,text,jsonb) to authenticated;

create function private.aqari_require_unit_ready() returns trigger
language plpgsql volatile security definer set search_path='' as $$
declare readiness text;
begin
 if new.status in ('cancelled','expired') then return new;end if;
 -- Preserve existing leases and routine state projection/financial saves. A new
 -- lease, reactivation, progression from draft, move or date extension needs review.
 if tg_op='UPDATE' then
  if new.workspace_id=old.workspace_id and new.unit_id=old.unit_id and new.tenant_id=old.tenant_id
   and new.start_date>=old.start_date and new.end_date<=old.end_date
   and (new.status=old.status or (old.status not in ('draft','ready','cancelled','expired') and new.status not in ('draft','ready'))) then return new;end if;
 end if;
 -- Share a row lock with readiness recording so acceptance cannot race a
 -- readiness change. AFTER INSERT runs only for new rows, not UPSERT conflicts.
 perform 1 from public.aqari_units where workspace_id=new.workspace_id and id=new.unit_id for update;
 select r.state into readiness from private.aqari_unit_readiness r where r.workspace_id=new.workspace_id and r.unit_id=new.unit_id order by r.revision desc limit 1;
 if readiness is distinct from 'ready' then raise check_violation using message='UNIT_NOT_READY';end if;
 return new;
end$$;
revoke all on function private.aqari_require_unit_ready() from public,anon,authenticated;
create trigger aqari_unit_ready_insert after insert on public.aqari_leases for each row execute function private.aqari_require_unit_ready();
create trigger aqari_unit_ready_update before update on public.aqari_leases for each row execute function private.aqari_require_unit_ready();


-- Local synthetic acceptance after unit-readiness-existing.sql and unit-readiness.sql.
-- The existing fixture predates the migration; no trigger or check is disabled.
savepoint unit_readiness;
do $$declare w uuid:=current_setting('aqari.test.readiness.workspace')::uuid;begin
 -- A new tenancy must fail atomically when readiness has never been recorded.
 begin
  insert into public.aqari_leases(id,workspace_id,external_ref,tenant_id,unit_id,contract_no,start_date,end_date,monthly_rent,deposit,status,snapshot)
   values('76620000-0000-4000-8000-000000000402',w,'readiness-new','76620000-0000-4000-8000-000000000301','76620000-0000-4000-8000-000000000201','READINESS-NEW','2026-01-01','2026-12-31',100,50,'draft','{}');
  raise exception 'UNREVIEWED_UNIT_WAS_LEASED';
 exception when check_violation then if sqlerrm<>'UNIT_NOT_READY' then raise;end if;end;
 if exists(select 1 from public.aqari_leases where id='76620000-0000-4000-8000-000000000402') then raise exception 'PARTIAL_LEASE_REMAINS';end if;
 -- An unrelated financial save reprojects the old lease using an UPSERT.
 insert into public.aqari_leases select * from public.aqari_leases where id='76620000-0000-4000-8000-000000000401'
 on conflict(id) do update set snapshot=excluded.snapshot;
 if (select snapshot->>'source' from public.aqari_leases where id='76620000-0000-4000-8000-000000000401')<>'preserved' then raise exception 'EXISTING_LEASE_CHANGED';end if;
 begin update public.aqari_leases set end_date='2026-12-31' where id='76620000-0000-4000-8000-000000000401';raise exception 'UNREVIEWED_EXTENSION_ACCEPTED';exception when check_violation then if sqlerrm<>'UNIT_NOT_READY' then raise;end if;end;
end$$;
set local role authenticated;
do $$declare w uuid:=current_setting('aqari.test.readiness.workspace')::uuid;d jsonb;r jsonb;begin
 d:='{"id":"76620000-0000-4000-8000-000000000501","property_id":"76620000-0000-4000-8000-000000000101","unit_no":"١٠١","expected_revision":0,"state":"ready","inspected_on":"2026-01-01","source_ref":"محضر فحص اصطناعي","reason":"اجتازت الوحدة الفحص"}';
 if public.aqari_workspace_access(w)#>'{features,unit_readiness}' is distinct from 'true'::jsonb then raise exception 'READINESS_NOT_DISCOVERED';end if;
 r:=public.aqari_unit_readiness_register(w,'record',d);
 if r->>'unit_id'<>'76620000-0000-4000-8000-000000000201' or r->>'state'<>'ready' or (r->>'revision')::integer<>1 then raise exception 'READINESS_READBACK_FAILED';end if;
 if public.aqari_unit_readiness_register(w,'record',d) is distinct from r then raise exception 'READINESS_RETRY_CHANGED';end if;
 begin perform public.aqari_unit_readiness_register(w,'record',d||'{"reason":"محتوى مختلف لنفس المعرف"}');raise exception 'CHANGED_RETRY_ACCEPTED';exception when unique_violation then null;end;
 begin perform public.aqari_unit_readiness_register(w,'record',d||'{"id":"76620000-0000-4000-8000-000000000502"}');raise exception 'STALE_REVISION_ACCEPTED';exception when serialization_failure then null;end;
 begin perform public.aqari_unit_readiness_register(w,'record',d||'{"inspected_on":"2099-01-01"}');raise exception 'FUTURE_REVIEW_ACCEPTED';exception when check_violation then null;end;
 begin perform 1 from private.aqari_unit_readiness;raise exception 'PRIVATE_READINESS_TABLE_EXPOSED';exception when insufficient_privilege then null;end;
end$$;
reset role;
insert into public.aqari_leases(id,workspace_id,external_ref,tenant_id,unit_id,contract_no,start_date,end_date,monthly_rent,deposit,status,snapshot)
 values('76620000-0000-4000-8000-000000000402',current_setting('aqari.test.readiness.workspace')::uuid,'readiness-new','76620000-0000-4000-8000-000000000301','76620000-0000-4000-8000-000000000201','READINESS-NEW','2026-01-01','2026-12-31',100,50,'draft','{}');
do $$begin
 begin insert into public.aqari_leases(id,workspace_id,external_ref,tenant_id,unit_id,contract_no,start_date,end_date,monthly_rent,deposit,status,snapshot)
  values('76620000-0000-4000-8000-000000000403',current_setting('aqari.test.readiness.workspace')::uuid,'readiness-overlap','76620000-0000-4000-8000-000000000301','76620000-0000-4000-8000-000000000201','READINESS-OVERLAP','2026-02-01','2026-03-31',100,50,'draft','{}');
  raise exception 'EXISTING_OVERLAP_GUARD_LOST';exception when exclusion_violation then null;end;
end$$;
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000002',true);
set local role authenticated;
do $$declare w uuid:=current_setting('aqari.test.readiness.workspace')::uuid;d jsonb;rows jsonb;begin
 rows:=public.aqari_unit_readiness_register(w,'list');
 if jsonb_array_length(rows->'properties')<>1 or jsonb_array_length(rows->'units')<>1 or jsonb_array_length(rows->'history')<>1 then raise exception 'READINESS_PROPERTY_SCOPE_FAILED';end if;
 d:='{"id":"76620000-0000-4000-8000-000000000502","property_id":"76620000-0000-4000-8000-000000000101","unit_no":"101","expected_revision":1,"state":"not_ready","inspected_on":"2026-01-02","source_ref":"محضر صيانة اصطناعي","reason":"أعمال صيانة تحتاج استكمال"}';
 perform public.aqari_unit_readiness_register(w,'record',d);
 begin perform public.aqari_unit_readiness_register(w,'record',d||'{"property_id":"76620000-0000-4000-8000-000000000102"}');raise exception 'FOREIGN_PROPERTY_WRITE_ACCEPTED';exception when insufficient_privilege then null;end;
 begin perform public.aqari_unit_readiness_register(w,'record',d||'{"unit_no":"999","expected_revision":0}');raise exception 'MAINTENANCE_CREATED_UNIT';exception when insufficient_privilege then null;end;
end$$;
reset role;
do $$begin
 begin update public.aqari_leases set status='ready' where id='76620000-0000-4000-8000-000000000402';raise exception 'UNREADY_DRAFT_PROGRESSED';exception when check_violation then if sqlerrm<>'UNIT_NOT_READY' then raise;end if;end;
 update public.aqari_leases set status='cancelled' where id='76620000-0000-4000-8000-000000000402';
 begin update public.aqari_leases set status='signed' where id='76620000-0000-4000-8000-000000000402';raise exception 'UNREADY_LEASE_REACTIVATED';exception when check_violation then if sqlerrm<>'UNIT_NOT_READY' then raise;end if;end;
 begin update private.aqari_unit_readiness set state='ready' where id='76620000-0000-4000-8000-000000000502';raise exception 'READINESS_HISTORY_REWRITTEN';exception when check_violation then null;end;
 begin delete from private.aqari_unit_readiness where id='76620000-0000-4000-8000-000000000502';raise exception 'READINESS_HISTORY_DELETED';exception when check_violation then null;end;
 if (select count(*) from private.aqari_unit_readiness)<>2 then raise exception 'READINESS_AUDIT_HISTORY_LOST';end if;
 if has_function_privilege('anon','public.aqari_unit_readiness_register(uuid,text,jsonb)','execute') then raise exception 'ANON_READINESS_ACCESS';end if;
end$$;
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000003',true);
set local role authenticated;
do $$begin
 begin perform public.aqari_unit_readiness_register(current_setting('aqari.test.readiness.workspace')::uuid,'record','{"id":"76620000-0000-4000-8000-000000000503","property_id":"76620000-0000-4000-8000-000000000101"}');raise exception 'VIEWER_MARKED_READY';exception when insufficient_privilege then null;end;
end$$;
reset role;
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000001',true);
select set_config('request.jwt.claims','{"aal":"aal1"}',true);
set local role authenticated;
do $$begin
 begin perform public.aqari_unit_readiness_register(current_setting('aqari.test.readiness.workspace')::uuid,'record','{"id":"76620000-0000-4000-8000-000000000503","property_id":"76620000-0000-4000-8000-000000000101"}');raise exception 'MANAGER_BYPASSED_MFA';exception when insufficient_privilege then if sqlerrm<>'MFA_REQUIRED' then raise;end if;end;
end$$;
reset role;
rollback to savepoint unit_readiness;
select 'PASS: readiness, new lease denial, unchanged legacy UPSERT, extensions, progression, overlap, property scope, immutable history, retry and MFA';

-- Positive synthetic MFA fixture: include a current supported second-factor event.
-- Negative AAL1/expired-MFA cases and all production guards remain unchanged.
-- Regression on the real application state RPC, after the readiness migration.
savepoint unit_readiness_projection;
select set_config('request.jwt.claim.sub','76620000-0000-4000-8000-000000000004',true);
select set_config('request.jwt.claims',jsonb_build_object('aal','aal2','amr',jsonb_build_array(jsonb_build_object('method','totp','timestamp',floor(extract(epoch from statement_timestamp()))::bigint)))::text,true);
set local role authenticated;
do $$declare w uuid:='76620000-0000-4000-8000-000000000900';state jsonb;d jsonb;c jsonb;r jsonb;row_data jsonb;receipt jsonb;p uuid;prior jsonb;begin
 state:=public.aqari_read_state_v267(w);d:=state->'payload';c:=d->'contractsV202'->0;prior:=c;
 -- Its existing lease predates readiness and must still support collection.
 row_data:=jsonb_build_array('READINESS-RECEIPT',c->>'tenant',20,'جزئي',c->>'property',current_date::text,c->>'unit','موظف اختبار',to_char(current_date,'YYYY-MM'),'نقدي');
 r:=jsonb_build_object('receiptNo',row_data->>0,'contractId',c->>'id','contractNo',c->>'contract_no','property',c->>'property','unit',c->>'unit','tenant',c->>'tenant','paid',20,'due',100,'period',to_char(current_date,'YYYY-MM'),'paidAt',current_date::text,'status','جزئي','method','نقدي','transactionNo','','accountant',c->>'accountant');
 receipt:=jsonb_build_object('id',row_data->>0,'detailsVersion',2,'template','rent-voucher-v267-1','record',row_data,'contract',c,'accountant',c->>'accountant','transactionNo','');
 d:=d||jsonb_build_object('collections',jsonb_build_array(row_data),'rentLedgerV202',jsonb_build_array(r),'rentReceiptsV267',jsonb_build_array(receipt));
 perform public.aqari_save_state_v267(w,d,(state->>'revision')::bigint);
 state:=public.aqari_read_state_v267(w);
 if state->'payload' is distinct from d then raise exception 'READINESS_PAYMENT_READBACK_MISMATCH';end if;
 -- A new unit and tenancy through the same RPC must be rejected atomically.
 c:=c||jsonb_build_object('id','readiness-new-projection','unit','2','contract_no','READINESS-NEW-PROJECTION','status','draft');
 begin
  perform public.aqari_save_state_v267(w,jsonb_set(d,'{contractsV202}',d->'contractsV202'||jsonb_build_array(c)),(state->>'revision')::bigint);
  raise exception 'STATE_RPC_BYPASSED_READINESS';
 exception when check_violation then if sqlerrm<>'UNIT_NOT_READY' then raise;end if;end;
 if public.aqari_read_state_v267(w) is distinct from state then raise exception 'DENIED_LEASE_CHANGED_STATE_OR_REVISION';end if;
 -- Explicit readiness permits the same draft; no blanket approval or guessed state.
 select id into p from public.aqari_properties where workspace_id=w and name=c->>'property';
 perform public.aqari_unit_readiness_register(w,'record',jsonb_build_object('id','76620000-0000-4000-8000-000000000901','property_id',p,'unit_no','2','expected_revision',0,'state','ready','inspected_on',current_date::text,'source_ref','محضر فحص اصطناعي','reason','اجتازت الوحدة الفحص'));
 perform public.aqari_save_state_v267(w,jsonb_set(d,'{contractsV202}',d->'contractsV202'||jsonb_build_array(c)),(state->>'revision')::bigint);
 if public.aqari_read_state_v267(w)#>'{payload,contractsV202,0}' is distinct from prior then raise exception 'EXISTING_CONTRACT_MUTATED';end if;
 if public.aqari_read_state_v267(w)#>'{payload,rentReceiptsV267,0}' is distinct from receipt then raise exception 'EXISTING_RECEIPT_MUTATED';end if;
end$$;
reset role;
do $$begin
 if (select count(*) from public.aqari_rent_payments where workspace_id='76620000-0000-4000-8000-000000000900' and amount=20 and reference='READINESS-RECEIPT')<>1 then raise exception 'PAYMENT_PROJECTION_LOST_OR_DUPLICATED';end if;
 if (select count(*) from public.aqari_leases where workspace_id='76620000-0000-4000-8000-000000000900')<>2 then raise exception 'NEW_READY_LEASE_NOT_PROJECTED';end if;
end$$;
rollback to savepoint unit_readiness_projection;
select 'PASS: real state RPC rejects unreviewed new lease atomically, accepts reviewed unit, preserves legacy contract and receipt, and projects one payment';

rollback;
select 'PASS: readiness activation rehearsal, legacy collection, new tenancy refusal, explicit readiness, role/property/MFA and overlap guards; all DDL and fixtures rolled back' as result;
