import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {verifyDeploymentTarget} from './verify-deployment-target.mjs';
import './install-v267-official-exit-notice.mjs';
verifyDeploymentTarget();
execFileSync(process.execPath,['--test','tests/v267-webhook-idempotency-conflict.test.mjs'],{stdio:'inherit'});
execFileSync(process.execPath,['--test','tests/v267-property-statement-payment-reference.test.mjs'],{stdio:'inherit'});
execFileSync(process.execPath,['--test','tests/v267-editable-ui-labels.test.mjs'],{stdio:'inherit'});
const requiredFiles=['index.html','vercel.json','api/health.js','api/release.js','api/config-status.js','.env.example','staging-database/sql/official-commercial-statement-20260915.sql','src/v267/components/official-extra-forms.js','src/v267/components/official-document-handovers.js','src/v267/support/official-exit-notice-patch.js','staging-database/supabase/migrations/20260915094500_v267_official_exit_notice_source.sql','staging-database/supabase/migrations/20260915094600_v267_official_exit_notice_context.sql','staging-database/supabase/migrations/20260915094700_v267_official_discount_approval_source.sql','staging-database/supabase/migrations/20260915094800_v267_official_discount_approval_context.sql','staging-database/supabase/migrations/20260915094900_v267_official_extra_forms_source_fix.sql','staging-database/supabase/migrations/20260915095000_v267_official_document_handovers.sql','staging-database/supabase/migrations/20260915095100_v267_official_document_handover_rpc.sql','staging-database/supabase/migrations/20260915095200_v267_official_document_handover_context.sql','staging-database/supabase/migrations/20260915095300_v267_inbound_maintenance_messages.sql','staging-database/supabase/migrations/20260915095400_v267_webhook_idempotency_conflict_guard.sql'];
let failed=false;for(const file of requiredFiles)if(!fs.existsSync(file)){console.error(`Missing: ${file}`);failed=true;}
const html=fs.readFileSync('index.html','utf8');if(!html.includes('V198')){console.error('index.html does not contain V198 release marker');failed=true;}
const commercialStatement=fs.readFileSync('staging-database/sql/official-commercial-statement-20260915.sql','utf8');for(const marker of ['aqari_commercial_collections','aqari_commercial_collection_reversals','aqari_assert_commercial_collections','commercialCollectionsIncluded','camIncluded'])if(!commercialStatement.includes(marker)){console.error(`Unified commercial statement missing: ${marker}`);failed=true;}if(commercialStatement.includes('DOCUMENT_COMMERCIAL_RECONCILIATION_REQUIRED')){console.error('Unified commercial statement regressed to blanket commercial rejection');failed=true;}
const officialCenter=fs.readFileSync('src/v267/pages/official-document-center.js','utf8');for(const marker of ['AQARI_V267_EXIT_NOTICE_FORM','EXTRA_OFFICIAL_FORM_TEMPLATES','renderExtraOfficialForm','mountOfficialDocumentHandovers'])if(!officialCenter.includes(marker)){console.error(`Official form/hand-over overlay missing: ${marker}`);failed=true;}
const extraForms=fs.readFileSync('src/v267/components/official-extra-forms.js','utf8');for(const marker of ['exit_notice','discount_approval','اعتماد خصم','فترة الخصم'])if(!extraForms.includes(marker)){console.error(`Official extra form definition missing: ${marker}`);failed=true;}
const handoverUi=fs.readFileSync('src/v267/components/official-document-handovers.js','utf8');for(const marker of ['aqari_official_document_handover','aqari_official_document_handover_context','archivedVersions','pdfSha256','OFFICIAL_HANDOVER_IDEMPOTENCY_CONFLICT'])if(!handoverUi.includes(marker)){console.error(`Official handover UI missing: ${marker}`);failed=true;}
const exitSource=fs.readFileSync('staging-database/supabase/migrations/20260915094500_v267_official_exit_notice_source.sql','utf8'),exitContext=fs.readFileSync('staging-database/supabase/migrations/20260915094600_v267_official_exit_notice_context.sql','utf8');for(const marker of ["k='exit_notice'",'DOCUMENT_VACATING_RECORD_REQUIRED','aqari_vacating_settlements','vacateDate'])if(!exitSource.includes(marker)){console.error(`Official exit notice source missing: ${marker}`);failed=true;}for(const marker of ["p_kind<>'exit_notice'",'source_required',"'entity_type','lease'",'aqari_official_source'])if(!exitContext.includes(marker)){console.error(`Official exit notice context missing: ${marker}`);failed=true;}
const discountSource=fs.readFileSync('staging-database/supabase/migrations/20260915094700_v267_official_discount_approval_source.sql','utf8'),discountFix=fs.readFileSync('staging-database/supabase/migrations/20260915094900_v267_official_extra_forms_source_fix.sql','utf8');for(const marker of ['discount_approval','DOCUMENT_NO_SAVED_DISCOUNT','aqari_rent_period_breakdown','approvedBy'])if(!discountSource.includes(marker)){console.error(`Discount approval source missing: ${marker}`);failed=true;}for(const marker of ['lease_row','DOCUMENT_NO_SAVED_DISCOUNT','rentAdjustments'])if(!discountFix.includes(marker)){console.error(`Discount approval source fix missing: ${marker}`);failed=true;}
const handoverRpc=fs.readFileSync('staging-database/supabase/migrations/20260915095100_v267_official_document_handover_rpc.sql','utf8');for(const marker of ['ARCHIVED_OFFICIAL_PDF_REQUIRED','VOID_OFFICIAL_DOCUMENT_HANDOVER_FORBIDDEN','pdfSha256','OFFICIAL_HANDOVER_IDEMPOTENCY_CONFLICT','aqari_official_document_handover_voids'])if(!handoverRpc.includes(marker)){console.error(`Official handover RPC missing: ${marker}`);failed=true;}const handoverContext=fs.readFileSync('staging-database/supabase/migrations/20260915095200_v267_official_document_handover_context.sql','utf8');for(const marker of ['archivedVersions','aqari_official_pdf_artifacts','pdfSha256'])if(!handoverContext.includes(marker)){console.error(`Official handover context missing: ${marker}`);failed=true;}
const inbound=fs.readFileSync('staging-database/supabase/migrations/20260915095300_v267_inbound_maintenance_messages.sql','utf8'),webhook=fs.readFileSync('api/provider-webhook.py','utf8'),normalizer=fs.readFileSync('lib/provider_webhook.py','utf8');for(const marker of ['aqari_maintenance_message_events','aqari_process_whatsapp_maintenance_webhook','MAINTENANCE_REQUEST_OR_SENDER_MISMATCH','MAINTENANCE_MESSAGE_REPLAY','sender_digits<>stored_digits'])if(!inbound.includes(marker)){console.error(`Inbound maintenance link missing: ${marker}`);failed=true;}for(const marker of ["provider=='whatsapp'","maintenance.message",'process_maintenance','MAINTENANCE_MESSAGE_NOT_CONFIRMED'])if(!webhook.includes(marker)){console.error(`Inbound maintenance webhook route missing: ${marker}`);failed=true;}for(const marker of ['maintenance_request_no','sender_reference','message_text','INVALID_MAINTENANCE_MESSAGE'])if(!normalizer.includes(marker)){console.error(`Maintenance webhook normalization missing: ${marker}`);failed=true;}
const idempotencyGuard=fs.readFileSync('staging-database/supabase/migrations/20260915095400_v267_webhook_idempotency_conflict_guard.sql','utf8');for(const marker of ['WEBHOOK_IDEMPOTENCY_CONFLICT','MAINTENANCE_MESSAGE_REFERENCE_REPLAY','MAINTENANCE_MESSAGE_REFERENCE_CONFLICT','provider_message_reference=reference',"jsonb_build_object('duplicate',true,'id',r.id,'status',r.status)"])if(!idempotencyGuard.includes(marker)){console.error(`Webhook idempotency guard missing: ${marker}`);failed=true;}const referenceLookup=idempotencyGuard.indexOf('provider_message_reference=reference'),referenceConflict=idempotencyGuard.indexOf('MAINTENANCE_MESSAGE_REFERENCE_CONFLICT'),messageInsert=idempotencyGuard.indexOf('insert into private.aqari_maintenance_message_events');if(referenceLookup<0||referenceConflict<=referenceLookup||messageInsert<=referenceConflict){console.error('Maintenance reference conflict guard must run before immutable insert');failed=true;}
if(failed)process.exit(1);console.log('AQARI V198 package check: PASS');
