-- AQARI V267 Preview/Staging: official system serial and atomic canonical KNET webhook settlement.
create or replace function private.aqari_system_rent_receipt_serial(p_w uuid,p_contract_ref text,p_operation_ref uuid,p_year integer) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare row_data private.aqari_rent_receipt_serial_reservations%rowtype;seq bigint;within_contract integer;result_no text;
begin
 if current_setting('role',true) is distinct from 'service_role' or p_operation_ref is null or btrim(coalesce(p_contract_ref,''))='' or p_year not between 2000 and 2200 then raise insufficient_privilege using message='SERVER_RECEIPT_SERIAL_DENIED';end if;
 select * into row_data from private.aqari_rent_receipt_serial_reservations r where r.operation_ref=p_operation_ref;if found then if row_data.workspace_id<>p_w or row_data.contract_ref<>p_contract_ref then raise check_violation using message='RECEIPT_SERIAL_SCOPE_MISMATCH';end if;return jsonb_build_object('receipt_no',row_data.receipt_no,'contract_sequence',row_data.contract_sequence);end if;
 perform pg_advisory_xact_lock(hashtextextended(p_w::text||':rent-receipt:'||p_contract_ref,0));select coalesce(max(r.contract_sequence),0)+1 into within_contract from private.aqari_rent_receipt_serial_reservations r where r.workspace_id=p_w and r.contract_ref=p_contract_ref;insert into private.aqari_global_serial_counters(kind,year,last_value) values('rent_receipt',p_year,0) on conflict(kind,year) do nothing;update private.aqari_global_serial_counters set last_value=last_value+1 where kind='rent_receipt' and year=p_year returning last_value into seq;if seq is null then raise exception 'RECEIPT_SERIAL_UNAVAILABLE';end if;result_no:='AQ-R-'||p_year::text||'-'||lpad(seq::text,8,'0');insert into private.aqari_rent_receipt_serial_reservations(receipt_no,workspace_id,contract_ref,operation_ref,year,global_serial,contract_sequence,reserved_by,reservation_actor_kind) values(result_no,p_w,p_contract_ref,p_operation_ref,p_year,seq,within_contract,null,'system') returning * into row_data;return jsonb_build_object('receipt_no',row_data.receipt_no,'contract_sequence',row_data.contract_sequence);
end $$;
revoke all on function private.aqari_system_rent_receipt_serial(uuid,text,uuid,integer) from public,anon,authenticated,service_role;grant execute on function private.aqari_system_rent_receipt_serial(uuid,text,uuid,integer) to service_role;
create or replace function public.aqari_process_knet_webhook(p_receipt_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
#variable_conflict use_variable
declare wr private.aqari_webhook_receipts%rowtype;i private.aqari_knet_payment_intents%rowtype;l public.aqari_leases%rowtype;u public.aqari_units%rowtype;p public.aqari_properties%rowtype;t public.aqari_tenants%rowtype;due private.aqari_rent_due_periods%rowtype;payload jsonb;provider_ref text;account_ref text;status_value text;event_value text;currency_value text;amount_value numeric;occurred timestamptz;paid_day date;serial jsonb;receipt_value text;contract_sequence integer;payment_value uuid;method_value text:='KNET';status_label text;period_text text;row_value jsonb;ledger jsonb;receipt_json jsonb;contract_value jsonb;breakdown jsonb;balance_after numeric;channel text;existing public.aqari_rent_payments%rowtype;
begin
 if current_setting('role',true) is distinct from 'service_role' then raise insufficient_privilege using message='SERVER_ONLY';end if;select * into wr from private.aqari_webhook_receipts x where x.id=p_receipt_id for update;if not found or wr.provider<>'knet' then raise no_data_found using message='KNET_WEBHOOK_NOT_FOUND';end if;
 payload:=wr.normalized_payload;provider_ref=btrim(coalesce(payload->>'payment_reference',''));account_ref=btrim(coalesce(payload->>'account_reference',''));status_value=lower(btrim(coalesce(payload->>'provider_status','')));event_value=lower(btrim(coalesce(wr.event_type,'')));currency_value=upper(btrim(coalesce(payload->>'currency','')));
 if event_value<>'payment.succeeded' or status_value<>'succeeded' or provider_ref='' or account_ref='' or currency_value<>'KWD' or coalesce(payload->>'amount','')!~'^[0-9]{1,14}(\.[0-9]{1,3})?$' then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,reason) values(wr.workspace_id,wr.id,'knet','rejected','knet_payment_intent','KNET_WEBHOOK_CANONICAL_FIELDS_INVALID');return jsonb_build_object('processed',false,'reason','KNET_WEBHOOK_CANONICAL_FIELDS_INVALID');end if;
 amount_value:=(payload->>'amount')::numeric;begin occurred:=(payload->>'occurred_at')::timestamptz;exception when others then occurred:=null;end;if amount_value<=0 or amount_value<>round(amount_value,3) or occurred is null or occurred>now()+interval '5 minutes' then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,reason) values(wr.workspace_id,wr.id,'knet','rejected','knet_payment_intent','KNET_WEBHOOK_VALUE_INVALID');return jsonb_build_object('processed',false,'reason','KNET_WEBHOOK_VALUE_INVALID');end if;
 select * into i from private.aqari_knet_payment_intents x where x.workspace_id=wr.workspace_id and x.idempotency_key=account_ref for update;if not found then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,reason) values(wr.workspace_id,wr.id,'knet','rejected','knet_payment_intent','KNET_INTENT_NOT_FOUND');return jsonb_build_object('processed',false,'reason','KNET_INTENT_NOT_FOUND');end if;
 if i.status='paid' then if i.provider_reference=provider_ref and i.amount=amount_value and i.currency=currency_value and i.payment_id is not null then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,'knet','replayed','knet_payment_intent',i.id::text,'KNET_PAYMENT_ALREADY_POSTED');insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason,details) values(i.workspace_id,i.id,'webhook_replay','system','إعادة Webhook لنفس دفعة KNET',jsonb_build_object('providerReference',provider_ref));return private.aqari_knet_intent_snapshot(i)||jsonb_build_object('processed',true,'replayed',true);end if;raise unique_violation using message='KNET_PAID_INTENT_CONFLICT';end if;
 if i.status<>'link_ready' or i.expires_at<occurred or i.provider_reference is distinct from provider_ref or i.amount<>amount_value or i.currency<>currency_value then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,'knet','rejected','knet_payment_intent',i.id::text,'KNET_INTENT_WEBHOOK_MISMATCH');return jsonb_build_object('processed',false,'reason','KNET_INTENT_WEBHOOK_MISMATCH');end if;
 select * into l from public.aqari_leases x where x.workspace_id=i.workspace_id and x.id=i.lease_id and x.status='signed' for update;if not found then raise check_violation using message='SIGNED_LEASE_REQUIRED';end if;select * into u from public.aqari_units x where x.workspace_id=l.workspace_id and x.id=l.unit_id;select * into p from public.aqari_properties x where x.workspace_id=u.workspace_id and x.id=u.property_id;select * into t from public.aqari_tenants x where x.workspace_id=l.workspace_id and x.id=l.tenant_id;if u.id is null or p.id is null or t.id is null then raise check_violation using message='KNET_PAYMENT_SCOPE_MISSING';end if;
 perform private.aqari_refresh_rent_due_schedule(i.workspace_id,i.lease_id);select * into due from private.aqari_rent_due_periods x where x.workspace_id=i.workspace_id and x.lease_id=i.lease_id and x.period=i.period;if not found or due.balance<i.amount then raise check_violation using message='KNET_BALANCE_CHANGED_BEFORE_SETTLEMENT';end if;
 paid_day:=(occurred at time zone 'Asia/Kuwait')::date;period_text:=to_char(i.period,'YYYY-MM');status_label:=case when due.balance=i.amount then 'مدفوع' else 'جزئي' end;serial:=private.aqari_system_rent_receipt_serial(i.workspace_id,l.external_ref,i.id,extract(year from paid_day)::integer);receipt_value:=serial->>'receipt_no';contract_sequence:=(serial->>'contract_sequence')::integer;payment_value:=md5(i.workspace_id::text||':knet-payment:'||i.id::text)::uuid;contract_value:=l.snapshot||jsonb_build_object('id',l.external_ref,'contract_no',l.contract_no,'status','signed','tenant',t.full_name,'property',p.name,'unit',u.unit_no,'start_date',l.start_date,'end_date',l.end_date);
 row_value:=jsonb_build_array(receipt_value,t.full_name,i.amount,status_label,p.name,paid_day,u.unit_no,'دفع إلكتروني KNET مؤكد عبر Webhook',period_text,method_value);ledger:=jsonb_build_object('id','rent-'||receipt_value,'receiptNo',receipt_value,'property',p.name,'unit',u.unit_no,'tenant',t.full_name,'contractId',l.external_ref,'contractNo',l.contract_no,'contractReceiptSequence',contract_sequence,'period',period_text,'due',due.due_amount,'paid',i.amount,'balance',due.balance-i.amount,'paidAt',paid_day,'method',method_value,'transactionNo',provider_ref,'knetTransactionNo',provider_ref,'accountant','النظام / KNET','status',status_label,'note','دفع إلكتروني KNET مؤكد','source','knet-webhook','knetIntentId',i.id);breakdown:=case when jsonb_typeof(contract_value->'rentEntitlement')='object' then private.aqari_rent_period_breakdown(contract_value,period_text) else null end;receipt_json:=jsonb_strip_nulls(jsonb_build_object('id',receipt_value,'contractReceiptSequence',contract_sequence,'template','rent-voucher-v267-1','record',row_value,'contract',contract_value,'tenantId',t.id,'tenantNameEn',coalesce(t.profile->>'nameEn',''),'brand',jsonb_build_object('ar',p.name,'en','AQARI PROPERTY','website','myaqari.com'),'detailsVersion',2,'accountant','النظام / KNET','transactionNo',provider_ref,'rentPeriodBreakdown',breakdown));
 select * into existing from public.aqari_rent_payments x where x.id=payment_value;if found then raise unique_violation using message='KNET_PAYMENT_ID_CONFLICT';end if;insert into public.aqari_rent_payments(id,workspace_id,lease_id,reference,amount,period,paid_at,status,payment_method,record,receipt) values(payment_value,i.workspace_id,i.lease_id,receipt_value,i.amount,i.period,paid_day,status_label,method_value,ledger,receipt_json);update private.aqari_rent_receipt_serial_reservations r set consumed_at=now() where r.receipt_no=receipt_value and r.operation_ref=i.id;perform private.aqari_refresh_rent_due_schedule(i.workspace_id,i.lease_id);select balance into balance_after from private.aqari_rent_due_periods x where x.workspace_id=i.workspace_id and x.lease_id=i.lease_id and x.period=i.period;
 if balance_after=0 then channel:=private.aqari_preferred_delivery_channel(private.aqari_effective_contact_profile(i.workspace_id,t.id,t.profile),t.email,t.phone);if channel is not null then insert into public.aqari_notification_outbox(workspace_id,lease_id,period,kind,channel,idempotency_key) values(i.workspace_id,i.lease_id,i.period,'payment_thanks',channel,'thanks:'||i.lease_id::text||':'||period_text) on conflict(workspace_id,idempotency_key) do nothing;end if;end if;
 update private.aqari_knet_payment_intents set status='paid',payment_id=payment_value,receipt_no=receipt_value,contract_sequence=contract_sequence,webhook_receipt_id=wr.id,updated_at=now() where id=i.id returning * into i;insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason,details) values(i.workspace_id,i.id,'webhook_paid','system','ترحيل دفعة KNET مؤكدة',jsonb_build_object('providerReference',provider_ref,'paymentId',payment_value,'receiptNo',receipt_value,'period',i.period,'amount',i.amount));insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,'knet','processed','knet_payment_intent',i.id::text,'KNET_PAYMENT_POSTED');return private.aqari_knet_intent_snapshot(i)||jsonb_build_object('processed',true,'replayed',false,'remainingBalance',balance_after);
end $$;
revoke all on function public.aqari_process_knet_webhook(uuid) from public,anon,authenticated;grant execute on function public.aqari_process_knet_webhook(uuid) to service_role;
create or replace function public.aqari_record_verified_webhook(p_workspace_id uuid,p_receipt jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$declare r private.aqari_webhook_receipts;begin if current_setting('role',true) is distinct from 'service_role' then raise insufficient_privilege using message='SERVER_ONLY';end if;if p_receipt is null or jsonb_typeof(p_receipt)<>'object' or p_receipt->>'body_sha256'!~'^[a-f0-9]{64}$' or p_receipt->>'signature_sha256'!~'^[a-f0-9]{64}$' then raise exception 'INVALID_VERIFIED_WEBHOOK' using errcode='22023';end if;insert into private.aqari_webhook_receipts(id,workspace_id,provider,provider_event_id,event_type,body_sha256,signature_sha256,occurred_at,status,normalized_payload) values((p_receipt->>'id')::uuid,p_workspace_id,p_receipt->>'provider',p_receipt->>'provider_event_id',p_receipt->>'event_type',p_receipt->>'body_sha256',p_receipt->>'signature_sha256',(p_receipt->>'occurred_at')::timestamptz,'received',p_receipt->'normalized_payload') on conflict(workspace_id,provider,provider_event_id) do nothing returning * into r;if not found then select * into r from private.aqari_webhook_receipts x where x.workspace_id=p_workspace_id and x.provider=p_receipt->>'provider' and x.provider_event_id=p_receipt->>'provider_event_id';return jsonb_build_object('duplicate',true,'id',r.id,'status',r.status);end if;return jsonb_build_object('duplicate',false,'id',r.id,'status',r.status);end $$;
revoke all on function public.aqari_record_verified_webhook(uuid,jsonb) from public,anon,authenticated;grant execute on function public.aqari_record_verified_webhook(uuid,jsonb) to service_role;