-- AQARI V267 Preview/Staging: authenticated KNET intent plus service-only link claim/result.
create or replace function private.aqari_knet_intent_snapshot(r private.aqari_knet_payment_intents) returns jsonb language sql immutable set search_path='' as $$select jsonb_strip_nulls(jsonb_build_object('id',r.id,'workspace_id',r.workspace_id,'lease_id',r.lease_id,'period',r.period,'amount',r.amount,'currency',r.currency,'idempotencyKey',r.idempotency_key,'status',r.status,'expiresAt',r.expires_at,'paymentUrl',r.payment_url,'providerReference',r.provider_reference,'paymentId',r.payment_id,'receiptNo',r.receipt_no,'contractReceiptSequence',r.contract_sequence,'createdAt',r.created_at,'updatedAt',r.updated_at))$$;
revoke all on function private.aqari_knet_intent_snapshot(private.aqari_knet_payment_intents) from public,anon,authenticated,service_role;
create or replace function public.aqari_knet_payment_intent(p_workspace_id uuid,p_action text,p_data jsonb default '{}'::jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare w uuid:=p_workspace_id;d jsonb:=coalesce(p_data,'{}'::jsonb);ident uuid;lid uuid;mon date;amount_value numeric;expires timestamptz;idem text;l public.aqari_leases%rowtype;property_ref uuid;due private.aqari_rent_due_periods%rowtype;existing private.aqari_knet_payment_intents%rowtype;initial_status text;
begin
 if auth.uid() is null or jsonb_typeof(d)<>'object' or not private.aqari_can(w,'collections','read') then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 if p_action='get' then begin ident:=(d->>'id')::uuid;exception when others then raise invalid_parameter_value using message='KNET_INTENT_ID_REQUIRED';end;select * into existing from private.aqari_knet_payment_intents x where x.workspace_id=w and x.id=ident;if not found then raise no_data_found using message='KNET_INTENT_NOT_FOUND';end if;select u.property_id into property_ref from public.aqari_leases z join public.aqari_units u on u.workspace_id=z.workspace_id and u.id=z.unit_id where z.workspace_id=w and z.id=existing.lease_id;if property_ref is null or not private.aqari_can_property(w,property_ref,'properties','read') then raise insufficient_privilege using message='ACCESS_DENIED';end if;return private.aqari_knet_intent_snapshot(existing)||jsonb_build_object('user_id',auth.uid());end if;
 if p_action<>'create' or not private.aqari_can(w,'collections','write') then raise insufficient_privilege using message='KNET_INTENT_WRITE_DENIED';end if;
 if exists(select 1 from jsonb_object_keys(d) k where k not in('id','idempotencyKey','leaseId','period','amount','expiresAt')) then raise invalid_parameter_value using message='INVALID_KNET_INTENT_FIELDS';end if;
 begin ident:=(d->>'id')::uuid;lid:=(d->>'leaseId')::uuid;mon:=(d->>'period')::date;amount_value:=(d->>'amount')::numeric;expires:=(d->>'expiresAt')::timestamptz;exception when others then raise invalid_parameter_value using message='INVALID_KNET_INTENT_FIELDS';end;idem:=btrim(coalesce(d->>'idempotencyKey',''));
 if ident is null or lid is null or mon<>date_trunc('month',mon)::date or amount_value<=0 or amount_value<>round(amount_value,3) or idem!~'^[A-Za-z0-9:_-]{8,200}$' or expires<=now() or expires>now()+interval '24 hours' then raise invalid_parameter_value using message='INVALID_KNET_INTENT_FIELDS';end if;
 select * into l from public.aqari_leases x where x.workspace_id=w and x.id=lid and x.status='signed';if not found then raise check_violation using message='SIGNED_LEASE_REQUIRED';end if;select u.property_id into property_ref from public.aqari_units u where u.workspace_id=w and u.id=l.unit_id;if property_ref is null or not private.aqari_can_property(w,property_ref,'properties','read') then raise insufficient_privilege using message='KNET_PROPERTY_ACCESS_DENIED';end if;
 perform private.aqari_refresh_rent_due_schedule(w,lid);select * into due from private.aqari_rent_due_periods x where x.workspace_id=w and x.lease_id=lid and x.period=mon;if not found or due.balance<=0 or amount_value>due.balance then raise check_violation using message='KNET_AMOUNT_EXCEEDS_CURRENT_BALANCE';end if;
 select * into existing from private.aqari_knet_payment_intents x where x.workspace_id=w and x.idempotency_key=idem for update;if found then if existing.id<>ident or existing.lease_id<>lid or existing.period<>mon or existing.amount<>amount_value or existing.expires_at<>expires then raise unique_violation using message='KNET_IDEMPOTENCY_CONFLICT';end if;return private.aqari_knet_intent_snapshot(existing)||jsonb_build_object('user_id',auth.uid(),'replayed',true);end if;
 initial_status:=case when exists(select 1 from private.aqari_integration_configs c where c.workspace_id=w and c.provider='knet' and c.purpose in('rent_payment','payments','default') and c.mode in('sandbox','live') and c.endpoint_origin is not null and c.secret_reference is not null) then 'pending' else 'awaiting_configuration' end;
 insert into private.aqari_knet_payment_intents(id,workspace_id,lease_id,period,amount,idempotency_key,status,expires_at,created_by) values(ident,w,lid,mon,amount_value,idem,initial_status,expires,auth.uid()) returning * into existing;insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,actor_id,reason,details) values(w,ident,'create','authenticated',auth.uid(),'إنشاء رابط دفع KNET',jsonb_build_object('leaseId',lid,'period',mon,'amount',amount_value,'expiresAt',expires));insert into private.aqari_integration_outbox(id,workspace_id,event_type,aggregate_id,schema_version,payload,idempotency_key,status,attempts,available_at) values(extensions.gen_random_uuid(),w,'knet.payment_link',ident::text,1,jsonb_build_object('intentId',ident),'knet-link:'||ident::text,'pending',0,now()) on conflict(workspace_id,idempotency_key) do nothing;return private.aqari_knet_intent_snapshot(existing)||jsonb_build_object('user_id',auth.uid(),'replayed',false);
end $$;
revoke all on function public.aqari_knet_payment_intent(uuid,text,jsonb) from public,anon;grant execute on function public.aqari_knet_payment_intent(uuid,text,jsonb) to authenticated;
create or replace function public.aqari_knet_payment_link_claim(p_limit integer default 3) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare r private.aqari_integration_outbox%rowtype;i private.aqari_knet_payment_intents%rowtype;c private.aqari_integration_configs%rowtype;l public.aqari_leases%rowtype;due private.aqari_rent_due_periods%rowtype;items jsonb:='[]'::jsonb;claimed integer:=0;
begin
 if current_setting('role',true) is distinct from 'service_role' then raise insufficient_privilege using message='SERVER_ONLY';end if;if p_limit is null or p_limit<1 or p_limit>10 then raise invalid_parameter_value using message='INVALID_KNET_CLAIM_LIMIT';end if;
 update private.aqari_integration_outbox set status='failed',last_error='KNET_LINK_LEASE_EXPIRED',available_at=now() where event_type='knet.payment_link' and status='sending' and available_at<=now() and delivered_at is null and attempts<20;
 for r in select * from private.aqari_integration_outbox o where o.event_type='knet.payment_link' and o.status in('pending','failed') and o.available_at<=now() and o.attempts<20 order by o.available_at,o.created_at,o.id for update skip locked limit p_limit*5 loop
  exit when claimed>=p_limit;begin select * into i from private.aqari_knet_payment_intents x where x.workspace_id=r.workspace_id and x.id=r.aggregate_id::uuid for update;exception when invalid_text_representation then i:=null;end;if i.id is null then update private.aqari_integration_outbox set status='dead_letter',last_error='KNET_INTENT_NOT_FOUND' where id=r.id;continue;end if;if i.status in('paid','cancelled','expired') then update private.aqari_integration_outbox set status='dead_letter',last_error='KNET_INTENT_CLOSED' where id=r.id;continue;end if;
  if i.expires_at<=now() then update private.aqari_knet_payment_intents set status='expired',updated_at=now() where id=i.id;update private.aqari_integration_outbox set status='dead_letter',last_error='KNET_INTENT_EXPIRED' where id=r.id;insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason) values(i.workspace_id,i.id,'expire','system','انتهت صلاحية رابط الدفع قبل إرساله');continue;end if;
  perform private.aqari_refresh_rent_due_schedule(i.workspace_id,i.lease_id);select * into due from private.aqari_rent_due_periods d where d.workspace_id=i.workspace_id and d.lease_id=i.lease_id and d.period=i.period;if not found or due.balance<i.amount then update private.aqari_knet_payment_intents set status='cancelled',updated_at=now() where id=i.id;update private.aqari_integration_outbox set status='dead_letter',last_error='KNET_BALANCE_CHANGED' where id=r.id;insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason) values(i.workspace_id,i.id,'cancel','system','تغير الرصيد قبل توليد رابط الدفع');continue;end if;
  select * into l from public.aqari_leases z where z.workspace_id=i.workspace_id and z.id=i.lease_id and z.status='signed';if not found then update private.aqari_integration_outbox set status='dead_letter',last_error='KNET_SIGNED_LEASE_REQUIRED' where id=r.id;continue;end if;
  select * into c from private.aqari_integration_configs x where x.workspace_id=i.workspace_id and x.provider='knet' and x.purpose in('rent_payment','payments','default') and x.mode in('sandbox','live') and x.endpoint_origin is not null and x.secret_reference is not null order by case x.purpose when 'rent_payment' then 0 when 'payments' then 1 else 2 end,x.updated_at desc limit 1;if not found then update private.aqari_knet_payment_intents set status='awaiting_configuration',updated_at=now() where id=i.id;update private.aqari_integration_outbox set status='failed',last_error='KNET_PROVIDER_CONFIGURATION_MISSING',available_at=now()+interval '15 minutes' where id=r.id;continue;end if;
  update private.aqari_knet_payment_intents set status='pending',updated_at=now() where id=i.id;update private.aqari_integration_outbox o set status='sending',attempts=o.attempts+1,available_at=now()+interval '5 minutes',last_error=null where o.id=r.id;claimed:=claimed+1;items:=items||jsonb_build_array(jsonb_build_object('eventId',r.id,'workspaceId',i.workspace_id,'eventType','knet.payment_link','intentId',i.id,'idempotencyKey',i.idempotency_key,'leaseId',i.lease_id,'contractNo',l.contract_no,'amount',i.amount,'currency',i.currency,'expiresAt',i.expires_at,'endpointOrigin',c.endpoint_origin,'secretReference',c.secret_reference,'callbackPath','/api/provider-webhook?workspace='||i.workspace_id::text||'&provider=knet','returnPath','/app?release=V267&knet_intent='||i.id::text));
 end loop;return items;
end $$;
revoke all on function public.aqari_knet_payment_link_claim(integer) from public,anon,authenticated;grant execute on function public.aqari_knet_payment_link_claim(integer) to service_role;
create or replace function public.aqari_knet_payment_link_result(p_event_id uuid,p_ok boolean,p_retryable boolean default true,p_provider_reference text default null,p_payment_url text default null,p_error text default null) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare r private.aqari_integration_outbox%rowtype;i private.aqari_knet_payment_intents%rowtype;next_status text;err text;ref text;url_value text;delay_minutes integer;
begin
 if current_setting('role',true) is distinct from 'service_role' then raise insufficient_privilege using message='SERVER_ONLY';end if;select * into r from private.aqari_integration_outbox where id=p_event_id and event_type='knet.payment_link' for update;if not found then raise no_data_found using message='KNET_LINK_EVENT_NOT_FOUND';end if;select * into i from private.aqari_knet_payment_intents where workspace_id=r.workspace_id and id=r.aggregate_id::uuid for update;if not found then raise no_data_found using message='KNET_INTENT_NOT_FOUND';end if;if r.status='sent' and i.status='link_ready' then return private.aqari_knet_intent_snapshot(i)||jsonb_build_object('replayed',true);end if;if r.status<>'sending' then raise serialization_failure using message='KNET_LINK_EVENT_NOT_CLAIMED';end if;
 ref:=nullif(left(regexp_replace(coalesce(p_provider_reference,''),'[[:cntrl:]]','','g'),300),'');url_value:=nullif(btrim(coalesce(p_payment_url,'')),'');err:=nullif(left(regexp_replace(coalesce(p_error,''),'[[:cntrl:]]','','g'),1000),'');
 if p_ok then if ref is null or url_value is null or length(url_value)>2048 or url_value not like 'https://%' or url_value~'[[:space:][:cntrl:]]' then raise check_violation using message='INVALID_KNET_PROVIDER_RESULT';end if;update private.aqari_knet_payment_intents set status='link_ready',provider_reference=ref,payment_url=url_value,updated_at=now() where id=i.id returning * into i;update private.aqari_integration_outbox set status='sent',provider_reference=ref,last_error=null,delivered_at=now(),available_at=now() where id=r.id;insert into private.aqari_integration_delivery_events(workspace_id,event_id,attempt,outcome,provider_reference) values(r.workspace_id,r.id,r.attempts,'sent',ref);insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason,details) values(i.workspace_id,i.id,'link_ready','system','تم توليد رابط دفع KNET',jsonb_build_object('providerReference',ref));
 else if coalesce(p_retryable,true) and r.attempts<20 then next_status:='failed';else next_status:='dead_letter';end if;delay_minutes:=least(60,greatest(1,power(2,least(r.attempts,6)-1)::integer));update private.aqari_integration_outbox set status=next_status,last_error=coalesce(err,'KNET_PROVIDER_LINK_FAILED'),available_at=case when next_status='failed' then now()+make_interval(mins=>delay_minutes) else now() end where id=r.id;update private.aqari_knet_payment_intents set status=case when next_status='dead_letter' then 'failed' else 'pending' end,updated_at=now() where id=i.id returning * into i;insert into private.aqari_integration_delivery_events(workspace_id,event_id,attempt,outcome,error_code) values(r.workspace_id,r.id,r.attempts,next_status,coalesce(err,'KNET_PROVIDER_LINK_FAILED'));insert into private.aqari_knet_payment_events(workspace_id,intent_id,action,actor_kind,reason,details) values(i.workspace_id,i.id,'link_failed','system',coalesce(err,'فشل توليد رابط دفع KNET'),jsonb_build_object('retryable',coalesce(p_retryable,true)));end if;return private.aqari_knet_intent_snapshot(i)||jsonb_build_object('replayed',false);
end $$;
revoke all on function public.aqari_knet_payment_link_result(uuid,boolean,boolean,text,text,text) from public,anon,authenticated;grant execute on function public.aqari_knet_payment_link_result(uuid,boolean,boolean,text,text,text) to service_role;