-- AQARI V267 Preview/Staging: provider-neutral KNET intent schema and explicit system receipt actor.
alter table private.aqari_rent_receipt_serial_reservations alter column reserved_by drop not null;
alter table private.aqari_rent_receipt_serial_reservations add column if not exists reservation_actor_kind text not null default 'user';
do $guard$ begin if not exists(select 1 from pg_constraint where conrelid='private.aqari_rent_receipt_serial_reservations'::regclass and conname='aqari_receipt_reservation_actor_check') then alter table private.aqari_rent_receipt_serial_reservations add constraint aqari_receipt_reservation_actor_check check((reservation_actor_kind='user' and reserved_by is not null) or (reservation_actor_kind='system' and reserved_by is null));end if;end $guard$;
create table if not exists private.aqari_knet_payment_intents(id uuid primary key,workspace_id uuid not null references public.aqari_workspaces(id),lease_id uuid not null,period date not null check(period=date_trunc('month',period)::date),amount numeric(18,3) not null check(amount>0 and amount=round(amount,3)),currency text not null default 'KWD' check(currency='KWD'),idempotency_key text not null check(idempotency_key ~ '^[A-Za-z0-9:_-]{8,200}$'),status text not null default 'pending' check(status in('awaiting_configuration','pending','link_ready','paid','failed','expired','cancelled')),expires_at timestamptz not null,provider_reference text,payment_url text,payment_id uuid references public.aqari_rent_payments(id),receipt_no text references private.aqari_rent_receipt_serial_reservations(receipt_no),contract_sequence integer,webhook_receipt_id uuid,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(workspace_id,lease_id) references public.aqari_leases(workspace_id,id),foreign key(workspace_id,webhook_receipt_id) references private.aqari_webhook_receipts(workspace_id,id),unique(workspace_id,idempotency_key),check((receipt_no is null and contract_sequence is null) or (receipt_no is not null and contract_sequence>0)),check(payment_url is null or (length(payment_url) between 9 and 2048 and payment_url like 'https://%' and payment_url !~ '[[:space:][:cntrl:]]')),check(provider_reference is null or (length(provider_reference) between 1 and 300 and provider_reference !~ '[[:cntrl:]]')));
create unique index if not exists aqari_knet_intent_payment_uq on private.aqari_knet_payment_intents(workspace_id,payment_id) where payment_id is not null;
create unique index if not exists aqari_knet_intent_provider_uq on private.aqari_knet_payment_intents(workspace_id,provider_reference) where provider_reference is not null;
create index if not exists aqari_knet_intent_scope on private.aqari_knet_payment_intents(workspace_id,lease_id,period,status,created_at desc);
alter table private.aqari_knet_payment_intents enable row level security;revoke all on private.aqari_knet_payment_intents from public,anon,authenticated,service_role;
drop trigger if exists aqari_knet_intent_no_delete on private.aqari_knet_payment_intents;create trigger aqari_knet_intent_no_delete before delete on private.aqari_knet_payment_intents for each row execute function private.aqari_reject_immutable_change();
create table if not exists private.aqari_knet_payment_events(id bigint generated always as identity primary key,workspace_id uuid not null references public.aqari_workspaces(id),intent_id uuid not null references private.aqari_knet_payment_intents(id),action text not null check(action in('create','link_ready','link_failed','webhook_paid','webhook_replay','cancel','expire')),actor_kind text not null check(actor_kind in('authenticated','system')),actor_id uuid,reason text not null check(length(btrim(reason)) between 1 and 1000),details jsonb not null default '{}'::jsonb check(jsonb_typeof(details)='object'),created_at timestamptz not null default now());create index if not exists aqari_knet_payment_events_scope on private.aqari_knet_payment_events(workspace_id,intent_id,id desc);alter table private.aqari_knet_payment_events enable row level security;revoke all on private.aqari_knet_payment_events from public,anon,authenticated,service_role;drop trigger if exists aqari_knet_payment_events_immutable on private.aqari_knet_payment_events;create trigger aqari_knet_payment_events_immutable before update or delete on private.aqari_knet_payment_events for each row execute function private.aqari_reject_immutable_change();
create table if not exists private.aqari_webhook_processing_events(id bigint generated always as identity primary key,workspace_id uuid not null references public.aqari_workspaces(id),webhook_receipt_id uuid not null,provider text not null,outcome text not null check(outcome in('processed','replayed','rejected')),entity_type text not null,entity_id text,reason text not null,created_at timestamptz not null default now(),foreign key(workspace_id,webhook_receipt_id) references private.aqari_webhook_receipts(workspace_id,id));create index if not exists aqari_webhook_processing_scope on private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,id desc);alter table private.aqari_webhook_processing_events enable row level security;revoke all on private.aqari_webhook_processing_events from public,anon,authenticated,service_role;drop trigger if exists aqari_webhook_processing_immutable on private.aqari_webhook_processing_events;create trigger aqari_webhook_processing_immutable before update or delete on private.aqari_webhook_processing_events for each row execute function private.aqari_reject_immutable_change();