-- AQARI V267 Preview/Staging: record delivery of generated official PDF versions without re-uploading them.
create or replace function public.aqari_official_document_handover(p_workspace_id uuid,p_series_id uuid,p_action text,p_data jsonb default '{}'::jsonb) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare w uuid:=p_workspace_id;sid uuid:=p_series_id;d jsonb:=coalesce(p_data,'{}'::jsonb);s private.aqari_official_document_series;v private.aqari_official_document_versions;a private.aqari_official_pdf_artifacts;h private.aqari_official_document_handovers;void_row private.aqari_official_document_handover_voids;actor uuid:=auth.uid();actor_name text;ident uuid;version_value integer;handed_at timestamptz;copies integer;details jsonb;why text;begin
 if actor is null or jsonb_typeof(d)<>'object' or not private.aqari_official_document_access(w,false) then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 select * into s from private.aqari_official_document_series x where x.workspace_id=w and x.id=sid;if not found or not private.aqari_official_entity_scope(w,s.entity_type,s.entity_id,'read') then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 if p_action='list' then return jsonb_build_object('series',jsonb_build_object('id',s.id,'documentNo',s.document_no,'kind',s.kind,'status',s.status,'currentVersion',s.current_version),'canWrite',private.aqari_official_document_access(w,true) and private.aqari_official_entity_scope(w,s.entity_type,s.entity_id,'write'),'entries',coalesce((select jsonb_agg(to_jsonb(q) order by q.recorded_at desc,q.id desc) from (select h.*,to_jsonb(vd) cancellation from private.aqari_official_document_handovers h left join private.aqari_official_document_handover_voids vd on vd.handover_id=h.id where h.workspace_id=w and h.series_id=sid)q),'[]'::jsonb));end if;
 if not private.aqari_official_document_access(w,true) or not private.aqari_official_entity_scope(w,s.entity_type,s.entity_id,'write') then raise insufficient_privilege using message='ACCESS_DENIED';end if;
 if p_action not in('record','void') then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER_ACTION';end if;
 begin ident:=(d->>'id')::uuid;exception when others then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end;if ident is null then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end if;
 select coalesce(nullif(p.display_name,''),actor::text) into actor_name from public.aqari_profiles p where p.user_id=actor;actor_name:=coalesce(actor_name,actor::text);perform pg_advisory_xact_lock(hashtextextended('aqari-official-handover:'||sid::text,0));
 if p_action='void' then if d-array['id','handoverId','reason']<>'{}'::jsonb then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end if;begin select * into h from private.aqari_official_document_handovers x where x.workspace_id=w and x.series_id=sid and x.id=(d->>'handoverId')::uuid;exception when others then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end;if not found then raise no_data_found using message='OFFICIAL_HANDOVER_NOT_FOUND';end if;why:=btrim(coalesce(d->>'reason',''));if length(why) not between 5 and 500 then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end if;select * into void_row from private.aqari_official_document_handover_voids x where x.handover_id=h.id;if found then if void_row.id=ident and void_row.reason=why then return to_jsonb(void_row);end if;raise unique_violation using message='OFFICIAL_HANDOVER_ALREADY_VOID';end if;insert into private.aqari_official_document_handover_voids(id,handover_id,actor_id,actor_name,reason) values(ident,h.id,actor,actor_name,why) returning * into void_row;return to_jsonb(void_row);end if;
 if d-array['id','version','senderName','recipientName','handedAt','copyKind','copies','method','note']<>'{}'::jsonb then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end if;begin version_value:=(d->>'version')::integer;handed_at:=(d->>'handedAt')::timestamptz;copies:=(d->>'copies')::integer;exception when others then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end;if version_value<1 or copies not between 1 and 99 or handed_at>now()+interval '5 minutes' or d->>'copyKind' not in('original','copy') or d->>'method' not in('hand','courier','electronic') or length(btrim(coalesce(d->>'senderName',''))) not between 2 and 180 or length(btrim(coalesce(d->>'recipientName',''))) not between 2 and 180 or length(coalesce(d->>'note',''))>500 then raise invalid_parameter_value using message='INVALID_OFFICIAL_HANDOVER';end if;
 select * into v from private.aqari_official_document_versions x where x.workspace_id=w and x.series_id=sid and x.version=version_value;if not found then raise no_data_found using message='DOCUMENT_VERSION_NOT_FOUND';end if;select * into a from private.aqari_official_pdf_artifacts x where x.workspace_id=w and x.series_id=sid and x.version=version_value;if not found then raise check_violation using message='ARCHIVED_OFFICIAL_PDF_REQUIRED';end if;if s.status<>'issued' then raise check_violation using message='VOID_OFFICIAL_DOCUMENT_HANDOVER_FORBIDDEN';end if;
 details:=jsonb_build_object('senderName',btrim(d->>'senderName'),'recipientName',btrim(d->>'recipientName'),'handedAt',handed_at,'copyKind',d->>'copyKind','copies',copies,'method',d->>'method','note',btrim(coalesce(d->>'note','')));
 select * into h from private.aqari_official_document_handovers x where x.id=ident;if found then if h.workspace_id=w and h.series_id=sid and h.version=version_value and h.actor_id=actor and h.details=details then return to_jsonb(h);end if;raise unique_violation using message='OFFICIAL_HANDOVER_IDEMPOTENCY_CONFLICT';end if;
 insert into private.aqari_official_document_handovers(id,workspace_id,series_id,version,actor_id,actor_name,details,source_snapshot) values(ident,w,sid,version_value,actor,actor_name,details,jsonb_build_object('documentNo',s.document_no,'kind',s.kind,'status',s.status,'version',v.version,'title',v.title,'contentSha256',v.content_sha256,'pdfSha256',a.pdf_sha256,'issuedAt',v.issued_at,'issuedBy',v.issued_by_name)) returning * into h;return to_jsonb(h);
end$$;
revoke all on function public.aqari_official_document_handover(uuid,uuid,text,jsonb) from public,anon;grant execute on function public.aqari_official_document_handover(uuid,uuid,text,jsonb) to authenticated;
