-- AQARI V267 Preview/Staging: link a verified canonical WhatsApp message to one existing maintenance request.
create table if not exists private.aqari_maintenance_message_events(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.aqari_workspaces(id),request_id uuid not null references public.aqari_maintenance_requests(id),webhook_receipt_id uuid not null unique,
 provider_message_reference text not null check(length(provider_message_reference) between 1 and 200 and provider_message_reference !~ '[[:cntrl:]]'),sender_reference text not null check(length(sender_reference) between 3 and 80 and sender_reference !~ '[[:cntrl:]]'),message_text text not null check(length(message_text) between 1 and 4000 and message_text !~ E'\\x00'),occurred_at timestamptz not null,created_at timestamptz not null default now(),
 foreign key(workspace_id,webhook_receipt_id) references private.aqari_webhook_receipts(workspace_id,id),unique(workspace_id,provider_message_reference)
);
create index if not exists aqari_maintenance_message_request on private.aqari_maintenance_message_events(workspace_id,request_id,occurred_at desc,id);
alter table private.aqari_maintenance_message_events enable row level security;revoke all on private.aqari_maintenance_message_events from public,anon,authenticated,service_role;
drop trigger if exists aqari_maintenance_message_events_immutable on private.aqari_maintenance_message_events;create trigger aqari_maintenance_message_events_immutable before update or delete on private.aqari_maintenance_message_events for each row execute function private.aqari_reject_immutable_change();

create or replace function public.aqari_process_whatsapp_maintenance_webhook(p_receipt_id uuid) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare wr private.aqari_webhook_receipts;existing private.aqari_maintenance_message_events;request_row public.aqari_maintenance_requests;tenant_phone text;payload jsonb;request_value bigint;sender text;sender_digits text;reference text;body text;stored_digits text;
begin
 if current_setting('role',true) is distinct from 'service_role' then raise insufficient_privilege using message='SERVER_ONLY';end if;
 select * into wr from private.aqari_webhook_receipts x where x.id=p_receipt_id for update;if not found then raise no_data_found using message='WEBHOOK_NOT_FOUND';end if;
 select * into existing from private.aqari_maintenance_message_events x where x.webhook_receipt_id=wr.id;if found then insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,wr.provider,'replayed','maintenance_request',existing.request_id::text,'MAINTENANCE_MESSAGE_REPLAY');return jsonb_build_object('status','processed','requestId',existing.request_id,'messageReference',existing.provider_message_reference,'replayed',true);end if;
 if wr.provider<>'whatsapp' or wr.event_type<>'maintenance.message' then raise invalid_parameter_value using message='MAINTENANCE_MESSAGE_WEBHOOK_REQUIRED';end if;payload:=wr.normalized_payload;
 begin request_value:=(payload->>'maintenance_request_no')::bigint;exception when others then request_value:=null;end;sender:=coalesce(payload->>'sender_reference','');reference:=coalesce(payload->>'message_reference','');body:=coalesce(payload->>'message_text','');sender_digits:=regexp_replace(sender,'[^0-9]','','g');
 if request_value is null or length(sender_digits) not between 3 and 20 or length(reference) not between 1 and 200 or length(body) not between 1 and 4000 then update private.aqari_webhook_receipts set status='rejected',rejection_reason='INVALID_MAINTENANCE_MESSAGE' where id=wr.id;insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,wr.provider,'rejected','maintenance_request',null,'INVALID_MAINTENANCE_MESSAGE');return jsonb_build_object('status','rejected','reason','INVALID_MAINTENANCE_MESSAGE');end if;
 select m.*,t.phone into request_row,tenant_phone from public.aqari_maintenance_requests m join public.aqari_leases l on l.workspace_id=m.workspace_id and l.id=m.lease_id and l.tenant_id=m.tenant_id join public.aqari_tenants t on t.workspace_id=m.workspace_id and t.id=m.tenant_id where m.workspace_id=wr.workspace_id and m.request_no=request_value;
 stored_digits:=regexp_replace(coalesce(tenant_phone,''),'[^0-9]','','g');
 if request_row.id is null or stored_digits='' or sender_digits<>stored_digits then update private.aqari_webhook_receipts set status='rejected',rejection_reason='MAINTENANCE_REQUEST_OR_SENDER_MISMATCH' where id=wr.id;insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,wr.provider,'rejected','maintenance_request',null,'MAINTENANCE_REQUEST_OR_SENDER_MISMATCH');return jsonb_build_object('status','rejected','reason','MAINTENANCE_REQUEST_OR_SENDER_MISMATCH');end if;
 insert into private.aqari_maintenance_message_events(workspace_id,request_id,webhook_receipt_id,provider_message_reference,sender_reference,message_text,occurred_at) values(wr.workspace_id,request_row.id,wr.id,reference,sender,body,wr.occurred_at) returning * into existing;
 update private.aqari_webhook_receipts set status='processed',rejection_reason=null where id=wr.id;insert into private.aqari_webhook_processing_events(workspace_id,webhook_receipt_id,provider,outcome,entity_type,entity_id,reason) values(wr.workspace_id,wr.id,wr.provider,'processed','maintenance_request',request_row.id::text,'MAINTENANCE_MESSAGE_LINKED');
 return jsonb_build_object('status','processed','requestId',request_row.id,'requestNo',request_row.request_no,'messageReference',reference,'replayed',false);
end$$;
revoke all on function public.aqari_process_whatsapp_maintenance_webhook(uuid) from public,anon,authenticated;grant execute on function public.aqari_process_whatsapp_maintenance_webhook(uuid) to service_role;
